In [ ]:
!pip install keybert

In [26]:
import pandas as pd

In [ ]:
import keybert
from keybert import KeyBERT

In [4]:
with open('/Users/sergey/PycharmProjects/SemAnalyzer/Keywords/ChizhikMelnikovaZakharov_IMS_2022.txt', 'r', encoding='utf-8') as f:
    doc = f.read()

In [20]:
with open('/Users/sergey/PycharmProjects/SemAnalyzer/Keywords/ChizhikMelnikovaZakharov_IMS_2022_Abstract_rus.txt', 'r', encoding='utf-8') as f:
    doc_abstract = f.read()

In [5]:
kw_model = KeyBERT()

In [6]:
keywords = kw_model.extract_keywords(doc)

In [7]:
keywords = kw_model.extract_keywords(doc, top_n=20)

In [8]:
with open('KeyBERT_top_20_bigram.csv', 'w', encoding='utf-8') as f2:
    for eachkwrd in keywords:
        f2.write(str(eachkwrd[0])+";"+str(eachkwrd[1])+"\n")

In [9]:
keywords = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 3), top_n=20)

In [55]:
with open('KeyBERT_top_20_trigram.csv', 'w', encoding='utf-8') as f2:
    for eachkwrd in keywords:
        f2.write(str(eachkwrd[0])+";"+str(eachkwrd[1])+"\n")

In [ ]:
#KeyBERT Abstract

In [28]:
keywords = kw_model.extract_keywords(doc_abstract, top_n=20)
with open('KeyBERT_abstract_bigram.csv', 'w', encoding='utf-8') as f2:
    for eachkwrd in keywords:
        f2.write(str(eachkwrd[0])+";"+str(eachkwrd[1])+"\n")

In [30]:
keywords = kw_model.extract_keywords(doc_abstract, keyphrase_ngram_range=(1, 3), top_n=20)
with open('KeyBERT_abstract_trigram.csv', 'w', encoding='utf-8') as f2:
    for eachkwrd in keywords:
        f2.write(str(eachkwrd[0])+";"+str(eachkwrd[1])+"\n")

In [31]:
df1 = pd.read_csv('KeyBERT_top_20_bigram.csv', sep=';', header=None)[0]
df2 = pd.read_csv('KeyBERT_abstract_bigram.csv', sep=';', header=None)[0]
df3= pd.read_csv('KeyBERT_top_20_trigram.csv', sep=';', header=None)[0]
df4= pd.read_csv('KeyBERT_abstract_trigram.csv', sep=';', header=None)[0]

pd.concat([df1, df2, df3, df4], axis=1)

,0,0,0,0
0,алгоритмов,алгоритмов,эмоционального состояния жителей,социального самочувствия горожан
1,администраций,самочувствия,частотное появление исследованиях,районных сообществ города
2,здравоохранения,горожан,важнейших аспектов социологического,алгоритмов логистическая регрессия
3,жизнеощущения,регрессия,социального настроения жителей,индекс социального самочувствия
4,программирования,внимания,времени актуализированное социальными,привязкой геолокации авторы
5,агрессивности,города,анализа эмоционального состояния,коммуникации членов сообществ
6,функционирования,авторов,исследований социального настроения,сообществ города санкт
7,социологической,обращено,алгоритмов логистическая регрессия,постам районных сообществ
8,алгоритм,обращается,целостной форме жизнеощущения,самочувствия горожан
9,кодирования,присутствующие,активности жителей районов,конечная цель авторов
10,взаимодействия,сообществ,изучение социального настроения,алгоритмов машинного обучения
11,исследованиях,геолокации,формирования индивидуального настроения,внимания исследования обращается
12,исследования,сбора,использование среднего значения,машинного обучения целью
13,комментариями,исследования,социальное настроение изменения,цель авторов интерактивная
14,проживания,санкт,состояния жителей района,самочувствия горожан связи
15,актуализированное,привязкой,эмоционально окрашенные комментарии,привязкой геолокации
16,создания,описанию,понятия используемых социологии,геолокации авторы предлагают
17,алгоритма,комментариев,взаимодействия коммуникативных особенностей,социального самочувствия
18,аудитории,эксперимента,аспектов социологического анализа,районных сообществ
19,применениях,авторы,своего времени актуализированное,отражающая индекс социального

YAKE

In [ ]:
!pip install git+http://github.com/LIAAD/yake

In [12]:
import yake
custom_kw_extractor = yake.KeywordExtractor(lan="ru", top=20)
keywords = custom_kw_extractor.extract_keywords(doc)

In [13]:
with open('YAKE_top_20.csv', 'w', encoding='utf-8') as f:
    for kw in keywords:
        f.write(f"{kw[0]};{kw[1]}\n")

In [ ]:
#YAKE abstract

In [25]:
custom_kw_extractor = yake.KeywordExtractor(lan="ru", top=20)
keywords = custom_kw_extractor.extract_keywords(doc_abstract)
with open('YAKE_abstract.csv', 'w', encoding='utf-8') as f:
    for kw in keywords:
        f.write(f"{kw[0]};{kw[1]}\n")

In [27]:
df1 = pd.read_csv('/Users/sergey/PycharmProjects/SemAnalyzer/Keywords/YAKE_top_20.csv', sep=';', header=None)[0]
df2 = pd.read_csv('/Users/sergey/PycharmProjects/SemAnalyzer/Keywords/YAKE_abstract.csv', sep=';', header=None)[0]

pd.concat([df1, df2], axis=1)

                                   0                                  0
0             социального настроения            Данная статья посвящена
1                             данных          статья посвящена описанию
2           тональности комментариев    посвящена описанию эксперимента
3                         настроения    оценке тональности комментариев
4    Анализ тональности комментариев  сообществ города Санкт-Петербурга
5                         настроение                    публичных групп
6                        тональности          постам районных сообществ
7                       комментариев          районных сообществ города
8              социальное настроение                      Данная статья
9                                Рис            города Санкт-Петербурга
10                          является                   статья посвящена
11                Анализ тональности                 посвящена описанию
12                       социального              описанию эксперимента
13  социального настроения населения             эксперимента по оценке
14    социального настроения жителей                 оценке тональности
15   комментариев Анализ тональности           тональности комментариев
16   тональности комментариев Анализ              комментариев к постам
17                            Анализ                    постам районных
18      социального настроения имеет                        исследовано
19                          общества              Конечная цель авторов

RuTermExtract

In [ ]:
!pip install rutermextract

In [15]:
from rutermextract import TermExtractor

In [16]:
term_extractor = TermExtractor()

In [17]:
terms = term_extractor(doc, limit=20)

In [42]:
with open('RuTermExtract_top_20.csv', 'w', encoding='utf-8') as f2:
    for term in terms:
        f2.write(f"{term.normalized};{term.count}\n")

In [ ]:
#rutermAbstract

In [21]:
terms_sec = term_extractor(doc_abstract, limit=20)
with open('RuTermExtract_abstract.csv', 'w', encoding='utf-8') as f2:
    for term in terms_sec:
        f2.write(f"{term.normalized};{term.count}\n")

In [24]:
df1 = pd.read_csv('RuTermExtract_top_20.csv', sep=';', header=None)[0]
df2 = pd.read_csv('RuTermExtract_abstract.csv', sep=';', header=None)[0]

pd.concat([df1, df2], axis=1)

                            0                                            0
0                         рис      статистика успешности работы алгоритмов
1       социальное настроение  районные сообщества города санкт-петербурга
2     логистическая регрессия   невербальная коммуникация членов сообществ
3                 комментарии                  фокус внимания исследования
4                    алгоритм              социальное самочувствие горожан
5             социальные сети                       первый этап реализации
6           машинное обучение              оценка тональности комментариев
7                        цель                        методика сбора данных
8                      модель                        конечная цель авторов
9                       spacy                           36 публичных групп
10          социальная группа                               цель выделения
11  индивидуальное настроение                         тематические паблики
12                    уровень                              социальная сеть
13                      текст                                случайный лес
14                    решение                            отражающая индекс
15                предложения                              опорные векторы
16                предложение                        описание эксперимента
17                      набор                         несколько алгоритмов
18                      карта                            машинное обучение
19                       итог                      логистическая регрессия