In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from tqdm import tqdm
from matplotlib import pyplot as plt # show graph

from sklearn.model_selection import GroupShuffleSplit
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
with open("GSD_train.txt", encoding='utf-8') as f:
  data = f.read()
sent = data.split('\n\n')

In [7]:
tokens = []
for sentence in sent:
    s = []
    for word in sentence.split('\n'):
        if word:
            token = (word.split()[1], word.split()[3])
            s.append(token)
    tokens.append(s)

In [25]:
tagged_words = [(i, *tup) for i, sent in enumerate(tokens) for tup in sent]
tagged_words

[(0, 'Начальный', 'ADJ'),
 (0, 'ролик', 'NOUN'),
 (0, ',', 'PUNCT'),
 (0, 'или', 'CCONJ'),
 (0, 'опенинг', 'NOUN'),
 (0, '(', 'PUNCT'),
 (0, 'от', 'ADP'),
 (0, ',', 'PUNCT'),
 (0, 'сокр.', 'ADV'),
 (0, ':', 'PUNCT'),
 (0, 'OP', 'X'),
 (0, ')', 'PUNCT'),
 (0, ',', 'PUNCT'),
 (0, 'как', 'ADP'),
 (0, 'правило', 'NOUN'),
 (0, ',', 'PUNCT'),
 (0, 'представляет', 'VERB'),
 (0, 'собой', 'PRON'),
 (0, 'анимацию', 'NOUN'),
 (0, ',', 'PUNCT'),
 (0, 'изображающую', 'VERB'),
 (0, 'главных', 'ADJ'),
 (0, 'героев', 'NOUN'),
 (0, 'аниме', 'NOUN'),
 (0, 'и', 'CCONJ'),
 (0, 'отражающую', 'VERB'),
 (0, 'его', 'DET'),
 (0, 'стиль', 'NOUN'),
 (0, '.', 'PUNCT'),
 (1, 'Стропило', 'NOUN'),
 (1, ',', 'PUNCT'),
 (1, 'означающее', 'VERB'),
 (1, 'победителя', 'NOUN'),
 (1, ',', 'PUNCT'),
 (1, 'окрашено', 'VERB'),
 (1, 'в', 'ADP'),
 (1, 'красный', 'ADJ'),
 (1, 'цвет', 'NOUN'),
 (1, '--', 'PUNCT'),
 (1, 'цвет', 'NOUN'),
 (1, 'гербового', 'ADJ'),
 (1, 'щита', 'NOUN'),
 (1, 'Москвы', 'PROPN'),
 (1, ',', 'PUNCT'),
 (1, 'стропило', 'NOUN'),
 (1, ',', 'PUNCT'),
 (1, 'означающее', 'VERB'),
 (1, 'побеждённого', 'VERB'),
 (1, ',', 'PUNCT'),
 (1, 'имеет', 'VERB'),
 (1, 'зелёный', 'ADJ'),
 (1, 'цвет', 'NOUN'),
 (1, '--', 'PUNCT'),
 (1, 'цвет', 'NOUN'),
 (1, 'ислама', 'NOUN'),
 (1, '.', 'PUNCT'),
 (2, 'Он', 'PRON'),
 (2, 'и', 'PART'),
 (2, 'являлся', 'VERB'),
 (2, '&#39;&#39;', 'PUNCT'),
 (2, 'полным', 'ADJ'),
 (2, 'властелином', 'NOUN'),
 (2, 'всей', 'DET'),
 (2, 'Ахсауской', 'ADJ'),
 (2, 'местности', 'NOUN'),
 (2, '&#39;&#39;', 'PUNCT'),
 (2, 'и', 'CCONJ'),
 (2, 'родоначальником', 'NOUN'),
 (2, 'Телакуровых', 'PROPN'),
 (2, ',', 'PUNCT'),
 (2, 'построивших', 'VERB'),
 (2, 'здесь', 'ADV'),
 (2, 'свой', 'DET'),
 (2, 'замок', 'NOUN'),
 (2, '.', 'PUNCT'),
 (3, 'Сержант', 'NOUN'),
 (3, 'посоветовал', 'VERB'),
 (3, 'Баклсу', 'PROPN'),
 (3, 'пойти', 'VERB'),
 (3, 'на', 'ADP'),
 (3, 'работу', 'NOUN'),
 (3, 'водителем', 'NOUN'),
 (3, 'машины', 'NOUN'),
 (3, 'скорой', 'ADJ'),
 (3, 'помощи', 'NOUN'),
 (3, '.', 'PUNCT'),
 (4, 'Барыкина', 'PROPN'),
 (4, 'иногда', 'ADV'),
 (4, 'называют', 'VERB'),
 (4, '``', 'PUNCT'),
 (4, 'отцом', 'NOUN'),
 (4, 'русского', 'ADJ'),
 (4, 'регги', 'NOUN'),
 (4, '&#39;&#39;', 'PUNCT'),
 (4, '.', 'PUNCT'),
 (5, 'Безгачиха', 'PROPN'),
 (5, '--', 'PUNCT'),
 (5, 'деревня', 'NOUN'),
 (5, 'в', 'ADP'),
 (5, 'Бабушкинском', 'ADJ'),
 (5, 'районе', 'NOUN'),
 (5, 'Вологодской', 'ADJ'),
 (5, 'области', 'NOUN'),
 (5, '.', 'PUNCT'),
 (6, 'В', 'ADP'),
 (6, '2006', 'ADJ'),
 (6, 'году', 'NOUN'),
 (6, 'газета', 'NOUN'),
 (6, '``', 'PUNCT'),
 (6, 'Вестник', 'NOUN'),
 (6, 'культуры', 'NOUN'),
 (6, '&#39;&#39;', 'PUNCT'),
 (6, 'подверглась', 'VERB'),
 (6, 'дискриминации', 'NOUN'),
 (6, 'со', 'ADP'),
 (6, 'стороны', 'NOUN'),
 (6, 'официальной', 'ADJ'),
 (6, 'сети', 'NOUN'),
 (6, 'распространения', 'NOUN'),
 (6, 'СМИ', 'NOUN'),
 (6, ',', 'PUNCT'),
 (6, 'что', 'PRON'),
 (6, 'вынудило', 'VERB'),
 (6, 'её', 'DET'),
 (6, 'учредителей', 'NOUN'),
 (6, 'отказаться', 'VERB'),
 (6, 'от', 'ADP'),
 (6, 'сотрудничества', 'NOUN'),
 (6, 'с', 'ADP'),
 (6, 'РУП', 'PROPN'),
 (6, '``', 'PUNCT'),
 (6, 'Белсоюзпечать', 'PROPN'),
 (6, '&#39;&#39;', 'PUNCT'),
 (6, '.', 'PUNCT'),
 (7, 'Хобби', 'NOUN'),
 (7, ':', 'PUNCT'),
 (7, 'боевые', 'ADJ'),
 (7, 'искусства', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'фотография', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'верховая', 'ADJ'),
 (7, 'езда', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'рыбная', 'ADJ'),
 (7, 'ловля', 'NOUN'),
 (7, 'и', 'CCONJ'),
 (7, 'написание', 'NOUN'),
 (7, 'сценариев', 'NOUN'),
 (7, '(', 'PUNCT'),
 (7, 'Дэниел', 'PROPN'),
 (7, 'уже', 'ADV'),
 (7, 'закончил', 'VERB'),
 (7, 'один', 'NUM'),
 (7, 'сценарий', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'который', 'PRON'),
 (7, 'называется', 'VERB'),
 (7, '``', 'PUNCT'),
 (7, 'Парень', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'молния', 'NOUN'),
 (7, '&#39;&#39;', 'PUNCT'),
 (7, '(', 'PUNCT'),
 (7, 'The', 'X'),
 (7, 'Lightning', 'X'),
 (7, 'Kid', 'X'),
 (7, ')', 'PUNCT'),
 (7, ',', 'PUNCT'),
 (7, 'и', 'CCONJ'),
 (7, 'работает', 'VERB'),
 (7, 'над', 'ADP'),
 (7, 'вторым', 'ADJ'),
 (7, '--', 'PUNCT'),
 (7, '``', 'PUNCT'),
 (7, 'Шаолиньский', 'ADJ'),
 (7, 'монах', 'NOUN'),
 (7, '&#39;&#39;', 'PUNCT'),
 (7, '(', 'PUNCT'),
 (7, 'The', 'X'),
 (7, 'Shaolin', 'X'),
 (7, 'Monk', 'X'),
 (7, ')', 'PUNCT'),
 (7, ')', 'PUNCT'),
 (7, '.', 'PUNCT'),
 (8, 'Такое', 'DET'),
 (8, 'расположение', 'NOUN'),
 (8, 'орудий', 'NOUN'),
 (8, ',', 'PUNCT'),
 (8, 'когда', 'ADV'),
 (8, 'батарея', 'NOUN'),
 (8, 'хорошо', 'ADV'),
 (8, 'замаскирована', 'VERB'),
 (8, 'и', 'CCONJ'),
 (8, 'становится', 'VERB'),
 (8, 'малоуязвимой', 'ADJ'),
 (8, 'для', 'ADP'),
 (8, 'противника', 'NOUN'),
 (8, ',', 'PUNCT'),
 (8, 'а', 'CCONJ'),
 (8, 'стрельба', 'NOUN'),
 (8, 'производится', 'VERB'),
 (8, 'по', 'ADP'),
 (8, 'вспомогательной', 'ADJ'),
 (8, 'точке', 'NOUN'),
 (8, 'наводки', 'NOUN'),
 (8, ',', 'PUNCT'),
 (8, 'было', 'AUX'),
 (8, 'впервые', 'ADV'),
 (8, 'освоено', 'VERB'),
 (8, 'в', 'ADP'),
 (8, 'русско-японскую', 'ADJ'),
 (8, 'войну', 'NOUN'),
 (8, '1904', 'ADJ'),
 (8, '-', 'PUNCT'),
 (8, '1905', 'ADJ'),
 (8, 'гг', 'NOUN'),
 (8, '.', 'PUNCT'),
 (9, 'Популяции', 'NOUN'),
 (9, 'Западной', 'ADJ'),
 (9, 'и', 'CCONJ'),
 (9, 'Северной', 'ADJ'),
 (9, 'Европы', 'PROPN'),
 (9, 'зимуют', 'VERB'),
 (9, 'в', 'ADP'),
 (9, 'Западной', 'ADJ'),
 (9, 'Африке', 'PROPN'),
 (9, 'к', 'ADP'),
 (9, 'югу', 'NOUN'),
 (9, 'от', 'ADP'),
 (9, 'Сахары', 'PROPN'),
 (9, '.', 'PUNCT'),
 (10, 'Один', 'NUM'),
 (10, 'из', 'ADP'),
 (10, 'пионеров', 'NOUN'),
 (10, 'исследований', 'NOUN'),
 (10, 'в', 'ADP'),
 (10, 'области', 'NOUN'),
 (10, 'авиации', 'NOUN'),
 (10, '.', 'PUNCT'),
 (11, '17', 'ADJ'),
 (11, 'апреля', 'NOUN'),
 (11, '1945', 'ADJ'),
 (11, 'газета', 'NOUN'),
 (11, '``', 'PUNCT'),
 (11, 'Ноорте', 'ADJ'),
 (11, 'Хяэль', 'PROPN'),
 (11, '&#39;&#39;', 'PUNCT'),
 (11, 'писала', 'VERB'),
 (11, ':', 'PUNCT'),
 (11, '``', 'PUNCT'),
 (11, 'В', 'ADP'),
 (11, 'субботу', 'NOUN'),
 (11, ',', 'PUNCT'),
 (11, '14-го', 'ADJ'),
 (11, 'числа', 'NOUN'),
 (11, ',', 'PUNCT'),
 (11, 'прошло', 'VERB'),
 (11, 'захоронение', 'NOUN'),
 (11, 'в', 'ADP'),
 (11, 'общей', 'ADJ'),
 (11, 'могиле', 'NOUN'),
 (11, 'двенадцати', 'NUM'),
 (11, 'героических', 'ADJ'),
 (11, 'бойцов', 'NOUN'),
 (11, 'Красной', 'ADJ'),
 (11, 'армии', 'NOUN'),
 (11, ',', 'PUNCT'),
 (11, 'погибших', 'VERB'),
 (11, 'в', 'ADP'),
 (11, 'день', 'NOUN'),
 (11, 'освобождения', 'NOUN'),
 (11, 'Таллина', 'PROPN'),
 (11, 'от', 'ADP'),
 (11, 'гитлеровских', 'ADJ'),
 (11, 'поработителей', 'NOUN'),
 (11, '&#39;&#39;', 'PUNCT'),
 (11, '.', 'PUNCT'),
 (12, 'Буроголовый', 'ADJ'),
 (12, 'коровий', 'ADJ'),
 (12, 'трупиал', 'NOUN'),
 (12, '--', 'PUNCT'),
 (12, 'это', 'PART'),
 (12, 'гнездовой', 'ADJ'),
 (12, 'паразит', 'NOUN'),
 (12, ',', 'PUNCT'),
 (12, 'который', 'PRON'),
 (12, 'откладывает', 'VERB'),
 (12, 'свои', 'DET'),
 (12, 'яйца', 'NOUN'),
 (12, 'в', 'ADP'),
 (12, 'гнёзда', 'NOUN'),
 (12, 'других', 'ADJ'),
 (12, 'маленьких', 'ADJ'),
 (12, 'певчих', 'ADJ'),
 (12, 'птиц', 'NOUN'),
 (12, ',', 'PUNCT'),
 (12, 'особенно', 'ADV'),
 (12, 'в', 'ADP'),
 (12, 'чашеобразные', 'ADJ'),
 (12, 'гнёзда', 'NOUN'),
 (12, ',', 'PUNCT'),
 (12, 'такие', 'DET'),
 (12, 'как', 'SCONJ'),
 (12, 'у', 'ADP'),
 (12, 'жёлтой', 'ADJ'),
 (12, 'древесницы', 'NOUN'),
 (12, '.', 'PUNCT'),
 (13, 'Для', 'ADP'),
 (13, 'аварийного', 'ADJ'),
 (13, 'электроснабжения', 'NOUN'),
 (13, 'предусмотрены', 'VERB'),
 (13, 'источники', 'NOUN'),
 (13, 'автономного', 'ADJ'),
 (13, 'электроснабжения', 'NOUN'),
 (13, ':', 'PUNCT'),
 (13, 'автоматизированные', 'ADJ'),
 (13, 'дизель-генераторы', 'NOUN'),
 (13, 'и', 'CCONJ'),
 (13, 'агрегат', 'NOUN'),
 (13, 'бесперебойного', 'ADJ'),
 (13, 'питания', 'NOUN'),
 (13, 'на', 'ADP'),
 (13, 'основе', 'NOUN'),
 (13, 'аккумуляторных', 'ADJ'),
 (13, 'батарей', 'NOUN'),
 (13, '.', 'PUNCT'),
 (14, 'Участник', 'NOUN'),
 (14, 'Великой', 'ADJ'),
 (14, 'Отечественной', 'ADJ'),
 (14, 'войны', 'NOUN'),
 (14, 'с', 'ADP'),
 (14, 'июня', 'NOUN'),
 (14, '1941', 'ADJ'),
 (14, 'года', 'NOUN'),
 (14, '.', 'PUNCT'),
 (15, 'В', 'ADP'),
 (15, 'передаче', 'NOUN'),
 (15, 'приняли', 'VERB'),
 (15, 'участие', 'NOUN'),
 (15, 'поэт', 'NOUN'),
 (15, 'Андрей', 'PROPN'),
 (15, 'Вознесенский', 'PROPN'),
 (15, ',', 'PUNCT'),
 (15, 'художник', 'NOUN'),
 (15, ',', 'PUNCT'),
 (15, 'модельер', 'NOUN'),
 (15, 'Вячеслав', 'PROPN'),
 (15, 'Зайцев', 'PROPN'),
 (15, ',', 'PUNCT'),
 (15, 'композитор', 'NOUN'),
 (15, 'Родион', 'PROPN'),
 (15, 'Щедрин', 'PROPN'),
 (15, '.', 'PUNCT'),
 (16, 'В', 'ADP'),
 (16, 'течение', 'NOUN'),
 (16, '3', 'NUM'),
 (16, 'лет', 'NOUN'),
 (16, '10', 'NUM'),
 (16, 'месяцев', 'NOUN'),
 (16, 'Виноградов', 'PROPN'),
 (16, 'являлся', 'VERB'),
 (16, 'младшим', 'ADJ'),
 (16, 'офицером', 'NOUN'),
 (16, ',', 'PUNCT'),
 (16, 'воспитателем', 'NOUN'),
 (16, 'Одесского', 'ADJ'),
 (16, 'пехотного', 'ADJ'),
 (16, 'юнкерского', 'ADJ'),
 (16, 'училища', 'NOUN'),
 (16, ',', 'PUNCT'),
 (16, '6', 'ADJ'),
 (16, 'мая', 'NOUN'),
 (16, '1901', 'ADJ'),
 (16, 'года', 'NOUN'),
 (16, 'произведён', 'VERB'),
 (16, 'в', 'ADP'),
 (16, 'капитаны', 'NOUN'),
 (16, 'и', 'CCONJ'),
 (16, 'затем', 'ADV'),
 (16, 'около', 'ADP'),
 (16, 'полутора', 'NUM'),
 (16, 'лет', 'NOUN'),
 (16, 'был', 'AUX'),
 (16, 'помощником', 'NOUN'),
 (16, 'инспектора', 'NOUN'),
 (16, 'классов', 'NOUN'),
 (16, 'Иркутского', 'ADJ'),
 (16, 'пехотного', 'ADJ'),
 (16, 'юнкерского', 'ADJ'),
 (16, 'училища', 'NOUN'),
 (16, '.', 'PUNCT'),
 (17, 'Во́дская', 'ADJ'),
 (17, 'пяти́на', 'NOUN'),
 (17, '(', 'PUNCT'),
 (17, 'или', 'CCONJ'),
 (17, 'Вотская', 'ADJ'),
 (17, 'пятина', 'NOUN'),
 (17, ',', 'PUNCT'),
 (17, 'Вотьская', 'ADJ'),
 (17, 'пятина', 'NOUN'),
 (17, ',', 'PUNCT'),
 (17, 'Вотская', 'ADJ'),
 (17, 'земля', 'NOUN'),
 (17, ',', 'PUNCT'),
 (17, ')', 'PUNCT'),
 (17, '--', 'PUNCT'),
 (17, 'северо-западная', 'ADJ'),
 (17, 'пятина', 'NOUN'),
 (17, 'Новгородской', 'ADJ'),
 (17, 'земли', 'NOUN'),
 (17, 'до', 'ADP'),
 (17, 'XVIII', 'ADJ'),
 (17, 'века', 'NOUN'),
 (17, '.', 'PUNCT'),
 (18, 'Вечно', 'ADV'),
 (18, 'подозреваемый', 'VERB'),
 (18, 'в', 'ADP'),
 (18, 'политической', 'ADJ'),
 (18, 'неблагонадёжности', 'NOUN'),
 (18, ',', 'PUNCT'),
 (18, 'не', 'PART'),
 (18, 'чувствуя', 'VERB'),
 (18, 'себя', 'PRON'),
 (18, 'во', 'ADP'),
 (18, 'Франции', 'PROPN'),
 (18, 'в', 'ADP'),
 (18, 'безопасности', 'NOUN'),
 (18, ',', 'PUNCT'),
 (18, 'Вольтер', 'PROPN'),
 (18, 'последовал', 'VERB'),
 (18, '(', 'PUNCT'),
 (18, '1751', 'ADJ'),
 (18, ')', 'PUNCT'),
 (18, 'приглашению', 'NOUN'),
 (18, 'прусского', 'ADJ'),
 (18, 'короля', 'NOUN'),
 (18, 'Фридриха', 'PROPN'),
 (18, 'II', 'ADJ'),
 (18, ',', 'PUNCT'),
 (18, 'с', 'ADP'),
 (18, 'которым', 'PRON'),
 (18, 'давно', 'ADV'),
 (18, '(', 'PUNCT'),
 (18, 'с', 'ADP'),
 (18, '1736', 'ADJ'),
 (18, ')', 'PUNCT'),
 (18, 'находился', 'VERB'),
 (18, 'в', 'ADP'),
 (18, 'переписке', 'NOUN'),
 (18, ',', 'PUNCT'),
 (18, 'и', 'CCONJ'),
 (18, 'поселился', 'VERB'),
 (18, 'в', 'ADP'),
 (18, 'Берлине', 'PROPN'),
 (18, '(', 'PUNCT'),
 (18, 'Потсдаме', 'PROPN'),
 (18, ')', 'PUNCT'),
 (18, ',', 'PUNCT'),
 (18, 'но', 'CCONJ'),
 (18, ',', 'PUNCT'),
 (18, 'вызвав', 'VERB'),
 (18, 'недовольство', 'NOUN'),
 (18, 'короля', 'NOUN'),
 (18, 'неблаговидными', 'ADJ'),
 (18, 'денежными', 'ADJ'),
 (18, 'спекуляциями', 'NOUN'),
 (18, ',', 'PUNCT'),
 (18, 'а', 'CCONJ'),
 (18, 'также', 'CCONJ'),
 (18, 'ссорой', 'NOUN'),
 (18, 'с', 'ADP'),
 (18, 'президентом', 'NOUN'),
 (18, 'Академии', 'NOUN'),
 (18, 'Мопертюи', 'PROPN'),
 (18, '(', 'PUNCT'),
 (18, 'карикатурно', 'ADV'),
 (18, 'изображённым', 'VERB'),
 (18, 'Вольтером', 'PROPN'),
 (18, 'в', 'ADP'),
 (18, '``', 'PUNCT'),
 (18, 'Диатрибе', 'NOUN'),
 (18, 'доктора', 'NOUN'),
 (18, 'Акакия', 'PROPN'),
 (18, '&#39;&#39;', 'PUNCT'),
 (18, ')', 'PUNCT'),
 (18, ',', 'PUNCT'),
 (18, 'был', 'AUX'),
 (18, 'вынужден', 'VERB'),
 (18, 'покинуть', 'VERB'),
 (18, 'Пруссию', 'PROPN'),
 (18, 'и', 'CCONJ'),
 (18, 'поселился', 'VERB'),
 (18, 'в', 'ADP'),
 (18, 'Швейцарии', 'PROPN'),
 (18, '(', 'PUNCT'),
 (18, '1753', 'NUM'),
 (18, ')', 'PUNCT'),
 (18, '.', 'PUNCT'),
 (19, 'Разработаны', 'VERB'),
 (19, 'теоретические', 'ADJ'),
 (19, 'основы', 'NOUN'),
 (19, 'и', 'CCONJ'),
 (19, 'созданы', 'VERB'),
 (19, 'новые', 'ADJ'),
 (19, 'виды', 'NOUN'),
 (19, 'полимерных', 'ADJ'),
 (19, 'связующих', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'лакокрасочных', 'ADJ'),
 (19, 'материалов', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'клеев', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'герметиков', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'теплозащитных', 'ADJ'),
 (19, 'и', 'CCONJ'),
 (19, 'эрозионностойких', 'ADJ'),
 (19, 'материалов', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'специальных', 'ADJ'),
 (19, 'покрытий', 'NOUN'),
 (19, ',', 'PUNCT'),
 (19, 'многофункциональных', 'ADJ'),
 (19, 'неметаллических', 'ADJ'),
 (19, '(', 'PUNCT'),
 (19, 'радиопрозрачных', 'ADJ'),
 (19, ',', 'PUNCT'),
 (19, 'радиопоглощающих', 'ADJ'),
 (19, ')', 'PUNCT'),
 (19, 'материалов', 'NOUN'),
 (20, 'Вышивки', 'NOUN'),
 (20, 'Полесья', 'PROPN'),
 (20, '--', 'PUNCT'),
 (20, 'простые', 'ADJ'),
 (20, 'и', 'CCONJ'),
 (20, 'четкие', 'ADJ'),
 (20, 'по', 'ADP'),
 (20, 'композиции', 'NOUN'),
 (20, '.', 'PUNCT'),
 (21, 'В', 'ADP'),
 (21, '1959', 'ADJ'),
 (21, 'году', 'NOUN'),
 (21, 'перешел', 'VERB'),
 (21, 'на', 'ADP'),
 (21, 'шахту', 'NOUN'),
 (21, '``', 'PUNCT'),
 (21, 'Боково', 'PROPN'),
 (21, '-', 'PUNCT'),
 (21, 'Платовская', 'ADJ'),
 (21, '&#39;&#39;', 'PUNCT'),
 (21, ',', 'PUNCT'),
 (21, 'где', 'ADV'),
 (21, 'его', 'PRON'),
 (21, 'назначили', 'VERB'),
 (21, 'бригадиром', 'NOUN'),
 (21, '.', 'PUNCT'),
 (22, 'В', 'ADP'),
 (22, 'сезоне', 'NOUN'),
 (22, '2007/08', 'NUM'),
 (22, 'Алекс', 'PROPN'),
 (22, 'Фергюсон', 'PROPN'),
 (22, 'активно', 'ADV'),
 (22, 'использовал', 'VERB'),
 (22, 'систему', 'NOUN'),
 (22, 'ротации', 'NOUN'),
 (22, 'игроков', 'NOUN'),
 (22, 'полузащиты', 'NOUN'),
 (22, ',', 'PUNCT'),
 (22, 'выпуская', 'VERB'),
 (22, 'на', 'ADP'),
 (22, 'одну', 'NUM'),
 (22, 'позицию', 'NOUN'),
 (22, 'или', 'CCONJ'),
 (22, 'Гиггза', 'PROPN'),
 (22, ',', 'PUNCT'),
 (22, 'или', 'CCONJ'),
 (22, 'новичков', 'NOUN'),
 (22, 'команды', 'NOUN'),
 (22, 'Нани', 'PROPN'),
 (22, 'и', 'CCONJ'),
 (22, 'Андерсона', 'PROPN'),
 (22, '.', 'PUNCT'),
 (23, 'Текст', 'NOUN'),
 (23, 'был', 'AUX'),
 (23, 'написан', 'VERB'),
 (23, 'по', 'ADP'),
 (23, '-', 'PUNCT'),
 (23, 'латыни', 'NOUN'),
 (23, '.', 'PUNCT'),
 (24, 'Гомологическая', 'ADJ'),
 (24, 'алгебра', 'NOUN'),
 (24, '--', 'PUNCT'),
 (24, 'ветвь', 'NOUN'),
 (24, 'алгебры', 'NOUN'),
 (24, ',', 'PUNCT'),
 (24, 'изучающая', 'VERB'),
 (24, 'алгебраические', 'ADJ'),
 (24, 'объекты', 'NOUN'),
 (24, ',', 'PUNCT'),
 (24, 'заимствованные', 'VERB'),
 (24, 'из', 'ADP'),
 (24, 'алгебраической', 'ADJ'),
 (24, 'топологии', 'NOUN'),
 (24, '.', 'PUNCT'),
 (25, 'Греческое', 'ADJ'),
 (25, 'министерство', 'NOUN'),
 (25, 'здравоохранения', 'NOUN'),
 (25, 'издало', 'VERB'),
 (25, 'специальное', 'ADJ'),
 (25, 'разрешение', 'NOUN'),
 (25, 'разрешающее', 'VERB'),
 (25, 'донорство', 'NOUN'),
 (25, 'и', 'CCONJ'),
 (25, 'отправку', 'NOUN'),
 (25, 'крови', 'NOUN'),
 (25, 'из', 'ADP'),
 (25, 'муниципалитетов', 'NOUN'),
 (25, 'Каламария', 'PROPN'),
 (25, ',', 'PUNCT'),
 (25, 'Пенталофос', 'PROPN'),
 (25, 'и', 'CCONJ'),
 (25, 'Флорина', 'PROPN'),
 (25, ',', 'PUNCT'),
 (25, 'а', 'CCONJ'),
 (25, 'также', 'CCONJ'),
 (25, 'от', 'ADP'),
 (25, 'монахов', 'NOUN'),
 (25, 'сербского', 'ADJ'),
 (25, 'монастыря', 'NOUN'),
 (25, 'Хиландар', 'PROPN'),
 (25, 'на', 'ADP'),
 (25, 'Афоне', 'PROPN'),
 (25, ',', 'PUNCT'),
 (25, 'и', 'CCONJ'),
 (25, 'включение', 'NOUN'),
 (25, 'крови', 'NOUN'),
 (25, 'в', 'ADP'),
 (25, 'гуманитарную', 'ADJ'),
 (25, 'помощь', 'NOUN'),
 (25, '.', 'PUNCT'),
 (26, 'Она', 'PRON'),
 (26, 'была', 'AUX'),
 (26, 'настолько', 'ADV'),
 (26, 'скупа', 'ADJ'),
 (26, ',', 'PUNCT'),
 (26, 'что', 'SCONJ'),
 (26, 'даже', 'PART'),
 (26, 'отказывала', 'VERB'),
 (26, 'жнецам', 'NOUN'),
 (26, 'в', 'ADP'),
 (26, 'пиве', 'NOUN'),
 (26, 'во', 'ADP'),
 (26, 'время', 'NOUN'),
 (26, 'жатвы', 'NOUN'),
 (26, '.', 'PUNCT'),
 (27, 'В', 'ADP'),
 (27, 'Средние', 'ADJ'),
 (27, 'века', 'NOUN'),
 (27, 'в', 'ADP'),
 (27, 'Дании', 'PROPN'),
 (27, 'были', 'AUX'),
 (27, 'популярны', 'ADJ'),
 (27, 'песни', 'NOUN'),
 (27, 'скальдов', 'NOUN'),
 (27, ',', 'PUNCT'),
 (27, 'позднее', 'ADV'),
 (27, 'с', 'ADP'),
 (27, 'христианизацией', 'NOUN'),
 (27, 'страны', 'NOUN'),
 (27, 'распространение', 'NOUN'),
 (27, 'получили', 'VERB'),
 (27, 'григорианские', 'ADJ'),
 (27, 'хоралы', 'NOUN'),
 (27, '.', 'PUNCT'),
 (28, 'Через', 'ADP'),
 (28, 'некоторое', 'DET'),
 (28, 'время', 'NOUN'),
 (28, 'она', 'PRON'),
 (28, 'рассказала', 'VERB'),
 (28, 'в', 'ADP'),
 (28, 'интервью', 'NOUN'),
 (28, 'журналу', 'NOUN'),
 (28, '``', 'PUNCT'),
 (28, 'Огонек', 'NOUN'),
 (28, '&#39;&#39;', 'PUNCT'),
 (28, ',', 'PUNCT'),
 (28, 'что', 'SCONJ'),
 (28, 'во', 'ADP'),
 (28, 'время', 'NOUN'),
 (28, 'работы', 'NOUN'),
 (28, 'в', 'ADP'),
 (28, 'мэрии', 'NOUN'),
 (28, 'конфликтовала', 'VERB'),
 (28, 'с', 'ADP'),
 (28, 'пресс-секретарем', 'NOUN'),
 (28, 'мэрии', 'NOUN'),
 (28, 'Москвы', 'PROPN'),
 (28, 'Сергеем', 'PROPN'),
 (28, 'Цоем', 'PROPN'),
 (28, '.', 'PUNCT'),
 (29, '``', 'PUNCT'),
 (29, 'Дети', 'NOUN'),
 (29, 'гор', 'NOUN'),
 (29, '&#39;&#39;', 'PUNCT'),
 (29, '--', 'PUNCT'),
 (29, 'альбом', 'NOUN'),
 (29, 'российской', 'ADJ'),
 (29, 'рок-группы', 'NOUN'),
 (29, '``', 'PUNCT'),
 (29, 'Чайф', 'PROPN'),
 (29, '&#39;&#39;', 'PUNCT'),
 (29, '.', 'PUNCT'),
 (30, 'Жена', 'NOUN'),
 (30, 'Дзодзуашвили', 'PROPN'),
 (30, 'приходится', 'VERB'),
 (30, 'тетей', 'NOUN'),
 (30, 'жене', 'NOUN'),
 (30, 'Владимира', 'PROPN'),
 (30, 'Гуцаева', 'PROPN'),
 (30, '.', 'PUNCT'),
 (31, 'Был', 'AUX'),
 (31, 'полностью', 'ADV'),
 (31, 'перестроен', 'VERB'),
 (31, 'детский', 'ADJ'),
 (31, 'сад', 'NOUN'),
 (31, 'и', 'CCONJ'),
 (31, 'сельский', 'ADJ'),
 (31, 'клуб', 'NOUN'),
 (31, ',', 'PUNCT'),
 (31, 'в', 'ADP'),
 (31, 'котором', 'PRON'),
 (31, 'были', 'AUX'),
 (31, 'открыты', 'VERB'),
 (31, 'библиотека', 'NOUN'),
 (31, ',', 'PUNCT'),
 (31, 'концертный', 'ADJ'),
 (31, 'зал', 'NOUN'),
 (31, 'и', 'CCONJ'),
 (31, 'танцплощадка', 'NOUN'),
 (31, '.', 'PUNCT'),
 (32, 'Хирамацу', 'PROPN'),
 (32, 'Дзенки', 'PROPN'),
 (32, 'и', 'CCONJ'),
 (32, 'Яцумото', 'PROPN'),
 (32, 'Эйти', 'PROPN'),
 (32, 'призывают', 'VERB'),
 (32, 'в', 'ADP'),
 (32, 'армию', 'NOUN'),
 (32, '.', 'PUNCT'),
 (33, 'В', 'ADP'),
 (33, 'парке', 'NOUN'),
 (33, 'раньше', 'ADV'),
 (33, 'находилась', 'VERB'),
 (33, 'эстрада', 'NOUN'),
 (33, ',', 'PUNCT'),
 (33, 'снесена', 'VERB'),
 (33, 'и', 'CCONJ'),
 (33, 'позднее', 'ADV'),
 (33, 'на', 'ADP'),
 (33, 'её', 'DET'),
 (33, 'месте', 'NOUN'),
 (33, 'выстроен', 'VERB'),
 (33, 'в', 'ADP'),
 (33, '80-х', 'ADJ'),
 (33, 'годах', 'NOUN'),
 (33, 'новый', 'ADJ'),
 (33, 'мемориал', 'NOUN'),
 (33, 'павших', 'NOUN'),
 (33, 'при', 'ADP'),
 (33, 'освобождении', 'NOUN'),
 (33, 'города', 'NOUN'),
 (33, 'от', 'ADP'),
 (33, 'нацистов', 'NOUN'),
 (33, 'в', 'ADP'),
 (33, 'июле', 'NOUN'),
 (33, '1944', 'ADJ'),
 (33, 'года', 'NOUN'),
 (33, ',', 'PUNCT'),
 (33, 'открыт', 'VERB'),
 (33, 'в', 'ADP'),
 (33, '1984', 'ADJ'),
 (33, 'году', 'NOUN'),
 (33, '.', 'PUNCT'),
 (34, 'Многочисленные', 'ADJ'),
 (34, 'пародии', 'NOUN'),
 (34, 'еврейской', 'ADJ'),
 (34, 'речи', 'NOUN'),
 (34, 'появляются', 'VERB'),
 (34, 'и', 'PART'),
 (34, 'в', 'ADP'),
 (34, 'записи', 'NOUN'),
 (34, 'рождественских', 'ADJ'),
 (34, 'гимнов', 'NOUN'),
 (34, '.', 'PUNCT'),
 (35, 'Все', 'ADV'),
 (35, 'чаще', 'ADV'),
 (35, 'и', 'CCONJ'),
 (35, 'чаще', 'ADV'),
 (35, 'в', 'ADP'),
 (35, 'современной', 'ADJ'),
 (35, 'литературе', 'NOUN'),
 (35, 'слышатся', 'VERB'),
 (35, 'голоса', 'NOUN'),
 (35, 'в', 'ADP'),
 (35, 'пользу', 'NOUN'),
 (35, 'старой', 'ADJ'),
 (35, 'доктрины', 'NOUN'),
 (35, '.', 'PUNCT'),
 (36, 'В', 'ADP'),
 (36, 'этой', 'DET'),
 (36, 'трёхактной', 'ADJ'),
 (36, 'пьесе', 'NOUN'),
 (36, ',', 'PUNCT'),
 (36, 'сюжет', 'NOUN'),
 (36, 'которой', 'PRON'),
 (36, 'связан', 'VERB'),
 (36, 'с', 'ADP'),
 (36, 'трагическим', 'ADJ'),
 (36, 'финалом', 'NOUN'),
 (36, 'жизни', 'NOUN'),
 (36, 'египетской', 'ADJ'),
 (36, 'царицы', 'NOUN'),

In [3]:
data = pd.DataFrame(tagged_words, columns=['sentence', 'Word', 'POS'])
data

NameError: name 'tagged_words' is not defined

In [4]:
data = pd.read_csv("NER dataset.csv", encoding='latin1')
data = data.fillna(method="ffill")
data = data.rename(columns={'Sentence #': 'sentence'})
data.head(5)

C:\Users\Андрей\AppData\Local\Temp\ipykernel_10532\2134620346.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = data.fillna(method="ffill")

      sentence           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1  Sentence: 1             of   IN   O
2  Sentence: 1  demonstrators  NNS   O
3  Sentence: 1           have  VBP   O
4  Sentence: 1        marched  VBN   O

Get the numbers of tags & words inside the whole data. We'll need this in the future.

In [5]:
tags = list(set(data.POS.values)) #Read POS values
words = list(set(data.Word.values))
len(tags), len(words)

(42, 35177)

We cannot split data normally with `train_test_split` because doing that makes some parts of a sentence in the training set while some others in the testing set. Instead, we use `GroupShuffleSplit`.

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
y = data.POS
X = data.drop('POS', axis=1)

gs = GroupShuffleSplit(n_splits=2, test_size=.33, random_state=42)
train_ix, test_ix = next(gs.split(X, y, groups=data['sentence']))

data_train = data.loc[train_ix]
data_test = data.loc[test_ix]

data_train

                sentence       Word  POS Tag
24           Sentence: 2   Families  NNS   O
25           Sentence: 2         of   IN   O
26           Sentence: 2   soldiers  NNS   O
27           Sentence: 2     killed  VBN   O
28           Sentence: 2         in   IN   O
...                  ...        ...  ...  ..
1048570  Sentence: 47959       they  PRP   O
1048571  Sentence: 47959  responded  VBD   O
1048572  Sentence: 47959         to   TO   O
1048573  Sentence: 47959        the   DT   O
1048574  Sentence: 47959     attack   NN   O

[702936 rows x 4 columns]

After checking the data after splitted, it seems to be fine.
Check the numbers of tags & words in the training set.

In [8]:
tags = list(set(data_train.POS.values)) #Read POS values
words = list(set(data_train.Word.values))
len(tags), len(words)

(42, 29586)

The number of tags is enough but the number of words is not enough (~29k vs ~35k).
Because of that we need to randomly add some UNKNOWN words into the training dataset then we recalculate the word list and create map from them to number.

In [9]:
dfupdate = data_train.sample(frac=.15, replace=False, random_state=42)
dfupdate.Word = 'UNKNOWN'
data_train.update(dfupdate)
words = list(set(data_train.Word.values))
# Convert words and tags into numbers
word2id = {w: i for i, w in enumerate(words)}
tag2id = {t: i for i, t in enumerate(tags)}
id2tag = {i: t for i, t in enumerate(tags)}
len(tags), len(words)

(42, 27553)

Hidden Markov Models can be trained by using the Baum-Welch algorithm.
However input of the training is just dataset (Words).
We cannot map back the states to the POS tag.

That's why we have to calculate the model parameters for `hmmlearn.hmm.MultinomialHMM` manually by calculating
- `startprob_`
- `transmat_`
- `emissionprob_`

In [10]:
count_tags = dict(data_train.POS.value_counts())
count_tags_to_words = data_train.groupby(['POS']).apply(lambda grp: grp.groupby('Word')['POS'].count().to_dict()).to_dict()
count_init_tags = dict(data_train.groupby('sentence').first().POS.value_counts())

# TODO use panda solution
count_tags_to_next_tags = np.zeros((len(tags), len(tags)), dtype=int)
sentences = list(data_train.sentence)
pos = list(data_train.POS)
for i in range(len(sentences)) :
    if (i > 0) and (sentences[i] == sentences[i - 1]):
        prevtagid = tag2id[pos[i - 1]]
        nexttagid = tag2id[pos[i]]
        count_tags_to_next_tags[prevtagid][nexttagid] += 1

C:\Users\Андрей\AppData\Local\Temp\ipykernel_10532\278955984.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  count_tags_to_words = data_train.groupby(['POS']).apply(lambda grp: grp.groupby('Word')['POS'].count().to_dict()).to_dict()

In [11]:
mystartprob = np.zeros((len(tags),))
mytransmat = np.zeros((len(tags), len(tags)))
myemissionprob = np.zeros((len(tags), len(words)))
num_sentences = sum(count_init_tags.values())
sum_tags_to_next_tags = np.sum(count_tags_to_next_tags, axis=1)
for tag, tagid in tag2id.items():
    floatCountTag = float(count_tags.get(tag, 0))
    mystartprob[tagid] = count_init_tags.get(tag, 0) / num_sentences
    for word, wordid in word2id.items():
        myemissionprob[tagid][wordid]= count_tags_to_words.get(tag, {}).get(word, 0) / floatCountTag
    for tag2, tagid2 in tag2id.items():
        mytransmat[tagid][tagid2]= count_tags_to_next_tags[tagid][tagid2] / sum_tags_to_next_tags[tagid]

Initialize a HMM

In [12]:
model = hmm.CategoricalHMM(n_components=len(tags), algorithm='viterbi', random_state=42)
model.startprob_ = mystartprob
model.transmat_ = mytransmat
model.emissionprob_ = myemissionprob

As some words may never appear in the training set, we need to transform them into `UNKNOWN` first.
Then we split `data_test` into `samples` & `lengths` and send them to HMM.

In [25]:
data_test.loc[~data_test['Word'].isin(words), 'Word'] = 'UNKNOWN'
word_test = list(data_test.Word)
samples = []
for i, val in enumerate(word_test):
    samples.append([word2id[val]])
    
# TODO use panda solution
lengths = []
count = 0
sentences = list(data_test.sentence)
for i in range(len(sentences)) :
    if (i > 0) and (sentences[i] == sentences[i - 1]):
        count += 1
    elif i > 0:
        lengths.append(count)
        count = 1
    else:
        count = 1

In [26]:
help(model.predict)

Help on method predict in module hmmlearn.base:

predict(X, lengths=None) method of hmmlearn.hmm.CategoricalHMM instance
    Find most likely state sequence corresponding to ``X``.

    Parameters
    ----------
    X : array-like, shape (n_samples, 1)
        Feature matrix of individual samples.
    lengths : array-like of integers, shape (n_sequences, ), optional
        Lengths of the individual sequences in ``X``. The sum of
        these should be ``n_samples``.

    Returns
    -------
    state_sequence : array, shape (n_samples, )
        Labels for each sample from ``X``.

    Notes
    -----
    Unlike other HMM classes, `CategoricalHMM` ``X`` arrays have shape
    ``(n_samples, 1)`` (instead of ``(n_samples, n_features)``).  Consider using
    `sklearn.preprocessing.LabelEncoder` to transform your input to the right
    format.

In [27]:
# This code is very slow
pos_predict = model.predict(samples, lengths)
pos_predict

ValueError: lengths array [24, 21, 28, 25, 26, 22, 34, 23, 19, 25, 22, 35, 30, 24, 26, 39, 31, 7, 34, 8, 26, 32, 14, 30, 24, 11, 17, 29, 27, 7, 32, 25, 18, 18, 12, 28, 32, 22, 21, 26, 13, 25, 33, 20, 9, 27, 36, 40, 18, 24, 11, 17, 11, 26, 14, 20, 28, 21, 41, 25, 35, 18, 21, 30, 20, 17, 18, 27, 24, 25, 26, 17, 22, 14, 22, 27, 26, 24, 21, 30, 10, 14, 32, 30, 22, 17, 16, 23, 17, 29, 23, 16, 18, 22, 23, 25, 17, 24, 29, 15, 16, 46, 14, 27, 23, 24, 22, 20, 19, 7, 12, 21, 19, 19, 40, 13, 14, 26, 18, 27, 11, 31, 33, 21, 23, 9, 19, 20, 38, 26, 23, 18, 24, 26, 21, 17, 18, 24, 26, 24, 24, 37, 34, 15, 15, 17, 19, 25, 17, 9, 41, 24, 22, 18, 12, 37, 27, 12, 21, 29, 16, 24, 29, 23, 20, 33, 17, 17, 11, 19, 43, 31, 21, 42, 13, 31, 27, 35, 31, 13, 14, 38, 26, 24, 22, 32, 29, 62, 12, 9, 30, 15, 31, 28, 29, 13, 19, 13, 12, 12, 16, 27, 23, 32, 20, 10, 23, 27, 34, 15, 13, 19, 21, 11, 26, 28, 36, 14, 15, 18, 6, 30, 9, 18, 24, 32, 29, 25, 23, 22, 21, 20, 15, 26, 17, 29, 21, 20, 30, 18, 22, 21, 25, 38, 17, 11, 34, 27, 37, 13, 26, 26, 25, 25, 36, 19, 19, 20, 23, 23, 11, 27, 15, 29, 37, 26, 13, 23, 14, 18, 12, 16, 19, 20, 10, 18, 6, 14, 28, 37, 16, 25, 15, 21, 25, 24, 28, 29, 11, 13, 33, 24, 21, 38, 28, 22, 23, 15, 23, 20, 13, 28, 36, 16, 32, 27, 10, 11, 13, 35, 22, 17, 15, 35, 25, 26, 17, 18, 24, 12, 22, 23, 26, 43, 26, 22, 26, 21, 36, 26, 17, 15, 23, 32, 30, 22, 29, 24, 27, 18, 17, 10, 21, 25, 31, 17, 31, 19, 22, 27, 21, 21, 24, 20, 21, 10, 24, 20, 28, 15, 34, 21, 22, 6, 23, 40, 10, 19, 16, 17, 14, 38, 33, 27, 34, 16, 14, 13, 37, 15, 10, 20, 14, 28, 20, 10, 27, 29, 20, 22, 23, 25, 19, 13, 25, 14, 5, 28, 19, 20, 23, 29, 16, 32, 15, 49, 48, 17, 34, 27, 34, 21, 25, 25, 24, 24, 20, 24, 34, 9, 17, 26, 30, 25, 33, 30, 11, 19, 22, 13, 44, 29, 14, 6, 20, 25, 27, 25, 22, 15, 23, 21, 30, 23, 16, 21, 13, 8, 8, 28, 24, 39, 10, 43, 13, 28, 24, 10, 26, 26, 19, 24, 25, 38, 23, 25, 16, 20, 26, 29, 14, 15, 21, 23, 34, 28, 19, 8, 26, 21, 18, 26, 25, 25, 27, 19, 18, 20, 22, 24, 27, 27, 35, 8, 27, 17, 32, 11, 15, 34, 17, 21, 17, 24, 27, 23, 20, 19, 30, 31, 24, 23, 18, 22, 20, 14, 21, 11, 2, 35, 26, 14, 23, 19, 21, 13, 21, 29, 32, 24, 20, 11, 22, 12, 24, 14, 23, 16, 19, 11, 18, 24, 16, 21, 11, 27, 14, 25, 17, 16, 12, 22, 24, 28, 20, 19, 22, 13, 22, 19, 17, 17, 24, 11, 28, 17, 29, 32, 7, 15, 22, 14, 26, 28, 18, 27, 29, 14, 18, 22, 19, 27, 39, 23, 18, 27, 36, 23, 23, 35, 10, 29, 17, 9, 16, 9, 37, 18, 40, 20, 29, 18, 20, 28, 17, 21, 23, 18, 20, 31, 9, 30, 26, 21, 19, 25, 14, 9, 18, 15, 25, 31, 18, 11, 38, 25, 24, 21, 35, 34, 29, 12, 19, 14, 22, 20, 6, 25, 25, 25, 16, 13, 13, 17, 21, 18, 21, 21, 21, 28, 30, 15, 32, 15, 22, 18, 15, 31, 15, 30, 29, 18, 13, 24, 6, 22, 29, 15, 14, 25, 19, 20, 19, 24, 21, 27, 24, 8, 27, 16, 9, 14, 32, 7, 23, 18, 10, 22, 12, 12, 32, 13, 7, 24, 17, 26, 10, 14, 10, 30, 18, 9, 13, 14, 20, 24, 33, 22, 8, 24, 41, 22, 25, 32, 20, 33, 26, 26, 18, 32, 27, 26, 11, 21, 17, 23, 7, 14, 27, 21, 36, 13, 24, 33, 25, 25, 29, 10, 22, 31, 11, 9, 23, 15, 37, 19, 25, 30, 22, 17, 18, 40, 23, 26, 23, 24, 33, 28, 20, 21, 30, 15, 25, 31, 16, 34, 25, 16, 16, 23, 16, 32, 35, 23, 29, 22, 13, 16, 30, 10, 18, 22, 30, 24, 29, 14, 19, 16, 29, 19, 24, 18, 34, 33, 22, 25, 19, 19, 22, 17, 20, 12, 21, 15, 33, 17, 27, 32, 44, 28, 9, 25, 24, 9, 21, 18, 21, 25, 18, 20, 28, 20, 22, 21, 32, 6, 24, 27, 18, 16, 20, 17, 24, 13, 22, 18, 19, 21, 16, 22, 4, 18, 15, 26, 28, 23, 24, 21, 22, 23, 24, 17, 6, 27, 11, 9, 21, 25, 70, 13, 25, 22, 28, 28, 31, 30, 18, 26, 15, 19, 26, 24, 6, 25, 30, 22, 38, 15, 10, 16, 29, 35, 20, 15, 24, 29, 20, 16, 34, 17, 25, 25, 24, 21, 21, 14, 20, 25, 27, 29, 25, 36, 23, 19, 19, 19, 24, 23, 35, 19, 8, 18, 36, 11, 19, 10, 11, 29, 15, 19, 26, 27, 15, 22, 22, 30, 15, 18, 11, 21, 18, 29, 14, 13, 29, 23, 15, 25, 20, 18, 16, 27, 16, 20, 17, 16, 22, 20, 20, 22, 16, 21, 14, 20, 28, 17, 38, 12, 20, 8, 32, 6, 30, 22, 22, 15, 26, 31, 19, 31, 28, 27, 29, 17, 26, 16, 22, 31, 22, 22, 30, 32, 12, 23, 27, 30, 22, 23, 20, 30, 19, 19, 10, 29, 23, 37, 21, 22, 28, 7, 13, 12, 31, 17, 11, 19, 8, 9, 26, 20, 12, 16, 13, 13, 20, 30, 20, 15, 16, 13, 21, 22, 20, 17, 16, 24, 5, 13, 9, 22, 17, 14, 16, 25, 30, 12, 23, 21, 27, 10, 5, 23, 20, 8, 29, 25, 20, 29, 19, 22, 20, 15, 7, 8, 18, 10, 24, 23, 30, 38, 32, 26, 9, 26, 31, 14, 32, 21, 24, 22, 22, 26, 10, 31, 24, 14, 15, 35, 16, 20, 27, 20, 21, 11, 28, 25, 30, 29, 26, 37, 21, 24, 11, 13, 13, 19, 18, 28, 20, 44, 16, 21, 22, 23, 32, 20, 28, 14, 16, 21, 9, 20, 19, 28, 9, 13, 31, 19, 31, 25, 25, 23, 40, 26, 18, 25, 25, 15, 23, 22, 10, 20, 27, 17, 21, 7, 27, 27, 21, 22, 29, 30, 24, 25, 10, 14, 27, 25, 14, 19, 19, 41, 32, 29, 26, 24, 31, 21, 22, 19, 35, 22, 22, 16, 18, 27, 30, 11, 15, 15, 30, 12, 26, 23, 13, 18, 21, 30, 14, 14, 25, 19, 15, 29, 15, 15, 11, 12, 15, 21, 24, 14, 21, 12, 11, 27, 25, 34, 31, 22, 25, 38, 24, 10, 25, 21, 9, 8, 28, 20, 32, 28, 9, 13, 15, 22, 25, 7, 10, 22, 24, 13, 33, 28, 16, 24, 20, 23, 21, 21, 23, 35, 9, 18, 20, 23, 8, 18, 16, 26, 24, 20, 9, 35, 32, 28, 26, 26, 14, 25, 20, 28, 35, 31, 28, 21, 20, 11, 29, 29, 21, 35, 19, 19, 23, 23, 14, 25, 27, 11, 10, 17, 17, 29, 24, 26, 33, 23, 26, 23, 17, 35, 20, 18, 31, 13, 27, 32, 28, 21, 25, 20, 16, 34, 14, 26, 24, 30, 30, 28, 21, 24, 11, 14, 21, 32, 36, 26, 24, 26, 23, 23, 18, 24, 11, 24, 24, 24, 28, 33, 21, 38, 21, 33, 29, 36, 26, 15, 19, 15, 31, 19, 17, 15, 15, 23, 8, 25, 20, 22, 29, 19, 20, 16, 12, 13, 24, 13, 21, 17, 20, 28, 17, 30, 17, 27, 38, 23, 14, 24, 24, 24, 24, 17, 17, 15, 20, 36, 25, 21, 9, 27, 26, 27, 24, 35, 13, 20, 19, 18, 15, 29, 17, 18, 16, 32, 16, 27, 34, 12, 29, 31, 17, 27, 17, 15, 17, 26, 21, 14, 20, 21, 27, 26, 19, 21, 42, 17, 21, 26, 7, 13, 31, 26, 15, 32, 15, 25, 27, 38, 20, 14, 14, 27, 27, 30, 32, 25, 18, 32, 31, 18, 24, 23, 14, 7, 21, 22, 27, 21, 14, 19, 26, 15, 21, 20, 29, 39, 15, 24, 33, 14, 36, 24, 12, 28, 32, 33, 17, 29, 30, 19, 13, 29, 15, 16, 31, 23, 21, 20, 17, 25, 30, 23, 33, 25, 19, 19, 14, 23, 18, 21, 14, 18, 14, 37, 17, 18, 26, 14, 8, 30, 27, 25, 34, 14, 24, 36, 19, 21, 26, 14, 30, 21, 17, 26, 18, 12, 22, 20, 22, 24, 36, 22, 16, 37, 19, 24, 20, 15, 28, 21, 8, 24, 29, 53, 29, 28, 26, 16, 26, 19, 13, 21, 10, 27, 19, 24, 33, 25, 24, 10, 19, 27, 27, 19, 29, 18, 6, 18, 30, 19, 25, 23, 6, 23, 14, 21, 14, 28, 18, 13, 21, 20, 26, 34, 16, 19, 22, 28, 24, 23, 27, 24, 18, 29, 11, 21, 18, 20, 21, 20, 36, 35, 11, 26, 24, 11, 9, 21, 27, 29, 23, 24, 30, 20, 16, 7, 30, 19, 18, 28, 13, 22, 19, 15, 24, 28, 15, 7, 30, 25, 30, 21, 14, 20, 15, 24, 20, 12, 21, 24, 36, 12, 25, 20, 27, 23, 20, 28, 20, 27, 22, 13, 15, 36, 10, 13, 21, 17, 18, 20, 19, 17, 11, 19, 14, 24, 23, 36, 21, 6, 31, 22, 14, 31, 26, 27, 22, 26, 23, 27, 23, 32, 23, 28, 34, 36, 32, 29, 24, 31, 9, 15, 18, 25, 21, 17, 25, 20, 5, 26, 6, 26, 36, 18, 11, 20, 14, 26, 10, 24, 25, 21, 22, 19, 33, 23, 29, 25, 22, 28, 29, 15, 10, 23, 20, 15, 29, 27, 32, 22, 18, 24, 6, 26, 17, 15, 24, 25, 17, 32, 24, 21, 13, 15, 30, 12, 11, 23, 19, 26, 21, 12, 8, 29, 30, 18, 17, 17, 17, 20, 43, 18, 25, 25, 19, 18, 31, 31, 12, 25, 29, 18, 34, 27, 23, 25, 24, 17, 14, 18, 22, 31, 33, 11, 27, 31, 27, 27, 5, 15, 28, 17, 24, 20, 23, 22, 16, 19, 15, 15, 18, 19, 33, 35, 28, 25, 20, 33, 18, 23, 16, 19, 12, 21, 20, 24, 30, 7, 29, 28, 20, 19, 18, 19, 23, 22, 13, 25, 26, 16, 24, 22, 16, 8, 26, 32, 17, 28, 30, 28, 20, 24, 35, 8, 21, 34, 16, 27, 22, 25, 12, 29, 26, 18, 31, 30, 16, 11, 37, 31, 39, 20, 16, 23, 30, 38, 19, 24, 20, 20, 25, 15, 7, 29, 19, 20, 20, 11, 19, 26, 16, 34, 29, 14, 31, 27, 24, 15, 18, 17, 6, 31, 34, 15, 13, 18, 16, 15, 9, 6, 29, 17, 13, 27, 12, 18, 15, 21, 14, 13, 33, 50, 22, 24, 29, 19, 13, 9, 26, 28, 25, 13, 23, 18, 40, 24, 20, 12, 23, 23, 23, 19, 16, 16, 19, 25, 16, 23, 9, 17, 29, 12, 26, 28, 21, 15, 16, 20, 27, 27, 28, 24, 27, 25, 32, 25, 26, 14, 34, 17, 21, 26, 11, 22, 25, 11, 12, 18, 18, 11, 11, 31, 14, 15, 21, 10, 30, 14, 15, 24, 33, 29, 20, 17, 12, 16, 33, 10, 20, 19, 16, 19, 37, 25, 18, 16, 23, 19, 33, 32, 23, 18, 20, 30, 16, 7, 21, 14, 30, 22, 18, 20, 10, 23, 11, 39, 9, 29, 36, 14, 11, 22, 19, 22, 18, 17, 44, 14, 22, 15, 13, 19, 34, 19, 24, 12, 20, 20, 17, 29, 27, 31, 16, 20, 17, 15, 23, 13, 11, 34, 13, 33, 23, 23, 14, 23, 28, 15, 19, 21, 25, 31, 29, 16, 34, 21, 21, 15, 14, 13, 23, 18, 18, 13, 16, 23, 34, 8, 31, 14, 18, 17, 26, 24, 35, 19, 24, 24, 25, 29, 30, 24, 16, 28, 9, 28, 39, 31, 23, 12, 12, 20, 31, 13, 25, 12, 11, 28, 30, 19, 14, 23, 32, 32, 16, 33, 15, 35, 26, 21, 19, 15, 21, 31, 28, 31, 22, 17, 24, 23, 22, 14, 37, 11, 20, 21, 22, 28, 12, 9, 37, 18, 15, 22, 15, 20, 28, 21, 17, 20, 21, 22, 15, 18, 9, 18, 30, 18, 26, 42, 37, 13, 25, 43, 32, 29, 31, 25, 17, 23, 30, 25, 18, 27, 19, 31, 22, 18, 9, 26, 37, 24, 24, 25, 15, 26, 32, 28, 18, 24, 20, 15, 27, 27, 18, 22, 32, 18, 21, 14, 24, 36, 30, 18, 31, 36, 30, 28, 40, 12, 14, 19, 20, 16, 29, 18, 23, 14, 16, 26, 20, 6, 12, 24, 12, 17, 27, 13, 20, 26, 31, 11, 19, 51, 29, 34, 24, 18, 16, 11, 29, 28, 9, 10, 11, 7, 14, 24, 22, 25, 11, 20, 22, 27, 16, 33, 24, 16, 25, 18, 23, 29, 20, 22, 23, 38, 24, 18, 21, 10, 8, 19, 4, 41, 15, 17, 17, 33, 26, 28, 32, 12, 26, 18, 14, 38, 17, 24, 28, 14, 28, 38, 13, 24, 23, 27, 33, 18, 34, 32, 30, 28, 15, 22, 29, 6, 14, 15, 28, 20, 29, 24, 25, 15, 11, 31, 33, 21, 34, 20, 13, 42, 30, 18, 23, 34, 37, 22, 11, 23, 17, 19, 25, 21, 25, 23, 32, 29, 15, 33, 17, 22, 30, 22, 22, 20, 18, 17, 23, 11, 28, 9, 30, 25, 43, 11, 26, 18, 15, 17, 26, 11, 17, 19, 21, 18, 20, 25, 26, 24, 23, 26, 15, 27, 34, 13, 32, 29, 17, 29, 15, 48, 12, 34, 27, 28, 35, 39, 33, 28, 13, 25, 31, 19, 18, 38, 33, 34, 28, 23, 9, 24, 28, 13, 30, 16, 16, 18, 15, 25, 24, 23, 12, 30, 25, 18, 25, 29, 23, 31, 33, 15, 21, 12, 14, 17, 14, 11, 14, 24, 12, 21, 20, 22, 30, 18, 25, 11, 30, 20, 20, 16, 15, 20, 21, 16, 25, 22, 12, 18, 21, 14, 23, 34, 14, 25, 20, 11, 15, 15, 26, 17, 16, 32, 22, 12, 15, 24, 18, 10, 24, 32, 16, 22, 17, 9, 36, 13, 36, 17, 18, 24, 18, 10, 31, 9, 25, 19, 18, 17, 17, 12, 11, 16, 17, 18, 20, 17, 12, 12, 8, 12, 22, 12, 20, 15, 12, 10, 16, 41, 35, 18, 29, 16, 26, 16, 15, 18, 13, 10, 11, 18, 19, 16, 14, 24, 19, 23, 19, 34, 37, 16, 21, 23, 14, 29, 13, 18, 18, 20, 14, 18, 24, 24, 9, 11, 23, 18, 23, 14, 22, 12, 28, 12, 27, 10, 32, 26, 11, 23, 23, 27, 19, 16, 42, 17, 19, 24, 16, 24, 19, 28, 22, 11, 13, 12, 28, 18, 24, 29, 10, 46, 34, 38, 21, 31, 22, 25, 12, 8, 13, 12, 26, 26, 20, 19, 21, 21, 20, 27, 13, 21, 38, 24, 34, 29, 28, 22, 12, 19, 15, 11, 23, 18, 6, 27, 15, 35, 25, 9, 8, 8, 12, 32, 19, 15, 40, 16, 19, 24, 28, 18, 35, 27, 27, 19, 19, 29, 8, 23, 16, 26, 25, 26, 8, 31, 15, 39, 23, 23, 21, 13, 15, 29, 12, 27, 28, 30, 19, 33, 35, 10, 32, 29, 32, 20, 20, 26, 14, 10, 21, 17, 28, 18, 7, 14, 25, 9, 8, 10, 15, 27, 13, 13, 17, 25, 28, 25, 26, 16, 31, 34, 17, 27, 16, 18, 19, 29, 19, 15, 16, 24, 9, 19, 25, 18, 19, 13, 31, 8, 25, 22, 20, 17, 16, 38, 22, 19, 31, 18, 17, 15, 20, 12, 12, 29, 19, 28, 17, 15, 15, 22, 23, 5, 27, 11, 20, 21, 6, 26, 21, 8, 25, 17, 15, 24, 21, 7, 17, 28, 36, 22, 35, 33, 26, 22, 19, 34, 16, 8, 18, 14, 32, 32, 18, 20, 22, 16, 20, 36, 9, 22, 26, 21, 26, 22, 25, 25, 24, 24, 23, 20, 22, 21, 18, 24, 27, 28, 20, 11, 22, 15, 11, 14, 9, 31, 23, 19, 23, 19, 14, 32, 34, 17, 15, 18, 18, 19, 18, 24, 22, 24, 21, 34, 33, 25, 17, 21, 12, 35, 27, 32, 22, 14, 30, 15, 20, 34, 46, 42, 20, 38, 15, 31, 8, 24, 26, 26, 24, 11, 23, 36, 9, 19, 18, 14, 30, 25, 16, 19, 22, 18, 33, 21, 10, 25, 20, 21, 26, 24, 22, 16, 14, 15, 18, 45, 21, 9, 28, 23, 29, 20, 21, 12, 11, 16, 25, 16, 11, 15, 32, 12, 16, 25, 8, 16, 26, 25, 25, 23, 11, 26, 30, 19, 23, 21, 20, 10, 18, 12, 16, 26, 17, 29, 25, 13, 41, 26, 31, 23, 27, 15, 27, 23, 29, 19, 27, 15, 6, 23, 24, 26, 19, 24, 10, 19, 26, 29, 30, 13, 11, 11, 21, 22, 18, 36, 14, 10, 22, 22, 16, 24, 19, 16, 33, 21, 22, 27, 26, 17, 41, 12, 28, 31, 18, 23, 36, 25, 15, 24, 18, 34, 26, 22, 36, 13, 25, 23, 32, 33, 15, 15, 23, 22, 28, 20, 17, 19, 23, 22, 14, 14, 23, 7, 40, 30, 22, 16, 35, 33, 24, 24, 34, 30, 36, 8, 22, 24, 25, 28, 24, 26, 25, 17, 35, 23, 19, 25, 12, 19, 19, 22, 22, 16, 30, 23, 37, 35, 27, 16, 21, 12, 32, 17, 39, 34, 21, 17, 30, 19, 10, 29, 23, 26, 21, 17, 13, 21, 7, 9, 13, 16, 13, 21, 38, 20, 28, 15, 34, 17, 6, 24, 12, 31, 29, 30, 27, 19, 16, 29, 38, 29, 15, 30, 23, 28, 19, 23, 15, 41, 11, 33, 24, 25, 26, 27, 20, 36, 13, 8, 10, 10, 15, 9, 24, 13, 35, 24, 28, 18, 17, 7, 15, 12, 18, 21, 28, 9, 25, 7, 24, 20, 20, 30, 26, 33, 34, 31, 24, 11, 21, 35, 7, 23, 13, 28, 19, 18, 10, 11, 26, 9, 12, 31, 17, 15, 11, 32, 21, 28, 26, 40, 30, 26, 17, 21, 23, 8, 19, 20, 16, 19, 10, 30, 26, 29, 19, 12, 23, 9, 22, 25, 14, 20, 20, 21, 14, 26, 22, 25, 25, 24, 23, 13, 18, 31, 20, 9, 23, 19, 22, 13, 23, 17, 16, 29, 23, 28, 11, 25, 29, 26, 8, 18, 26, 20, 15, 21, 21, 33, 41, 36, 28, 26, 31, 25, 22, 21, 32, 24, 12, 22, 17, 16, 22, 20, 20, 23, 12, 22, 25, 18, 25, 21, 19, 24, 18, 25, 10, 21, 31, 10, 14, 10, 22, 18, 14, 27, 22, 29, 18, 13, 17, 14, 31, 15, 17, 17, 25, 18, 10, 25, 20, 22, 29, 13, 23, 15, 20, 21, 21, 24, 22, 50, 18, 27, 29, 20, 13, 21, 36, 20, 35, 20, 22, 26, 29, 19, 13, 18, 16, 24, 14, 10, 29, 31, 15, 16, 18, 25, 28, 28, 31, 25, 21, 25, 25, 31, 18, 20, 25, 17, 15, 21, 20, 27, 27, 27, 20, 15, 19, 25, 18, 16, 23, 40, 13, 13, 39, 26, 21, 7, 16, 16, 14, 10, 24, 31, 19, 13, 9, 32, 20, 15, 28, 25, 17, 35, 23, 18, 27, 47, 29, 17, 18, 20, 22, 29, 32, 41, 25, 35, 22, 7, 25, 35, 29, 26, 20, 22, 23, 13, 21, 35, 39, 19, 14, 54, 22, 25, 21, 24, 29, 12, 16, 18, 8, 20, 17, 34, 18, 27, 28, 41, 15, 13, 21, 21, 9, 16, 34, 31, 17, 25, 16, 33, 16, 10, 7, 14, 40, 7, 10, 39, 54, 27, 32, 19, 18, 21, 28, 33, 18, 23, 20, 9, 29, 27, 33, 20, 34, 19, 9, 21, 23, 21, 17, 27, 22, 14, 16, 22, 4, 25, 40, 20, 24, 15, 16, 18, 28, 23, 13, 18, 8, 24, 32, 16, 15, 16, 16, 21, 11, 20, 23, 31, 20, 11, 29, 23, 22, 20, 24, 30, 26, 17, 21, 24, 17, 9, 22, 21, 24, 36, 16, 18, 6, 31, 19, 7, 34, 30, 23, 38, 23, 21, 20, 27, 28, 29, 32, 24, 11, 11, 24, 10, 17, 24, 15, 10, 39, 33, 31, 15, 24, 23, 15, 27, 11, 18, 20, 19, 24, 20, 17, 14, 18, 9, 15, 12, 25, 13, 15, 27, 26, 17, 16, 24, 21, 17, 14, 23, 18, 17, 25, 24, 27, 29, 27, 43, 26, 29, 23, 28, 10, 9, 25, 23, 12, 31, 30, 25, 19, 23, 16, 24, 16, 29, 24, 25, 22, 34, 9, 24, 23, 37, 37, 23, 18, 22, 14, 15, 22, 35, 9, 37, 10, 22, 27, 27, 20, 33, 20, 24, 20, 20, 10, 28, 19, 19, 24, 28, 22, 24, 25, 23, 27, 9, 29, 27, 18, 27, 23, 14, 24, 30, 11, 24, 12, 19, 17, 14, 25, 23, 39, 30, 9, 17, 26, 13, 7, 28, 15, 20, 17, 19, 15, 18, 28, 23, 35, 10, 24, 25, 21, 21, 20, 18, 14, 20, 31, 25, 38, 20, 18, 18, 23, 32, 17, 13, 19, 22, 18, 27, 25, 31, 13, 10, 22, 34, 14, 14, 32, 10, 31, 25, 28, 15, 29, 17, 12, 20, 24, 15, 18, 20, 22, 24, 25, 30, 25, 20, 13, 27, 21, 23, 39, 32, 19, 30, 24, 16, 14, 10, 21, 21, 16, 23, 22, 21, 28, 21, 22, 33, 13, 30, 28, 18, 19, 28, 21, 26, 21, 9, 23, 7, 24, 23, 20, 25, 13, 8, 19, 20, 26, 19, 14, 27, 33, 21, 26, 23, 7, 25, 11, 26, 13, 22, 34, 12, 26, 24, 13, 13, 13, 33, 14, 29, 24, 6, 31, 25, 20, 30, 22, 18, 16, 16, 22, 25, 23, 25, 24, 21, 11, 20, 12, 12, 19, 27, 20, 21, 24, 20, 29, 16, 17, 20, 35, 19, 27, 18, 15, 25, 22, 27, 10, 19, 46, 19, 49, 48, 9, 33, 37, 24, 33, 12, 40, 21, 39, 29, 31, 14, 56, 31, 44, 25, 20, 23, 12, 23, 25, 19, 7, 14, 22, 25, 37, 23, 14, 32, 38, 27, 16, 12, 16, 15, 8, 28, 18, 22, 37, 36, 25, 18, 19, 23, 23, 20, 23, 25, 14, 32, 15, 39, 9, 18, 25, 29, 33, 21, 29, 14, 25, 28, 26, 18, 17, 29, 24, 27, 21, 22, 24, 24, 31, 39, 32, 27, 26, 14, 16, 33, 20, 19, 35, 23, 26, 28, 44, 30, 26, 18, 22, 23, 13, 19, 25, 11, 13, 24, 18, 28, 22, 5, 18, 15, 25, 28, 19, 24, 18, 22, 23, 17, 30, 15, 23, 19, 14, 12, 32, 22, 20, 34, 39, 21, 12, 34, 11, 14, 29, 30, 14, 44, 20, 19, 9, 35, 24, 30, 22, 22, 19, 17, 30, 33, 29, 15, 23, 35, 23, 25, 22, 36, 11, 7, 10, 20, 34, 20, 19, 11, 16, 35, 28, 20, 21, 8, 17, 30, 19, 23, 26, 34, 9, 24, 23, 22, 24, 24, 27, 9, 25, 44, 20, 14, 25, 32, 7, 23, 18, 24, 21, 21, 19, 26, 27, 31, 21, 20, 21, 30, 22, 17, 35, 22, 17, 17, 21, 17, 24, 25, 13, 28, 15, 27, 38, 17, 30, 26, 12, 21, 31, 29, 18, 14, 27, 18, 24, 23, 21, 27, 39, 12, 19, 11, 19, 12, 10, 22, 26, 25, 30, 49, 25, 39, 24, 24, 15, 12, 19, 45, 8, 15, 15, 11, 13, 6, 27, 19, 22, 22, 26, 8, 25, 14, 23, 14, 29, 27, 31, 35, 38, 13, 17, 35, 20, 18, 28, 18, 21, 11, 32, 35, 22, 26, 17, 27, 11, 28, 22, 19, 24, 9, 20, 18, 23, 11, 34, 19, 26, 21, 26, 18, 15, 25, 18, 29, 27, 16, 13, 12, 24, 33, 25, 27, 32, 15, 25, 17, 15, 19, 27, 19, 20, 34, 29, 24, 28, 20, 20, 16, 35, 22, 34, 30, 12, 10, 28, 25, 7, 12, 19, 29, 22, 14, 10, 21, 10, 17, 22, 21, 18, 16, 9, 15, 27, 20, 30, 33, 9, 34, 20, 24, 21, 6, 13, 27, 18, 22, 40, 24, 35, 19, 31, 9, 13, 24, 13, 20, 28, 18, 35, 20, 26, 17, 19, 25, 44, 35, 21, 26, 22, 29, 13, 8, 29, 16, 13, 19, 24, 26, 29, 15, 32, 23, 32, 20, 24, 14, 29, 15, 28, 17, 30, 21, 30, 11, 19, 29, 24, 21, 20, 26, 19, 27, 18, 28, 6, 6, 22, 29, 33, 16, 23, 9, 11, 16, 36, 20, 22, 27, 17, 29, 25, 32, 27, 19, 15, 29, 27, 32, 22, 26, 14, 11, 14, 11, 30, 41, 24, 33, 25, 27, 26, 16, 17, 48, 41, 20, 17, 20, 18, 19, 31, 21, 9, 34, 33, 11, 21, 29, 19, 32, 28, 12, 26, 10, 17, 11, 22, 7, 21, 24, 20, 10, 24, 15, 18, 15, 26, 28, 23, 32, 29, 16, 26, 23, 20, 11, 16, 20, 21, 13, 23, 31, 39, 16, 19, 23, 16, 17, 13, 28, 27, 20, 17, 23, 14, 20, 24, 16, 20, 15, 21, 25, 31, 28, 30, 22, 11, 31, 20, 8, 13, 7, 24, 27, 16, 23, 27, 35, 13, 22, 22, 20, 27, 33, 28, 32, 15, 22, 27, 23, 21, 15, 22, 34, 17, 17, 19, 32, 35, 14, 20, 10, 18, 23, 16, 40, 23, 31, 10, 26, 16, 28, 36, 17, 40, 35, 15, 29, 20, 15, 25, 36, 25, 23, 14, 36, 12, 14, 39, 24, 25, 11, 23, 20, 33, 21, 13, 30, 29, 14, 18, 25, 30, 11, 13, 23, 16, 34, 11, 23, 26, 37, 45, 24, 15, 13, 35, 26, 23, 18, 25, 18, 14, 31, 23, 27, 11, 41, 14, 11, 22, 15, 40, 30, 8, 18, 15, 18, 27, 15, 18, 17, 7, 20, 5, 20, 27, 20, 20, 21, 14, 18, 25, 13, 18, 25, 12, 23, 14, 27, 14, 20, 20, 22, 32, 21, 28, 15, 28, 17, 17, 17, 13, 12, 13, 17, 19, 47, 25, 26, 13, 20, 23, 27, 20, 10, 25, 11, 31, 23, 18, 30, 22, 26, 23, 16, 11, 24, 7, 26, 28, 28, 19, 18, 29, 23, 27, 10, 26, 25, 19, 10, 36, 14, 27, 18, 26, 19, 31, 18, 29, 30, 18, 14, 15, 14, 20, 25, 11, 31, 22, 23, 19, 32, 31, 24, 23, 30, 22, 32, 19, 6, 9, 21, 28, 37, 32, 15, 12, 10, 26, 30, 18, 19, 24, 14, 21, 24, 13, 12, 17, 13, 47, 20, 25, 19, 19, 14, 28, 14, 15, 25, 11, 15, 23, 28, 16, 21, 19, 19, 26, 19, 24, 22, 17, 27, 18, 16, 10, 16, 21, 25, 20, 13, 13, 19, 27, 20, 25, 14, 24, 29, 12, 24, 29, 17, 16, 28, 12, 22, 25, 25, 28, 16, 11, 15, 14, 28, 31, 9, 21, 17, 22, 18, 11, 16, 24, 26, 33, 27, 28, 24, 14, 10, 30, 19, 15, 26, 24, 14, 13, 12, 16, 17, 27, 39, 7, 16, 35, 14, 29, 31, 23, 37, 25, 23, 35, 15, 24, 14, 12, 29, 8, 27, 16, 45, 25, 8, 25, 10, 8, 8, 4, 5, 6, 6, 8, 44, 21, 31, 25, 25, 23, 35, 20, 8, 13, 20, 23, 28, 24, 12, 23, 18, 21, 19, 18, 21, 18, 25, 18, 30, 16, 28, 29, 17, 11, 22, 19, 15, 19, 25, 19, 15, 27, 26, 32, 25, 22, 31, 23, 23, 31, 19, 17, 7, 13, 23, 31, 32, 27, 9, 24, 19, 15, 19, 47, 27, 25, 31, 20, 29, 15, 22, 11, 24, 36, 26, 27, 11, 24, 40, 34, 13, 19, 16, 38, 24, 21, 22, 21, 19, 18, 24, 33, 21, 22, 24, 18, 34, 14, 32, 28, 31, 21, 27, 32, 7, 21, 17, 24, 10, 23, 19, 23, 19, 22, 23, 25, 23, 27, 27, 30, 15, 10, 26, 9, 28, 13, 14, 19, 4, 13, 29, 13, 25, 19, 17, 18, 17, 12, 40, 20, 25, 26, 29, 15, 17, 14, 19, 35, 8, 20, 30, 16, 26, 29, 31, 25, 24, 10, 22, 25, 15, 26, 32, 22, 11, 21, 22, 30, 8, 29, 9, 22, 21, 14, 29, 19, 34, 24, 23, 24, 62, 48, 11, 29, 35, 17, 18, 24, 20, 33, 11, 18, 33, 14, 12, 32, 31, 12, 16, 14, 18, 15, 25, 26, 19, 18, 16, 34, 18, 26, 17, 14, 12, 22, 29, 22, 22, 19, 25, 24, 22, 15, 24, 15, 30, 33, 22, 25, 8, 15, 11, 15, 44, 26, 30, 23, 8, 12, 21, 23, 32, 26, 13, 25, 28, 28, 20, 14, 47, 27, 23, 16, 6, 17, 21, 19, 26, 13, 35, 26, 29, 27, 24, 38, 24, 24, 15, 34, 14, 22, 21, 24, 17, 30, 22, 17, 19, 11, 22, 29, 14, 23, 13, 20, 11, 9, 23, 31, 19, 16, 22, 29, 28, 28, 19, 30, 13, 23, 26, 20, 17, 35, 28, 16, 29, 26, 26, 10, 10, 25, 27, 23, 17, 28, 14, 19, 15, 19, 27, 24, 25, 41, 34, 32, 33, 17, 9, 29, 13, 11, 15, 27, 32, 27, 24, 19, 17, 30, 33, 24, 19, 15, 6, 23, 42, 10, 10, 27, 32, 32, 13, 18, 33, 19, 22, 27, 28, 19, 20, 14, 12, 18, 33, 31, 23, 28, 17, 30, 36, 26, 23, 17, 24, 25, 11, 18, 24, 16, 46, 16, 25, 21, 33, 45, 43, 29, 28, 18, 19, 26, 27, 11, 23, 10, 28, 6, 6, 20, 22, 29, 21, 16, 

In [17]:
tags_test = list(data_test.POS)
pos_test = np.zeros((len(tags_test), ), dtype=int)
for i, val in enumerate(tags_test):
    pos_test[i] = tag2id[val]
len(pos_predict), len(pos_test), len(samples), len(word_test)

NameError: name 'pos_predict' is not defined

Somehow the output of HMM is in wrong size. Only use the shorter length to check the result.

In [13]:
def reportTest(y_pred, y_test):
    print("The accuracy is {}".format(accuracy_score(y_test, y_pred))) 
    print("The precision is {}".format(precision_score(y_test, y_pred, average='weighted'))) 
    print("The recall is {}".format(recall_score(y_test, y_pred, average='weighted'))) 
    print("The F1-Score is {}".format(f1_score(y_test, y_pred, average='weighted')))

min_length = min(len(pos_predict), len(pos_test))

reportTest(pos_predict[:min_length], pos_test[:min_length])

The accuracy is 0.9656062381551727
The precision is 0.9657832270028688
The recall is 0.9656062381551727
The F1-Score is 0.9655716883723663