Импортируем библиотеки, собираем все данные

In [16]:
import os
import re
import pandas as pd

BASE_DIR = '/Users/sergey/PycharmProjects/SemAnalyzer/Keywords/Задание '
YEARS = [str(y) for y in range(2014, 2025)]

pattern = re.compile(r'^(.*?)_IMS_(\d{4})_rus\.txt$')

data = []

for root, dirs, files in os.walk(BASE_DIR):
    for file in files:
        if 'Abstract' in file or 'KW' in file:
            continue
        match = pattern.match(file)
        if match and match.group(2) in YEARS:
            file_path = os.path.join(root, file)
            with open(file_path, 'r', encoding='utf-8') as f:
                text = f.read()
            name = file  # имя файла целиком
            year = match.group(2)
            data.append({'name': name, 'text': text, 'year': year})

df = pd.DataFrame(data, columns=['name', 'text', 'year'])

df

,name,text,year
0,Kuzmina_IMS_2014_rus.txt,Социально-гуманитарная образовательная среда\n...,2014
1,Bogoraz_IMS_2014_rus.txt,Централизованные и распределенные социальные с...,2014
2,Grigoryeva_IMS_2014_rus.txt,Обучение пожилых ИКТ и возможности их\nтрудоус...,2014
3,Dyakova_IMS_2014_rus.txt,Использование информационных технологий\nдля б...,2014
4,Lizunova_IMS_2014_rus.txt,Безграничность медиапространства:\nбудущее или...,2014
...,...,...,...
137,Korablinov_IMS_2020_rus.txt,Подготовка набора данных для вопросно-ответног...,2020
138,Khokhlova_IMS_2020_rus.txt,Методы машинного обучения применительно к зада...,2020
139,Kuznetsova_IMS_2020_rus.txt,О возможности использования корпуса NOW в курс...,2020
140,Sokolova_IMS_2020_rus.txt,К вопросу о формировании набора отношений для ...,2020
141,Rogov_IMS_2020_rus.txt,Применение деревьев решений для анализа сильны...,2020

SUMY

In [18]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

/Users/sergey/PycharmProjects/SemAnalyzer/.venvNew/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[nltk_data] Downloading package punkt to /Users/sergey/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/sergey/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [19]:
summarizer = LexRankSummarizer()

In [20]:
abstracts = [] #список для 3 клбчевых предлложений после суммаризатора LexRank

In [22]:
for text in df.text:
  doc = text
  parser = PlaintextParser.from_string(doc, Tokenizer('russian'))
  summary = summarizer(parser.document, 3)
  abstracts.append([str(sentence) for sentence in summary])

In [23]:
abstracts[:10] #объединяем предложения

[['20,77% полагают, что развитие системы дистанционного обучения будет способствовать их профессиональному росту; 27,54% не считают, что система дистанционного обучения будет способствовать их профессиональному росту [1, C.177].',
  'Но в процессе реальной коммуникации, в том числе и осуществляемой в ходе образовательной деятельности, четкого разделения в знаниях на процедурную и декларативную составляющие не существует.',
  '«Взаимодействие в процессе обучения» подразумевает тот простой факт, что люди, осуществляя познавательную деятельность, вступают в разнообразные отношения между собой и с окружающей средой.'],
 ['Существует угрозы, которые не имеют прямого отношения к социальной сети, но могут иметь серьезные последствия, как для компьютера пользователя, так и для профиля пользователя в социальной сети.',
  'Пользователь целиком и полностью определяет доступ к своим данным для любого пользователя распределенной социальной сети.',
  'В обычных социальных сетях, сервер используется для абсолютно всех клиентских действий, таких как общение, хранение информации о других пользователях и прочее.'],
 ['В то же время, исследование ФОМ пказывает, что при ответе на вопрос «По достижении пенсионного возраста одни люди прекращают работать, уходят на пенсию, другие – продолжают работать.',
  'Преимуществами такой программы являются: посещение курсов абсолютно бесплатно, охват населения города, возможность сохранения профессии для пожилых людей [7].',
  'Но пока вопрос о мотивации и возможностях дальнейшего трудоустройства обучившихся, но уже не работающих, не ясен.'],
 ['Существует убеждение, что информационные технологии могут использоваться по всем основным направлениям борьбы с коррупцией: для ее предотвращения, пресечения последствий, а также для вовлечения общественности в борьбу с ней [21].',
  'При этом идеология борьбы с коррупцией, включая использование информационных технологий, полностью вписана в китайскую управленческую традицию.',
  'Использование информационных технологий направлено на повышение легитимности власти путем роста ее эффективности, с упором на «порядок, а не демократические идеалы, технократический контроль, а не гражданское участие (кроме низового), управляемость, а не тип режима» [26, с. 311] и рассчитано прежде всего на китайский средний класс.'],
 ['Медийное пространство – это пространство отношений всех медиасубъектов.',
  'Опираясь на концепцию П. Бурдье можно утверждать, что медиапространство как часть социального пространства проецирует формируемые в процессе взаимодействия медиаструктур по поводу производства и потребления медиаконтента, социальные конструкции на физическое пространство, а в мере взаимодействия медиа-агентов – социальные конструкции на иные подпространства или поля социального пространства.',
  'Она выделяет при этом три измерения медиапространства.'],
 ['Алгоритмы пополнения семантических классов Создание словарей для определенных семантических классов можно рассматривать как разновидность более общей задачи извлечения именованных сущностей.',
  'В рамках предварительного эксперимента мы опирались на работу [13], с отличиями в способе классификации (метод опорных векторов вместо сортировки по весу) и набором параметров (синтаксические связи вместо соседних имен существительных).',
  'Для каждого значения итерации была получена следующая таблица ля итеративного алгоритма для всех примененных объемов итерации N, а также для базового неитеративного алгоритма, были проанализированы1 следующие параметры: − сколько релевантных слов дополнил алгоритм при увеличении объема всех проверенных слов (Рисунок 1); − как меняется средняя релевантность алгоритма, выраженная через отношение всех полученных релевантных ко всем проверенным, при увеличении объема проверенных слов (Рисунок 2).'],
 ['Также было принято решение разделить термины-названия служебных морфем и лексем (тэг TGrMark) и термины падежной грамматики (тэг TCGr).',
  'Структура лексической базы Наполнение лексической базы тибетской грамматической терминологии составляют лексические единицы, отобранные из тибетской части корпуса по заданным тэгам, а именно по тэгам для маркировки терминов (лингвистических метаданных, см. Табл. 1).',
  'Структура базы Для упрощения перевода данных XML в базу и наоборот, структура данных и таблиц внутри базы данных соответствует структуре формата TEI.'],
 ['Если считать выделенные мерами ассоциации свободные сочетания слов отрицательным показателем эффективности, то с этой точки зрения наименее эффективными оказались меры MI (по 2 свободных сочетания из 10 словоформ и лемм) и minimum sensitivity (2 свободных сочетания для словоформ и 1 для лемм).',
  'Заключение и направления совершенствования программы В данной работе мы привели подробное описание использующихся на практике мер ассоциации ― статистических методов выявления сочетаемости слов в тексте, рассмотрели основные проблемы, возникающие при выявлении коллокаций, и попытались решить их при создании собственной программы поиска коллокаций в текстах на русском языке.',
  'Проблема выделения сочетаний со знаками препинания в нашей программе решена полностью, проблемы выделения сочетаний знаменательного слова со служебным и случайных сочетаний решены в той мере, в какой позволяет корректная работа библиотеки морфологического анализа.'],
 ['АИК «Прогноз СПб» предназначен для средне- и долгосрочного прогнозирования социальноэкономического развития Санкт-Петербурга и позволяет решать задачи класса «что будет, если...?» и «что надо, чтобы…?» на основе различных вариантов развития.',
  'Классы прогнозно-аналитических задач Совокупность прогнозно-аналитических задач, решаемых с помощью государственной информационной системы Санкт-Петербурга можно классифицировать следующим образом [4, 5]: − кратко- и среднесрочное прогнозирование социальноэкономических процессов; в том числе многовариантное прогнозирование; − выявление взаимного влияния факторов социально-экономического развития региона и построение модельных зависимостей; − стратегическое планирование, оценка реализации стратегий и приоритетных национальных и региональных программ; − оценка эффективности деятельности органов исполнительной власти; − аналитическая обработка и моделирование на основе данных социологических опросов.',
  'С использованием моделирующих комплексов, функционирующих в составе ИС ИАО, осуществляется долгосрочное прогнозирование индикаторов социально-экономического развития региона по различным сферам жизнедеятельности (на период до 20 лет) [7].'],
 ['На втором этапе используется квотная выборка.',
  'По данным исследования структура ценностных ориентаций молодежи и их ценностные стереотипы значительно различаются Результаты исследования показывают, что основным жизненным ориентиром молодежи России является семья – более половины участников опроса (56,1 %) назвали её самым важным в жизни.',
  'Следующими, по распространенности среди молодежи, по мнению респондентов, являются работа, бизнес, карьера (13,6 %), достижение целей, успех (13,4 %), патриотизм, наследие (13,4 %), семья, брак (12,4 %).']]

In [24]:
annotations = []
for abstr in enumerate(abstracts, start=1):
    print(f'Аннотация статьи {abstr[0]}:')
    annotation = str(' '.join(abstr[1]))
    annotations.append(annotation)
    print(annotation, '\n\n')

Аннотация статьи 1:
20,77% полагают, что развитие системы дистанционного обучения будет способствовать их профессиональному росту; 27,54% не считают, что система дистанционного обучения будет способствовать их профессиональному росту [1, C.177]. Но в процессе реальной коммуникации, в том числе и осуществляемой в ходе образовательной деятельности, четкого разделения в знаниях на процедурную и декларативную составляющие не существует. «Взаимодействие в процессе обучения» подразумевает тот простой факт, что люди, осуществляя познавательную деятельность, вступают в разнообразные отношения между собой и с окружающей средой.


Аннотация статьи 2:
Существует угрозы, которые не имеют прямого отношения к социальной сети, но могут иметь серьезные последствия, как для компьютера пользователя, так и для профиля пользователя в социальной сети. Пользователь целиком и полностью определяет доступ к своим данным для любого пользователя распределенной социальной сети. В обычных социальных сетях, сервер используется для абсолютно всех клиентских действий, таких как общение, хранение информации о других пользователях и прочее.


Аннотация статьи 3:
В то же время, исследование ФОМ пказывает, что при ответе на вопрос «По достижении пенсионного возраста одни люди прекращают работать, уходят на пенсию, другие – продолжают работать. Преимуществами такой программы являются: посещение курсов абсолютно бесплатно, охват населения города, возможность сохранения профессии для пожилых людей [7]. Но пока вопрос о мотивации и возможностях дальнейшего трудоустройства обучившихся, но уже не работающих, не ясен.


Аннотация статьи 4:
Существует убеждение, что информационные технологии могут использоваться по всем основным направлениям борьбы с коррупцией: для ее предотвращения, пресечения последствий, а также для вовлечения общественности в борьбу с ней [21]. При этом идеология борьбы с коррупцией, включая использование информационных технологий, полностью вписана в китайскую управленческую традицию. Использование информационных технологий направлено на повышение легитимности власти путем роста ее эффективности, с упором на «порядок, а не демократические идеалы, технократический контроль, а не гражданское участие (кроме низового), управляемость, а не тип режима» [26, с. 311] и рассчитано прежде всего на китайский средний класс.


Аннотация статьи 5:
Медийное пространство – это пространство отношений всех медиасубъектов. Опираясь на концепцию П. Бурдье можно утверждать, что медиапространство как часть социального пространства проецирует формируемые в процессе взаимодействия медиаструктур по поводу производства и потребления медиаконтента, социальные конструкции на физическое пространство, а в мере взаимодействия медиа-агентов – социальные конструкции на иные подпространства или поля социального пространства. Она выделяет при этом три измерения медиапространства.


Аннотация статьи 6:
Алгоритмы пополнения семантических классов Создание словарей для определенных семантических классов можно рассматривать как разновидность более общей задачи извлечения именованных сущностей. В рамках предварительного эксперимента мы опирались на работу [13], с отличиями в способе классификации (метод опорных векторов вместо сортировки по весу) и набором параметров (синтаксические связи вместо соседних имен существительных). Для каждого значения итерации была получена следующая таблица ля итеративного алгоритма для всех примененных объемов итерации N, а также для базового неитеративного алгоритма, были проанализированы1 следующие параметры: − сколько релевантных слов дополнил алгоритм при увеличении объема всех проверенных слов (Рисунок 1); − как меняется средняя релевантность алгоритма, выраженная через отношение всех полученных релевантных ко всем проверенным, при увеличении объема проверенных слов (Рисунок 2).


Аннотация статьи 7:
Также было принято решение разделить термины-названия служебных морфем и лексем (тэг TGrMark) и термины падежной грамматики (тэг TCGr). Структура лексической базы Наполнение лексической базы тибетской грамматической терминологии составляют лексические единицы, отобранные из тибетской части корпуса по заданным тэгам, а именно по тэгам для маркировки терминов (лингвистических метаданных, см. Табл. 1). Структура базы Для упрощения перевода данных XML в базу и наоборот, структура данных и таблиц внутри базы данных соответствует структуре формата TEI.


Аннотация статьи 8:
Если считать выделенные мерами ассоциации свободные сочетания слов отрицательным показателем эффективности, то с этой точки зрения наименее эффективными оказались меры MI (по 2 свободных сочетания из 10 словоформ и лемм) и minimum sensitivity (2 свободных сочетания для словоформ и 1 для лемм). Заключение и направления совершенствования программы В данной работе мы привели подробное описание использующихся на практике мер ассоциации ― статистических методов выявления сочетаемости слов в тексте, рассмотрели основные проблемы, возникающие при выявлении коллокаций, и попытались решить их при создании собственной программы поиска коллокаций в текстах на русском языке. Проблема выделения сочетаний со знаками препинания в нашей программе решена полностью, проблемы выделения сочетаний знаменательного слова со служебным и случайных сочетаний решены в той мере, в какой позволяет корректная работа библиотеки морфологического анализа.


Аннотация статьи 9:
АИК «Прогноз СПб» предназначен для средне- и долгосрочного прогнозирования социальноэкономического развития Санкт-Петербурга и позволяет решать задачи класса «что будет, если...?» и «что надо, чтобы…?» на основе различных вариантов развития. Классы прогнозно-аналитических задач Совокупность прогнозно-аналитических задач, решаемых с помощью государственной информационной системы Санкт-Петербурга можно классифицировать следующим образом [4, 5]: − кратко- и среднесрочное прогнозирование социальноэкономических процессов; в том числе многовариантное прогнозирование; − выявление взаимного влияния факторов социально-экономического развития региона и построение модельных зависимостей; − стратегическое планирование, оценка реализации стратегий и приоритетных национальных и региональных программ; − оценка эффективности деятельности органов исполнительной власти; − аналитическая обработка и моделирование на основе данных социологических опросов. С использованием моделирующих комплексов, функционирующих в составе ИС ИАО, осуществляется долгосрочное прогнозирование индикаторов социально-экономического развития региона по различным сферам жизнедеятельности (на период до 20 лет) [7].


Аннотация статьи 10:
На втором этапе используется квотная выборка. По данным исследования структура ценностных ориентаций молодежи и их ценностные стереотипы значительно различаются Результаты исследования показывают, что основным жизненным ориентиром молодежи России является семья – более половины участников опроса (56,1 %) назвали её самым важным в жизни. Следующими, по распространенности среди молодежи, по мнению респондентов, являются работа, бизнес, карьера (13,6 %), достижение целей, успех (13,4 %), патриотизм, наследие (13,4 %), семья, брак (12,4 %).


Аннотация статьи 11:
Стандарт открытости представляет собой комплексный документ, состоящий из утвержденной Правительством Российской Федерации Концепции открытости федеральных органов исполнительной власти, а также Методических рекомендаций по реализации принципов открытости в федеральных органах исполнительной власти и Методики мониторинга и оценки открытости федеральных органов исполнительной власти, одобренных Правительственной комиссией по координации деятельности открытого правительства2. Например, «соответствие официального сайта требованиям Федерального закона «Об обеспечении доступа к информации о деятельности государственных органов и органов местного самоуправления»; «наличие на сайте обзоров обращений граждан». Экспертная оценка открытости и прозрачности деятельности федеральных органов исполнительной власти Экспертная оценка может проводиться по разным методикам.


Аннотация статьи 12:
Государственные модели межведомственного и межуровневого обмена информацией в пределах одного государства по типу Государственной модели обмена информацией США (NIEM), см. ниже. Такими направлениями являются международный обмен налоговой информацией, информацией о природных и техногенных катастрофах, медицинской информацией пациентов и др. Есть стандарты, которые используются как для международного обмена информацией, так и для обмена информацией между органами власти внутри страны. В рамках организации объединить всех заинтересованных в развитии моделей данных для обмена информацией в стратегических информационных системах в различных областях деятельности.


Аннотация статьи 13:
По мнению театрального художника Виктора Григорьева, «с викторианской эпохи машинерия по сути не изменилась, именно в это время она развилась до современного состояния. В нем используются как новые, так и старые средства «для расширения границ театра». На некоторых сайтах есть возможность смотреть спектакли онлайн целиком.


Аннотация статьи 14:
Архитектура и основной функционал ИС T-Libra Информационная система T-Libra v.6.x. «одиночество» (308 раз), 5. Проект «Humanitariana» (краткое описание) На основании разработанной ООО «Константа» технологии создания многофункциональных электронных библиотек с сервисами продвинутого полнотекстового поиска (реализованной в информационной системе T-Libra), опыта ее внедрения и эксплуатации в различных организациях России, осуществленных пилотных проектов по использованию поиска для экспликации различных смысловых контекстов и успешной реализации экспериментов по созданию децентрализованной распределенной среды под управлением пользовательского браузера в 2013 году был инициирован проект «Humanitariana» от имени ООО «Константа» и Санкт-Петербургского научно-исследовательского университете информационных технологий, механики и оптики (Университета ИТМО).


Аннотация статьи 15:
В потоке информации пользователю становится все сложнее выделить те публикации, которые в действительности относятся к интересующим его темам, при этом в большинстве случаев конечный пользователь даже не пытается отслеживать все такие публикации, так как считает эту задачу невыполнимой. Вместе с тем, в некоторых случаях показатели охвата публикаций не могут быть получены посредством предоставляемых API, и для получения показателей охвата публикаций необходимо использовать сторонние службы. Более того, для решения задачи отслеживания охвата аудитории не конкретными публикациями, а их темами, необходимо неким образом усреднять конкретные показатели охвата публикаций и вводить весовые коэффициенты, обеспечивающие возможность сравнения разных тем по признаку охвата аудитории.


Аннотация статьи 16:
Анкетирование и тестирование являются важными составляющими работы как для учебных (школы, колледжи, академии, институты), так и для коммерческих организаций (включая как государственные, так и частные компании) именно вследствие того, что предоставляют эту обратную связь между учеником и учителем, учебным материалом и качеством его усвоения, причём в дальнейшем в эту схему можно включить и собственно проверочный материал, форматы и представления тестов, отчётов и т..п. Широка и сфера применения тестов и анкет: их можно использовать с учащимися, прежде всего старших классов, со студентами, сотрудниками организаций; особенно интересны опросы выпускников и новых сотрудников, а также анализ их ответов на протяжении времени [1-3]. В этих случаях результат (например, выборки из баз данных, полученный сложный отчёт целиком) сохраняются во временной памяти на диске; при повторном обращении к нему пользователю показывается запомненный ранее отчёт, если до сих пор не произошло обновление информации, от которой данный отчёт зависит, что отслеживается в системе; то же происходит, если отчёт был получен как временный, при промежуточной приостановке опрашивания до его полного завершения: во избежание нарушения целостности данных пользователю будет показан отчёт не по текущему, а по сохранённому состоянию базы данных. Прежде всего, любой доступ к системе осуществляется на основе паролей и/или специальных уникальных ключей доступа.


Аннотация статьи 17:
В настоящее время в современной России правовые положения части четвертой Гражданского кодекса (далее – ГК РФ) определяют базис, позволяющий издателям, администраторам учебных заведений и учителям определять границы использования авторских текстов в учебной литературе. Докладчики считают, что необходимость обращения к авторам образовательных ресурсов в данном случае должна отсутствовать, т.к. использование предназначено для личных, в частности, учебных целей. Правовые аспекты свободного воспроизведения произведения в учебных целях Правовые положения ст.1274 ГК РФ «Свободное использование произведения в информационных, научных, учебных или культурных целях» существенно исправлены, дополнены и логически опосредовано изменены.


Аннотация статьи 18:
Сетевое научение и организационное научение Сетевое научение (network learning) тесно связано с понятием «организационного научения». В большинстве подходов организационное научение включает в себя и обучение, т.е. результатом такого научения будет как изменение поведения, так и сознания. В этом смысле, сетевое научение происходит, когда наблюдаются перемены в трех основных областях сетевого взаимодействия: в сетевых интерпретациях, в сетевой структуре и в сетевых практиках.


Аннотация статьи 19:
Согласно данным контент-анаиза релевантных сообщений, выгруженных из социальных медиа, в целом у участников клуба с вступлением в него жизнь изменилась в лучшую сторону, об этом свидетельствуют следующие факты: Во-первых, по мнению участников исследования, ожидания от клуба оправдались, у некоторых даже больше, чем они рассчитывали. И я считаю, что это очень большой плюс, что ты перестаешь играть, ты начинаешь видеть жизнь в реале, и то окружение, в котором ты находишься, сняв розовые очки». В результате участия в клубе они чаще задумываются о том, что с ними происходит, и анализируют окружение.


Аннотация статьи 20:
Имеется система представления спектров в виде спектрограмм и в ИС «Электронная структура атомов». В настоящее время возможность построения диаграмм Гротриана имеется в уже упоминавшейся ASD NIST. ИС ЭСА является на сегодня одной из двух информационных системой по атомной спектроскопии, в которой развито автоматическое построение диаграмм Гротриана, которое осуществляется динамически по запросу пользователя и по спектральной информации, хранящейся в базе данных атомных уровней и переходов системы на момент построения.


Аннотация статьи 21:
Во-первых, признавая важность работы государственных органов власти в направлении развития электронных услуг, необходимо помнить о том, что интегральная оценка готовности страны к электронному правительству складывается из нескольких базовых компонентов, характеризующих уровень развития ИКТинфраструктуры и сервисов электронного правительства, а также степень развития человеческого потенциала, отражающую готовность граждан пользоваться государственными услугами в электронном виде. В качестве основных структурных элементов ИАС ЭР выступают следующие подсистемы: − обеспечения интерактивного, открытого и эффективного диалога между органами исполнительной власти, гражданами и бизнесом – «Народный контроль»; − организации процесса предоставления государственных и муниципальных услуг, исполнения функций, осуществления межведомственного электронного взаимодействия и предоставления на портале четкой информации о способе получения услуги на территории Ростовской области – «Услуги и межведомственное взаимодействие»; − обеспечения открытости формирования и исполнения бюджета для жителей региона и конкретного муниципального образования – «Открытый бюджет»; − объединения информационных регистров в электронном виде и автоматизации сбора, обработки и представления данных для муниципального управления, повышения инвестиционной привлекательности муниципалитета и региона в целом, а также подготовки регламентированной отчетности для передачи на региональный уровень – «Электронный паспорт муниципалитета»; − формирования региональных условий для получения максимального политического, экономического и социального эффекта от использования открытых государственных данных – «Открытые данные». Основными целями разработки и внедрения ИАС ЭР являются: − разработка единой технологической платформы по созданию новых социально значимых сервисов для граждан и организаций Ростовской области; − формирование социальноориентированного информационного пространства, предоставляющего гражданам возможность эффективно решать вопросы, возникающие в рамках конкретных жизненных ситуаций; − повышение лояльности населения к электронному способу взаимодействия с региональными органами исполнительной власти и органами местного самоуправления; − повышение качества статистических сведений за счет получения информации от граждан и ее дальнейшей актуализации; − повышение информационной открытости и прозрачности деятельности региональных органов государственной власти и органов местного самоуправления.


Аннотация статьи 22:
Границы таких online-социальных сетей или online-сетевых сообществ формирует определенный смысловой концепт, разделяющийся участниками onlineпространства, и определяющий типы пользователей, составляющих online-социальную сеть: лидеры мнений, сенсоры, реализаторы, читатели, репутационные игроки. Наложим на классификацию пользователей, описанную нами выше, некоторые характеристики социального графа для выявления дополнительных свойств пользователей online-социальных сетей и сообществ: «индекс авторитетности», «мера связности», «мост» «Индекс авторитетности» – степень, которая показывает важность /влияние определенного пользователя (узла социального графа), определяется числом связей в одном узле (вершине) социального графа, при этом эти связи можно разделить на входящие и исходящие связи вершины. Если констелляция акторов представлена преимущественно политикоадминистративными диспозициями при наличии серьезных барьеров для входа новых акторов в процесс производства публичной политики, то высока возможность мобилизации onlineобщественности с последующей ее институционализацией в offline-cреде.


Аннотация статьи 23:
Альтернативой традиционных СМИ становятся возникшие в этот период новые медиа-формы – блоги и системы поддержки социальных сетей. Итак, средства массовой информации, присутствующие в сети Интернет, можно разделить на пять типов:  информационные агентства;  блогерская журналистика;  Интернет-СМИ общей тематики;  тематические Интернет-СМИ;  сайты печатных СМИ. Тенденция обработки одного информационного повода более двух раз (цепочка новые медиа – традиционные СМИ – новые медиа) способствует появлению у пользователей новых возможностей получения и анализа информации.


Аннотация статьи 24:
С другой стороны, разница в степени регулирования Интернета (на примере США и Китая), в масштабе коммуникации, который может выбрать пользователь, не только отражает особенности политического процесса оффлайн, но и является одним из инструментов воспроизводства сложившегося политического порядка. Impact of the Web: оценка социальных, экономических и политических показателей развития государства в контексте влияния на них Интернета. Взаимовлияние развития Интернеткоммуникации и политических систем общества: актуальные проблемы кросснационального исследования Реализация кросс-национального сравнительного анализа данных WIP является перспективной задачей, направленной на решение таких исследовательских вопросов, как:  определение взаимосвязей между степенью открытости политических систем и уровнем открытости Интернет-коммуникации;  выявление взаимозависимостей между характером политического режима и уровнем проникновения Интернета;  анализ коэволюции институциональных и социокультурных факторов, влияющих на структуру потребления Интернет-контента.



In [25]:
annots = pd.DataFrame(annotations, columns=['annotations_sumy'])
sumy = pd.concat([df, annots], join='outer', axis=1)
sumy

,name,text,year,annotations_sumy
0,Kuzmina_IMS_2014_rus.txt,Социально-гуманитарная образовательная среда\n...,2014,"20,77% полагают, что развитие системы дистанци..."
1,Bogoraz_IMS_2014_rus.txt,Централизованные и распределенные социальные с...,2014,"Существует угрозы, которые не имеют прямого от..."
2,Grigoryeva_IMS_2014_rus.txt,Обучение пожилых ИКТ и возможности их\nтрудоус...,2014,"В то же время, исследование ФОМ пказывает, что..."
3,Dyakova_IMS_2014_rus.txt,Использование информационных технологий\nдля б...,2014,"Существует убеждение, что информационные техно..."
4,Lizunova_IMS_2014_rus.txt,Безграничность медиапространства:\nбудущее или...,2014,Медийное пространство – это пространство отнош...
...,...,...,...,...
137,Korablinov_IMS_2020_rus.txt,Подготовка набора данных для вопросно-ответног...,2020,Подготовка набора данных для вопросно-ответног...
138,Khokhlova_IMS_2020_rus.txt,Методы машинного обучения применительно к зада...,2020,Обзор методов Традиционные методы извлечения л...
139,Kuznetsova_IMS_2020_rus.txt,О возможности использования корпуса NOW в курс...,2020,Для проверки частотности из off-list списка бы...
140,Sokolova_IMS_2020_rus.txt,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...
141,Rogov_IMS_2020_rus.txt,Применение деревьев решений для анализа сильны...,2020,Для решения задачи атрибуции текстов хорошо за...

T5

RuT5-base-sum

In [31]:
from transformers import AutoTokenizer, T5ForConditionalGeneration
import torch
from tqdm.notebook import tqdm

model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

annotations_t5 = []

for idx, text in enumerate(tqdm(df.text[:30], desc="Генерация аннотаций первых 30 текстов"), start=1):
    input_ids = tokenizer([text], max_length=600, add_special_tokens=True,
                          padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
    output_ids = model.generate(input_ids=input_ids,
                                min_length=50,
                                max_length=250,
                                no_repeat_ngram_size=4)[0]
    summary = tokenizer.decode(output_ids, skip_special_tokens=True)
    print(f'Аннотация текста {idx}:\n{summary}\n')
    annotations_t5.append(summary)

# Для остальных текстов ставим пустые строки
annotations_t5.extend([''] * (len(df) - 30))

Генерация аннотаций первых 30 текстов:   0%|          | 0/30 [00:00<?, ?it/s]

Аннотация текста 1:
Современные информационные технологии в современной образовательной среде становятся все более востребованными и востребованными в образовательном процессе. Проблемы, связанные с разработкой и применением в учебном процессе современных компьютерных технологий, в свою очередь, обсуждаются в инженерно-техническом и педагогическом сообществах.

Аннотация текста 2:
Социальные сети стали одним из наиболее быстро развивающихся интернет-сервисов в мире. Это связано с повсеместным развитием коммуникаций, компьютеризацией общества и неистребимым желанием человека общаться со старыми друзьями, так и с новыми людьми.

Аннотация текста 3:
Пожилые люди могут оказаться в положении «потерявших роль» и экономическую независимость, считают российские ученые. Это свидетельствует о том, что старение является социально конструируемыми отношениями, практикой и процессом.

Аннотация текста 4:
Использование информационных технологий для борьбы с коррупцией и локальная административная традиция КНР является общим местом в рекомендациях ООН, Всемирного банка, Международного валютного фонда и других международных организаций.

Аннотация текста 5:
В настоящее время исследователи пытаются выяснить основные характеристики новой среды реализации человеческой активности – медиапространства, его глобализации и усилении влияния на человека средств массовой информации.

Аннотация текста 6:
Метод полуавтоматического пополнения семантического класса терминов персонала, основанный на синтаксических связях в корпусе отзывов компании «S7 Airlines» и обработанный с помощью морфосинтаксического анализатора, можно рассматривать как разновидность более общей задачи извлечения именованных сущностей.

Аннотация текста 7:
В Санкт-Петербургском государственном университете разработали корпус тибетских грамматических сочинений, которые наиболее ценятся в тибетской грамматической традиции. Проект направлен на разработку корпуса памятников древней индийской письменности, которая, предположительно, начала свое формирование в VII–VIII вв. н.э., когда были созданы первые дошедшие до нас трактаты «Сумчупа» и «Тагкичжугпа».

Аннотация текста 8:
Программа выявления в тексте двусловных статистически значимых осмысленных коллокаций (на материале русского языка) В.В. Залесская разработала программное обеспечение, способное выявлять двучленные статистически значимые осмысленные коллокации в текстах на русском языке.

Аннотация текста 9:
Интегрированная система информационноаналитического обеспечения исполнительных органов государственной власти Санкт-Петербурга обеспечивает оперативное предоставление прогнозно-аналитических данных всем специалистам и руководителям регионов. Основным фундаментом ИС ИАО является Хранилище данных, позволяющее оперативно предоставлять прогнозноаналитические материалы органам государственной власти.

Аннотация текста 10:
Российская молодая молодежь осознает политические ценности в глобальной сети, а также оказывает влияние на формирование ценностных ориентаций молодежи. Эксперты считают, что интернет-коммуникации может привести к формированию новых форматов политической коммуникации, в том числе и политической мобилизации электората и краудсорсингу структур гражданского общества.

Аннотация текста 11:
Система оценки открытости исполнительной власти невозможна без активного участия общества в создании новой модели открытой и прозрачной государственной власти, считают эксперты «Высшей школы экономики».

Аннотация текста 12:
Проблема с импортозамещением ИТ-технологий в России оказалась похожей на проблему 2000-го года. Эксперты считают, что импортозамещение является инструментом экономической стратегии и промышленной политики государства.

Аннотация текста 13:
Современный театр и его современное наполнение стали одним из основных видов искусства, в том числе электронными средствами, которые позволяют воспринимать театр как цифровой перформанс, а также расширить возможности обратной связи зрителя с театром через Интернет.

Аннотация текста 14:
Сервисы полнотекстового поиска в распределенной среде являются универсальным инструментом поддержки гуманитарных исследований, а также инструментом экспликации контекстного знания для нескольких тем гуманитарной направленности.

Аннотация текста 15:
Пользователи интернет-среды становятся все сложнее выделить в информационном потоке информации те сообщения, которые относятся к интересующим его темам, а также те, которые не вызывают у пользователя сомнений в их достоверности или содержании.

Аннотация текста 16:
Анкетирование и тестирование для старшеклассников, студентов и сотрудников организаций являются важнейшей составляющей любого обучения, да и для многих профессиональных видов деятельности.

Аннотация текста 17:
Авторские тексты в цифровой форме, используемые в учебной литературе, обсуждались в докладе Научной педагогической библиотеки им. К.Д. Ушинского «Практика оцифровки электронных образовательных ресурсов» Е.А. Данилина и А.М. Цапенко.

Аннотация текста 18:
Электронные платформы и сетевое научение: как трансформируется публичное пространство, Л.В. Сморгунов считает, что правительство 2.0 ломает старые привычные формы взаимодействия государства и общества, а также повышает управляемость сетевой политики посредством сетевого научения.

Аннотация текста 19:
Киберметрический анализ общественной оценки клубного формирования «Школа великих книг» как метода информального самообразования взрослых в России выявил несколько смысловых блоков, дающих представление о репрезентации в общественном мнении проекта.

Аннотация текста 20:
Современные информационные системы по спектральным данным атомных систем являются одним из примеров Интернет ресурсов, критически важных для поддержки научных исследований. Наиболее перспективным механизмом предоставления спектральных данных являются информационные системы, основанные на базах данных, обеспечивающие взаимодействие с пользователем по протоколу HTTP.

Аннотация текста 21:
Информационное общество и современные технологии управления в мире становятся основной движущей силой прогресса и цивилизованного развития, считают эксперты Южно-Российского института управления при Президенте Российской Федерации.

Аннотация текста 22:
Типы пользователей онлайн-социальных сетей: теоретико-методологические основания для классификации жных сетей, а также методологические основания классификации их. Введение может быть проведено в рамках международной конференции, которая пройдет в Москве.

Аннотация текста 23:
В современной России появились новые медиа-форматы, которые позволяют охватывать самую широкую аудиторию потребителей информации за несколько дней. В настоящее время информационный повод может достигать практически стопроцентного охвата аудитории потребителей информации.

Аннотация текста 24:
Российская интернет-аудитория является одной из самых быстрорастущих в мире, свидетельствуют данные исследования Internet World Stats. Россия занимает 6-е место по величине пользовательской аудитории, оставляя позади Германию, Великобританию и Францию. Эксперты считают, что политические режимы в странахлидерах отличаются самым серьезным образом.

Аннотация текста 25:
«повестка дня» в сфере электронного правительства: результаты контент-анализа новостных сообщений Университета ИТМО, НИУ ВШЭ - Санкт-Петербург. Аналитики и эксперты ЦТЭП выяснили специфику обсуждаемости процесса внедрения электронных государственных услуг в сети Интернет, в том числе в социальных медиа и блогосфере.

Аннотация текста 26:
Мобильные технологии как инструмент совершенствования механизмов электронного участия С.А. Кудинов, Д.Ю. Белун и другие исследователи считают, что электронное правительство является инструментом для улучшения качества государственного управления и повышения эффективности и результативности управленческих решений.

Аннотация текста 27:
Открытые государственные данные в России: исследование дискуссий в социальных сетях по тематике открытых государственных данных, оценены перспективы дальнейшего развития открытых данных в Российской Федерации.

Аннотация текста 28:
Проект комплексной информационной системы поддержки научных исследований Д.Е. Прокудин считает, что научная деятельность в условиях непрерывно развивающегося информационного общества претерпевает изменения в любой сфере человеческой деятельности.

Аннотация текста 29:
Задача прогнозирования исходов выборов и протестов по цифровым следам пользователей в социальных сетях является фундаментальной научной задачей политологии. В данной работе будет проведен компаративный анализ методологических основ двух указанных задач, на основе чего будут указаны потенциальные трудности и ограничения, связанные с прогнозированием протестной активности.

Аннотация текста 30:
Взаимодействие между кредитными организациями и государственными финансовыми учетными системами исполнения бюджетов в процессе осуществления безналичных и налично-денежных расчетов обусловлено анализом возникающих проблем исполнения бюджета и ужесточением требований к качеству, достоверности и своевременности проводимых платежей со стороны законодательной власти Российской Федерации.

In [32]:
df['annotations_t5'] = annotations_t5

df.head(35)

,name,text,year,annotations_t5
0,Kuzmina_IMS_2014_rus.txt,Социально-гуманитарная образовательная среда\n...,2014,Современные информационные технологии в соврем...
1,Bogoraz_IMS_2014_rus.txt,Централизованные и распределенные социальные с...,2014,Социальные сети стали одним из наиболее быстро...
2,Grigoryeva_IMS_2014_rus.txt,Обучение пожилых ИКТ и возможности их\nтрудоус...,2014,Пожилые люди могут оказаться в положении «поте...
3,Dyakova_IMS_2014_rus.txt,Использование информационных технологий\nдля б...,2014,Использование информационных технологий для бо...
4,Lizunova_IMS_2014_rus.txt,Безграничность медиапространства:\nбудущее или...,2014,В настоящее время исследователи пытаются выясн...
5,Adaskina_IMS_2014_rus.txt,Полуавтоматическое пополнение словарей на осно...,2014,Метод полуавтоматического пополнения семантиче...
6,Grokhovskiy_IMS_2014_rus.txt,Лексическая база корпуса тибетских грамматичес...,2014,В Санкт-Петербургском государственном универси...
7,Zalesskaya_IMS_2014_rus.txt,Программа выявления в тексте двучленных\nстати...,2014,Программа выявления в тексте двусловных статис...
8,Kalinichenko_IMS_2014_rus.txt,Информационные технологии в целях обеспечения\...,2014,Интегрированная система информационноаналитиче...
9,Brodovskaya_Siniakov_IMS_2014_rus.txt,Влияние Интернет-коммуникации на формирование\...,2014,Российская молодая молодежь осознает политичес...
10,Dmitrieva_IMS_2014_rus.txt,Формирование системы оценки открытости\nисполн...,2014,Система оценки открытости исполнительной власт...
11,Akatkin_IMS_2014_rus.txt,Стандарты моделей данных для обмена информацие...,2014,Проблема с импортозамещением ИТ-технологий в Р...
12,Borisov_Shustrova_IMS_2014_rus.txt,"Современный театр и Интернет\nН.В. Борисов, О....",2014,Современный театр и его современное наполнение...
13,Lyapin_IMS_2014_rus.txt,Поддержка гуманитарных исследований сервисами\...,2014,Сервисы полнотекстового поиска в распределенно...
14,Soms_IMS_2014_rus.txt,Использование средств лингвистической обработк...,2014,Пользователи интернет-среды становятся все сло...
15,Kolodin_IMS_2014_rus.txt,Анкетирование и тестирование для старшеклассни...,2014,Анкетирование и тестирование для старшеклассни...
16,Danilina_IMS_2014_rus.txt,"Авторские тексты в цифровой форме,\nиспользуем...",2014,"Авторские тексты в цифровой форме, используемы..."
17,Smorgunov_IMS_2014_rus.txt,Электронные платформы и сетевое научение:\nкак...,2014,Электронные платформы и сетевое научение: как ...
18,Brodovskaya_IMS_2014_rus.txt,Киберметрический анализ общественной оценки\nк...,2014,Киберметрический анализ общественной оценки кл...
19,Yatsenko_IMS_2014_rus.txt,Информационная система «Электронная структура\...,2014,Современные информационные системы по спектрал...
20,Baranov_IMS_2014_rus.txt,Формирование электронного правительства в субъ...,2014,Информационное общество и современные технолог...
21,Ryabchenko_IMS_2014_rus.txt,Типы пользователей online-социальных сетей:\nт...,2014,Типы пользователей онлайн-социальных сетей: те...
22,Chizhik_IMS_2014_rus.txt,Новые медиа форматы в современной России\nА.В....,2014,В современной России появились новые медиа-фор...
23,Brodovskaya_Karzubov_IMS_2014_rus.txt,Специфика кросс-национальных исследований\nраз...,2014,Российская интернет-аудитория является одной и...
24,Chugunov_IMS_2014_rus.txt,Формирование «повестки дня» в сфере\nэлектронн...,2014,«повестка дня» в сфере электронного правительс...
25,Kudinov_IMS_2014_rus.txt,Мобильные технологии как инструмент\nсовершенс...,2014,Мобильные технологии как инструмент совершенст...
26,Vidyasova_IMS_2014_rus.txt,Открытые государственные данные в России:\nисс...,2014,Открытые государственные данные в России: иссл...
27,Prokudin_IMS_2014_rus.txt,Проектирование и реализация комплексной\nинфор...,2014,Проект комплексной информационной системы подд...
28,Filchenkov_IMS_2014_rus.txt,Компаративный анализ методологических основ за...,2014,Задача прогнозирования исходов выборов и проте...
29,Balakshina_IMS_2014_rus.txt,Перспективы развития электронного взаимодейств...,2014,Взаимодействие между кредитными организациями ...
30,Serebriakov_IMS_2014_rus.txt,Распространение данных\nпо теплофизическим сво...,2014,
31,Kanygin_IMS_2014_rus.txt,Проблемы визуализации социального знания\nГ.В....,2014,
32,Koltsov_IMS_2014_rus.txt,Интерпретация семантических связей в текстах\n...,2014,
33,Vozmishcheva_IMS_2014_rus.txt,Технологии билингвистического обучения курсу\n...,2014,
34,Kazakov_IMS_2014_rus.txt,Феномен «социальных сетей»: вопросы терминолог...,2014,

In [35]:
from tqdm.notebook import tqdm

annotations_t5_short = []

for text in tqdm(df.text[:30], desc="Генерация коротких заголовков T5 (30 шт)"):
    input_ids = tokenizer([text], max_length=512, add_special_tokens=True,
                          padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
    output_ids = model.generate(
        input_ids=input_ids,
        min_length=5,
        max_length=30,
        num_beams=5,
        early_stopping=True
    )[0]
    summary = tokenizer.decode(output_ids, skip_special_tokens=True)
    annotations_t5_short.append(summary)

# Заполним остальные строки пустыми
annotations_t5_short.extend([''] * (len(df) - 30))

df['T5_short'] = annotations_t5_short

df.head(35)

Генерация коротких заголовков T5 (30 шт):   0%|          | 0/30 [00:00<?, ?it/s]

,name,text,year,annotations_t5,T5_short
0,Kuzmina_IMS_2014_rus.txt,Социально-гуманитарная образовательная среда\n...,2014,Современные информационные технологии в соврем...,Современные информационные технологии в соврем...
1,Bogoraz_IMS_2014_rus.txt,Централизованные и распределенные социальные с...,2014,Социальные сети стали одним из наиболее быстро...,Социальные сети стали одним из наиболее быстро...
2,Grigoryeva_IMS_2014_rus.txt,Обучение пожилых ИКТ и возможности их\nтрудоус...,2014,Пожилые люди могут оказаться в положении «поте...,"Ученые считают, что старение является социальн..."
3,Dyakova_IMS_2014_rus.txt,Использование информационных технологий\nдля б...,2014,Использование информационных технологий для бо...,Использование информационных технологий для бо...
4,Lizunova_IMS_2014_rus.txt,Безграничность медиапространства:\nбудущее или...,2014,В настоящее время исследователи пытаются выясн...,"Ученые и исследователи пытаются выяснить, буде..."
5,Adaskina_IMS_2014_rus.txt,Полуавтоматическое пополнение словарей на осно...,2014,Метод полуавтоматического пополнения семантиче...,Метод полуавтоматического пополнения семантиче...
6,Grokhovskiy_IMS_2014_rus.txt,Лексическая база корпуса тибетских грамматичес...,2014,В Санкт-Петербургском государственном универси...,В Санкт-Петербурге создается корпус тибетских ...
7,Zalesskaya_IMS_2014_rus.txt,Программа выявления в тексте двучленных\nстати...,2014,Программа выявления в тексте двусловных статис...,Программа выявления в тексте двусловных статис...
8,Kalinichenko_IMS_2014_rus.txt,Информационные технологии в целях обеспечения\...,2014,Интегрированная система информационноаналитиче...,Информационные технологии в целях обеспечения ...
9,Brodovskaya_Siniakov_IMS_2014_rus.txt,Влияние Интернет-коммуникации на формирование\...,2014,Российская молодая молодежь осознает политичес...,"Российская молодая молодежь, ориентированная н..."
10,Dmitrieva_IMS_2014_rus.txt,Формирование системы оценки открытости\nисполн...,2014,Система оценки открытости исполнительной власт...,Система оценки открытости исполнительной власт...
11,Akatkin_IMS_2014_rus.txt,Стандарты моделей данных для обмена информацие...,2014,Проблема с импортозамещением ИТ-технологий в Р...,Проблема с ИТ-импортозамещением в России оказа...
12,Borisov_Shustrova_IMS_2014_rus.txt,"Современный театр и Интернет\nН.В. Борисов, О....",2014,Современный театр и его современное наполнение...,Современный театр и его современное наполнение...
13,Lyapin_IMS_2014_rus.txt,Поддержка гуманитарных исследований сервисами\...,2014,Сервисы полнотекстового поиска в распределенно...,Поддержка гуманитарных исследований сервисами ...
14,Soms_IMS_2014_rus.txt,Использование средств лингвистической обработк...,2014,Пользователи интернет-среды становятся все сло...,Введение лингвистической обработки текстов в с...
15,Kolodin_IMS_2014_rus.txt,Анкетирование и тестирование для старшеклассни...,2014,Анкетирование и тестирование для старшеклассни...,Основы анкетирования и тестирования для старше...
16,Danilina_IMS_2014_rus.txt,"Авторские тексты в цифровой форме,\nиспользуем...",2014,"Авторские тексты в цифровой форме, используемы...","Авторские тексты в цифровой форме, используемы..."
17,Smorgunov_IMS_2014_rus.txt,Электронные платформы и сетевое научение:\nкак...,2014,Электронные платформы и сетевое научение: как ...,Электронные платформы и сетевое научение: как ...
18,Brodovskaya_IMS_2014_rus.txt,Киберметрический анализ общественной оценки\nк...,2014,Киберметрический анализ общественной оценки кл...,Киберметрический анализ общественной оценки кл...
19,Yatsenko_IMS_2014_rus.txt,Информационная система «Электронная структура\...,2014,Современные информационные системы по спектрал...,Современные информационные системы по спектрал...
20,Baranov_IMS_2014_rus.txt,Формирование электронного правительства в субъ...,2014,Информационное общество и современные технолог...,"Информационное общество, управленческие иннова..."
21,Ryabchenko_IMS_2014_rus.txt,Типы пользователей online-социальных сетей:\nт...,2014,Типы пользователей онлайн-социальных сетей: те...,Типы пользователей онлайн-социальных сетей: те...
22,Chizhik_IMS_2014_rus.txt,Новые медиа форматы в современной России\nА.В....,2014,В современной России появились новые медиа-фор...,В современной России появились новые медиа-фор...
23,Brodovskaya_Karzubov_IMS_2014_rus.txt,Специфика кросс-национальных исследований\nраз...,2014,Российская интернет-аудитория является одной и...,Российская интернет-аудитория является одним и...
24,Chugunov_IMS_2014_rus.txt,Формирование «повестки дня» в сфере\nэлектронн...,2014,«повестка дня» в сфере электронного правительс...,«повестка дня» в сфере электронного правительс...
25,Kudinov_IMS_2014_rus.txt,Мобильные технологии как инструмент\nсовершенс...,2014,Мобильные технологии как инструмент совершенст...,Мобильные технологии как инструмент совершенст...
26,Vidyasova_IMS_2014_rus.txt,Открытые государственные данные в России:\nисс...,2014,Открытые государственные данные в России: иссл...,Открытые государственные данные в России: иссл...
27,Prokudin_IMS_2014_rus.txt,Проектирование и реализация комплексной\nинфор...,2014,Проект комплексной информационной системы подд...,Проект комплексной информационной системы подд...
28,Filchenkov_IMS_2014_rus.txt,Компаративный анализ методологических основ за...,2014,Задача прогнозирования исходов выборов и проте...,Задача прогнозирования исходов выборов и проте...
29,Balakshina_IMS_2014_rus.txt,Перспективы развития электронного взаимодейств...,2014,Взаимодействие между кредитными организациями ...,Взаимодействие между кредитными организациями ...
30,Serebriakov_IMS_2014_rus.txt,Распространение данных\nпо теплофизическим сво...,2014,,
31,Kanygin_IMS_2014_rus.txt,Проблемы визуализации социального знания\nГ.В....,2014,,
32,Koltsov_IMS_2014_rus.txt,Интерпретация семантических связей в текстах\n...,2014,,
33,Vozmishcheva_IMS_2014_rus.txt,Технологии билингвистического обучения курсу\n...,2014,,
34,Kazakov_IMS_2014_rus.txt,Феномен «социальных сетей»: вопросы терминолог...,2014,,