In [3]:
import os
import pandas as pd

In [4]:
years = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [5]:
path = "C:\\Users\\sasha\\Desktop\\opiskelu\\Семантические анализаторы\\Суммаризация\\articles"

In [6]:
texts = []

In [7]:
for root, dirs, files in os.walk(path):
  for file in files:
      if 'annotation' not in file:
        with open(os.path.join(root,file), 'r', encoding='utf-8')as f:
          text = f.read()
          name = str(file[:-4])
          year = str(file[-8:-4])
          texts += [(name, text, year)]

In [8]:
texts[:1]

[('Belkin_IMS_2024_rus',
  '1. Введение По  мере  стремительного  развития  Интернета новый  вид  приобретают  и  различные онлайн-платформы,  социальные  сети,  форумы  и  т.д.  Некоторые  подобные  площадки агрегируют  отзывы  интернет-пользователей,  описывающие  какой-либо  товар  или заведение. Отзыв  представляет  собой  текст  произвольной  длины,  написанный  пользователем  и выражающий его личное отношение к тому или иному объекту. Часто платформы дают возможность оценивать степень удовлетворенности в баллах от 1 до 5.Пользовательский  фидбек  может  быть  очень  ценным  источником  информации  для организаций,  направленных на  предоставление  различных  услуг  людям[1].  В  отзывах пользователи могут указывать на неочевидные проблемы, недостатки или несоответствие действительности информации, указанной на сайте организации. Это может помочь быстро выявить и своевременно устранить недочеты. Большое количество положительных отзывов влияет на приток новых клиентов, так как люди в первую очередь обращают внимание на рейтинг и оценки. Также, положительные отзывы могут быть использованы в рекламных целях, демонстрируя их на сайте или в социальных сетях. С другой стороны, отзывы могут помочь в оценке конкурентных заведений или товаров, например, понять сильные и слабые стороны, выявить новые тренды и возможности для роста. Эффективными инструментами изучения пользовательских отзывов являются анализ тональности и тематическое моделирование [2]. Тематическое моделирование позволяет выделить  ключевые  темы  и  проблемы,  которые  обсуждаются  в  отзывах  [3].  Вдобавок, можно  сравнивать  различные  группы  пользователей  и  выявлять  их  потребности  и предпочтения. В свою очередь, анализ тональности комментариев и отзывов помогает понять то, какие эмоции  выражают  пользователи.  Обученный  на  достаточно  большом  объеме  данных алгоритм анализа тональности поможет исследовать данные, не имеющие таких же оценок или  меток,  как  на  онлайн-платформах.  Существует  множество  традиционных  и современных  способов  сбора  отзывов,  которые  используются  в  настоящее  время.  К традиционным можно отнести бумажные формы для отзывов, как, например, книги жалоб и предложений или заполнение опросных листов [4]. Среди современных способов можно выделить электронные опросы, мониторинг социальных медиа и телефонные интервью. Такие данные не содержат конкретной метрики, говорящей об эмоциональном отношении опрошенного. В таких случаях и может пригодиться модель анализа тональности. Особенно важно понимать потребности и опыт пациентов в сфере здравоохранения, так как их мнение является ключевым показателем качества. Интернет дал людям возможность выражать свои мнения на  различных платформах, что создало большой объем данных, исследование которых может выявить тенденции, не замеченные ранее, в медицинских услугах. Исследователи из Имперского колледжа Лондона собрали комментарии пациентов с сайта NHS Choices за 2008, 2009 и 2011 годы (13802 текста) и применили методы анализа тональности [5]. Данные за 2010 год (6412 комментариев) использовались для проверки точности  предсказания.  Целью  было  обучение  модели  машинного  обучения  для автоматического   определения   рекомендаций пациентов,   чистоты   медицинского учреждения  и  уважительного  отношения.  Алгоритм  классифицировал  комментарии  на основе  примеров  и  проверял  точность  предсказания,  сравнивая  результаты  с  оценками пациентов  по  шкале  Ликерта.  Исследование  показало  высокую  точность  предсказаний, подтверждая соответствие прогнозов результатам опросов. В  другом  исследовании  группа  ученых  собрала  корпус  данных  с  сайта Otzovik, состоящий  из  1,4  миллиона  пользовательских  отзывов  на  русском  языке  о  здоровье  и лекарствах, а также 500 подробно аннотированных отзывов [6]. Корпус называется RuDReC и находится в публичном доступе. Ученые затем использовали эти тексты для обучения моделей Multi-BERT, RuBERT и RuDR-BERT, сравнив их способность извлекать из отзывов пользователей  информацию  о  названии  лекарств,  побочных  эффектах,  заболеваниях  и здоровье. В  еще  одной  работе  исследователи  так  же  собрали  корпус  из  2800  комментариев пользователей  на  форуме Otzovik.  В  статье  анализируется  то,  как  выбор  различных компонентов  модели  влияет  на  точность  распознавания  сущностей.  Исследователи применяют тот же подход к аннотированию текстов, что и авторы [6], и обучают на них алгоритм нейронной сети. Результатом работы стало то, что был установлен новый уровень точности извлечения биомедицинских сущностей для русского языка на полноразмерном размеченном корпусе [7]. Собранные для исследования данные могут быть получены по запросу. Также стоит отметить статью, в которой описывается способ выявления связей между лекарствами на основе семантического анализа текстовых данных [8]. Авторы применили веб-краулинг для сбора текстов с различных медицинских порталов. Всего было собрано примерно 2,5 млн текстов, из которых были извлечены названия препаратов, описание их действия и другие сущности. Затем полученные данные были векторизованы и сравнены между собой. Эксперименты показали, что такой подход может успешно идентифицировать препараты с похожими терапевтическими эффектами. Однако в машинном обучении существует  проблема нехватки размеченных данных, необходимых  для  обучения  моделей.  В  открытом  доступе  не  всегда  можно  найти достаточно информации или уже готовых «датасетов» с метками. Особенно это касается такого  домена,  как  медицинские  учреждения.  В  данном  случае  нехватка  частично обусловлена тем, что структура сайтов поликлиник и больниц не располагает отдельной секцией  для  отзывов  и  оценки  работы  учреждения.  Кроме  того,  очень  много  данных находится  в  закрытом доступе,  так  как  они  содержатся  на  бумажных  носителях  и  не оцифрованы. В последнее время обсуждают важность открытости данных и кода для сотрудничества государств  в  борьбе  с  глобальными  проблемами.  Доклад  ЮНЕСКО  подчеркивает,  что открытые  данные  обеспечивают  доступ  к  необходимой  информации  для  исследований, политики и мер против глобальных кризисов, таких  как COVID-19 [9]. Искусственный интеллект  помогает  анализировать  большие  объемы  данных,  выявляя  скрытые закономерности для принятия решений. Для публикации данных нужно выполнить три этапа: разработка политики управления и обмена данными, решение о публикации данных и привлечение пользователей. На первом этапе определяются обязательства, принципы, законодательные ссылки, причины недоступности данных, сбор и обучение пользователей. Затем принимается решение о том, какие наборы данных будут опубликованы и на условиях лицензирования.  После  этого  данные  публикуются  на  веб-сайте.  Этап  привлечения пользователей  включает  в  себя  информирование,  консультирование,  поддержку международного взаимодействия и предотвращение злоупотреблений. Также, необходимо регулярно  обновлять  данные  для  сохранения  их  актуальности.  Можно  заметить,  что предлагаемая процедура является цикличной поскольку после каждой публикации новых данных, она должна заново проходить все описанные этапы. Тем не менее, далеко не все страны придерживаются указанных выше рекомендаций и принципов. По этой причине нехватка качественных наборов данных, необходимых для обучения  алгоритмов  машинного  обучения,  является  актуальной  проблемой  во  многих областях науки. В  связи  с  этим  было  принято  решение  сформировать  подобный  корпус  с  нуля  при помощи компьютерных средств[10].2. Разработка алгоритма Для сбора информации и создания корпуса был разработан алгоритм и реализован на языке  программирования Python.  В  качестве  источника  данных,  с  которого  программа собирает отзывы, был выбран вебсайт онлайн-карт «ЯндексКарты». Формирование набора данных опирается на оценки, выставленные пользователями учреждениям. На сайте они имеют вид «звездочек» в диапазоне от 1 до 5.Принцип  работы  алгоритма  сводится  к  тому,  что  сначала  задаются  параметры,  по которым  будет  идти  поиск  организаций  и  учреждений  на  сайте.  В  результате  поиска выпадает  список  карточек  организаций,  который  затем прокручивается  вниз,  пока  не достигнет заданного числа искомых организаций. С каждой карточки собирается ссылка, ведущая  на  соответствующие  отзывы.  Каждая  ссылка  обрабатывается,  а  отзывы, находящиеся  на  странице,  прокручиваются  до  конца.  Затем  из  них,  оценок  и  имен пользователей  формируется  набор  данных  при  помощи  библиотеки «pandas».  Наконец, сформированный «датасет» передается внешней таблице, вбирающей в себя все результаты обработки. В  нашем  исследовании  для  реализации  алгоритма  использовались  следующие библиотеки Python: «Selenium», «BeautifulSoup», «pandas»и «pymorphy3».  Первые  две библиотеки  из  перечисленных,  необходимы  для  взаимодействия  с  веб-браузером  и извлечения  данных  с  сайта,  соответственно.  «Selenium»  автоматизирует  работу  веб-браузеров,  а «Beautiful  Soup»  облегчает  «веб-скраппинг»,  разбирая  HTML-и  XML-файлы[11]. Программная реализация алгоритма состоит из 6 функций, которые в процессе работы многократно вызываются. Прежде всего задаются параметры веб-драйвера, который будет моделировать действия пользователя в браузере, давая тем самым доступ к необходимой информации. На первом этапе указывается, какой браузер из 5 доступных будет использоваться для работы,  поскольку  структура  сайтов  для  разных  браузеров  отличается.  Для  данного исследования был выбран «GoogleChrome». Для ускорения работы кода следует применить специальный параметр, запрещающий использовать режим с графическим интерфейсом браузера. Данный режим весьма полезен, но только при разработке и экспериментах, так как он показывает каждое действие, которое было запрограммированно. В случае обычного использования программы нет необходимости следить за процессом моделирования работы браузера, так как это может оказать дополнительную нагрузку на компьютер. На  втором  этапе  задаются  функции,  которые  затем  объединяются  в  главной, исполняющей и автоматизирующей весь процесс. Первая функция очень важна, так как она необходима  для  имитации  пролистывания  страницы  при  помощи  ползунка,  поскольку одной  из  главных  сложностей  сбора  данных стала  процедурная  загрузка  отзывов  и учреждений  на  сайте.  Без  этого  решения  программа  может  собирать  только  первые 5предзагруженных текстов и ссылок. Третья функция отвечает за циклический поиск в коде сайта ссылок, ведущих с карточек найденных учреждений на отзывы к ним. Следующая функция совершает парсинг отзывов, поочередно переходя по заданному списку  ссылок.  Поскольку  сайт  не  всегда  успевает  загрузиться  быстро,  необходимо искусственно  замедлить  работу  кода,  давая  возможность  прогрузиться  всем  нужным элементам.   В   зависимости   от   количества   отзывов   программа   подсчитывает приблизительное  число  прокруток  ползунка,  чтобы  загрузить  все  тексты.  Для  этого используется библиотека «time», которая тормозит процесс выполнения кода на нужное количество секунд. Также на этом этапе вместе с отзывами собираются и соответствующие им оценки от 1 до 5.Стоит отметить, что не все пользователи ставят оценки. Хотя по нашим наблюдениям это довольно редкое явление, его необходимо учитывать: в противном случае, сталкиваясь с отсутствием оценки, код будет аварий но завершаться. Такие отзывы включаются в набор данных, но со специальной меткой. На этапе предобработки данных подобные тексты будут удалены или размечены вручную, если их количество будет достаточно большим. Помимо оценок данная функция собирает имена пользователей, которые затем используются для определения пола комментатора. На финальном этапе главная функция принимает на вход параметры поиска данных: тип организации, город для сбора отзывов, район и количество организаций, которое нужно обработать. Количество организаций указывается исследователем или иным пользователем, желающим сформировать набор данных в каком-либо домене. Эти параметры попадают в поисковую  строку  на  сайте,  после  чего  начинают  работать  другие  функции.  При  этом функция контролирует, чтобы параметры вводились правильно. Если какой-то параметр не был введен, то в работе будет использовано базовое значение этого параметра. Если было найдено недостаточное число организаций, запускается цикл, дополняющий список ссылок до тех пор, пока не наберется нужное количество. В случае, если было обработано слишком много сайтов, то список будет обрезан до обозначенного числа. Во избежание бесконечного поиска количество итераций ограничено максимальным числом допустимых циклов, к которым прибавляется еще 5 дополнительных. Когда процесс сбора завершен, функция, используя цикл, объединяет все полученные данные в единый датасет и возвращает его для дальнейшей работы. В рамках исследования программа собрала 64451 отзыв о350 поликлиниках Санкт-Петербурга. Время работы программы составило примерно 3 часа. В таблице приведены 5примеров из собранного набора отзывов (в отзывах сохранена авторская орфография; ФИО  упомянутых  в  отзывах  сотрудников  медучреждений  были  закодированы  путём сокращения имен, фамилий и отчеств до инициалов). Фамилии упомянутых врачей скрыты с целью сохранения безопасности личной информации. Как показано на рисунке, основные темы, выявленные в отзывах, включают обсуждение медицинского персонала, медицинских учреждений, процедур, записей и самих процессов на прием ко врачу, а также инфраструктуры. Поскольку нет строгих правил и ограничений, диктующих то, как надо писать отзывы, в них содержится множество индивидуальных лингвистических особенностей пользователей, которые будут кратко описаны в следующем разделе. 3. Предварительный лингвистический и стилистический анализ собранного датасета Пациенты поликлиник, оставляющие отзывы, часто используют в своих сообщениях разнообразные  фразеологизмы,  сленг  и  эмодзи.  Они  также  часто  совершают грамматические  и  пунктуационные  ошибки  и  выделяют  отдельные  слова  заглавными буквами. По причине того, что отзывы посвящены медучреждениям, пользователи часто описывают  свой  опыт  посещения  врачей,  упоминая  конкретные  даты,  имена  врачей  и другую информацию. К примеру, некоторые пациенты выражают благодарность отдельным врачам, которые оказали им помощь. Другие, наоборот, критикуют кого-то, обращаются к администрации больницы или поликлиники, призывая принять меры. Зачастую пользователи выражают свое отношение весьма эмоционально, используя в тексте скобочки для демонстрации эмоции. Их количество может варьироваться от одной до нескольких десятков. Они могут выражать как радость («))»), так и печаль («((»), а их количество  указывает  на  силу  испытанных  эмоций.  Более  того,  в  некоторых  случаях множественные скобочки сопровождают язвительные, саркастические и иронизирующие комментарии.  Кроме  того,  пациенты  могут  ставить  многоточие.  В  каких-то  случаях многоточие  используется  при  перечислении  большого  списка  объектов,  например специальностей врачей, либо для выражения расстройства, когда пациент не получил того, что ожидал. Также, для акцентирования внимания на каких-либо конкретных аспектах, пользователи  выделяют  слова  заглавными  буквами.  Как  правило,  это  встречается  в негативных  отзывах,  например,  при  описании  большого  времени  ожидания  в  очереди («ЧАС») или при неудовлетворительном качестве обслуживания в платной поликлинике («ПЛАТНАЯ»). Вдобавок  ко  всему  перечисленному,  пациенты  регулярно  используют  слэнг, неформальные  слова  и  выражения.  Они  могут  быть  специфичны  для  определенных социальных  групп,  возрастных  категорий  или  регионов  и  зачастую  могут  меняться  и развиваться  со  временем  (выявление  этих  закономерностей  может  стать  предметом отдельного исследования в будущем). Например, часто можно встретить преобразованные для  простоты  употребления  медицинские  термины.  Вместо слова  «флюорография» вероятнее  увидеть  слово  «флюшка».  Очень  много  пользователей  используют  большое количество разговорных выражений в своих отзывах. Так, они подчеркивают ту или иную эмоцию, которую стремятся донести до других. К примеру, некоторые пользователи так описывают хорошую работу медперсонала: «Медсестра колет как богиня» или «просто крутой профессионал своего дела». Негативные отзывы так же очень богаты на примеры: «аж  волосы  дыбом»,  «фикалии  в  уши  льют...»  или  «с  горем  пополам  профосмотр  был пройден». Отдельно можно упомянуть эмодзи, которые встречаются в пользовательских отзывах. Эмодзи —это  набор  символов,  представляющих  широкий  спектр  эмоций,  объектов, действий и идей. Они широко используются в современной коммуникации в социальных сетях, мессенджерах, форумах и других онлайн-платформах. Эмодзи позволяют выразить эмоции более точно и наглядно, чем простые текстовые сообщения, а в некоторых случаях, они  могут  заменять  слова  или  целые  фразы,  экономя  место  и  делая  сообщение  более лаконичным. 4.Дальнейшее исследование Полученный  набор  данных  станет  основой  для  обучения  ряда  моделей  анализа тональности, из которых будет выбрана наиболее эффективная. Однако перед этим данные следует предобработать. Для этого из данных будут извлечены в отдельный столбец эмодзи, которые были использованы пользователями для усиления эмоциональной составляющей отзыва.  Столбец  с  эмодзи  может  быть  использован  для  улучшения  качества  модели тональности текста. Кроме того, данные нужно проверить на дубликаты, так как некоторые пользователи могут писать несколько полностью совпадающих отзывов. Они могут быть посвящены  разным  учреждениям,  но  одинаковые  комментарии  от  одного  пользователя снижают качество данных. В полученном наборе данных обнаружилось чуть более 2 тысяч дубликатов.  Затем  данные  разделяются  на  токены,  слова  приводятся  к  основе  и лемматизируются.  Это  необходимо  для  уменьшения  размера  словаря  и  улучшения обобщающей способности модели. После этого данные преобразуются в числовой формат, необходимый  для  обучения  модели.  Для  этого  используется  один  из  существующих методов векторизации текстовых данных. За обучением модели анализа тональности следует обучение алгоритма тематического моделирования. Выделение ключевых тем в отзывах с разделением на положительные и отрицательные, а также с разделением пользователей на группы позволит проанализировать наиболее важные потребности, недостатки и преимущества, которые находятся в текстах.5. Заключение Итогом  данного  исследования  стал  алгоритм,  который  собирает  пользовательские отзывы  на  сайте  «Яндекс Карты»,  используя  настраиваемые  параметры.  Также  было проанализировано влияние отзывов об различных организациях и составлен набор данных, содержащий отзывы пользователей о поликлиниках в городе Санкт-Петербург. Эти данные будут  использованы  для  обучения  модели  анализа  тональности.  Сам  алгоритм  легко настраивается на сбор аналогичных данных о медучреждениях или других организациях, предоставляющих  услуги  населению,  расположенных  в  любом  регионе  страны,  при условии, что информация о них содержится на сайте «Яндекс Карты».Обученная  модель  может  помочь  оценить  удовлетворенность  пациентов  услугами медицинских  учреждений,  которые  в  свою  очередь  принять  во  внимание  выявленные проблемы и предпринять меры по улучшению качества услуг. Более того, модель может использоваться для сравнительного анализа различных медицинских учреждений с целью выявления  лучших  практик  и  определения  областей,  в  которых  могут  быть  внесены улучшения.',
  '_rus')]

In [9]:
df = pd.DataFrame(texts, columns=['names', 'texts', 'years'])

df

,names,texts,years
0,Belkin_IMS_2024_rus,1. Введение По мере стремительного развития...,_rus
1,Bogomolova_IMS_2013_rus,УИС РОССИЯ: эксперимент по реализации онтологи...,_rus
2,Filchenkov_IMS_2014_rus,Компаративный анализ методологических основ за...,_rus
3,Khokhlova_IMS_2017_rus,Сопоставительный анализ статистических мер\nна...,_rus
4,Martynenko_IMS_2018_rus,Методологические проблемы создания Компьютерно...,_rus
5,Masevich_IMS_2016_rus,Методы корпусной лингвистики в исторических\nи...,_rus
6,Mengliev_IMS_2021_rus,Структура и единицы морфоанализатора узбекског...,_rus
7,Perminov_IMS_2019_rus,Интеграция инструментов и сервисов для оценки ...,_rus
8,Rogov_IMS_2020_rus,Применение деревьев решений для анализа сильны...,_rus
9,Salin_IMS_2015_rus,Семантическая сегментация веб-гипертекста на\n...,_rus
10,Tatur_IMS_2023,Выявление скрытых закономерностей в реакции об...,2023
11,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022

Sumy

In [11]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sasha\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [12]:
summarizer = LexRankSummarizer()

In [13]:
abstracts = []

In [14]:
for text in df.texts:
  doc = text
  parser = PlaintextParser.from_string(doc, Tokenizer('russian'))
  summary = summarizer(parser.document, 3)
  abstracts.append([str(sentence) for sentence in summary])

In [15]:
abstracts[:10]

[['Существует  множество  традиционных  и современных  способов  сбора  отзывов,  которые  используются  в  настоящее  время.',
  'Исследователи из Имперского колледжа Лондона собрали комментарии пациентов с сайта NHS Choices за 2008, 2009 и 2011 годы (13802 текста) и применили методы анализа тональности [5].',
  'Эти данные будут  использованы  для  обучения  модели  анализа  тональности.'],
 ['Анализ онтологии как системы организации знаний дан в работе [2].',
  'Были обработаны формы федерального статистического наблюдения за 2008-2011 годы.',
  'Заключение По грантам РГНФ в рамках проекта УИС РОССИЯ разработана основа онтологии предметной области «государственное управление» для содержательной интеграции статистических показателей и аналитических документов.'],
 ['В целях настоящей работы мы выделим два типа протестов, которые условно назовем стихийные и организованные Стихийные протесты (например, события в Бирюлово в 2012 году) отличаются тем, что протест возникает спонтанно как ответ на какой-либо информационный повод (обычно, происшествие), очаг возникновения локализуется вне социальных сетей, которые, хотя и могут выступать инструментом для координации и мобилизации, не играют существенной роли в моменте образования протеста.',
  'Результаты: больше всего свидетельств с пользу репрезентативности выделено для организованных протестов, для стихийных протестов нет релевантной информации, а для выборов заведомо известно, что репрезентативность отсутствует.',
  'Именно этот критерий, на наш взгляд, является определяющим для решения задачи предсказания протеста и ее сложности по сравнению с задачей предсказания выборов 6.'],
 ['для',
  '4.1 Мера MI Отличительной особенностью меры MI оказалось то, что по сравнению с другими мерами она выделила наибольшее количество сочетаний с числительными и местоимениями.',
  'Так же в отличие от взаимной информации зафиксировано большое число сочетаний с существительными (23,4% vs 15,7%).'],
 ['Теоретические предпосылки Теоретическими предпосылками создания Антологии являются три источника: теория совокупности выдающегося русского статистика начала ХХ века А. А. Чупрова, статистические представления русского писателя и ученого А. А. Белого о массовом создании словарей русских писателей и системные представления выдающегося представителя русской формальной школы Ю. Н. Тынянова.',
  'После составления списка авторов каталогизируются их произведения.',
  'В основе проекта лежат идеи русской формальной школы и прежде всего системные идеи Ю. Н. Тынянова, обеспечивающие представительность авторов и их произведений на основе объективных формальных критериев.'],
 ['исследования.',
  'Мы',
  'В графиках частотного поведения десяти самых частотных (по НЧСРЛ) существительных русского языка колебания кривых незначительны.'],
 ['Особенности морфологического анализа узбекского языка Моделирование и аранжировка грамматическоих форм узбекского языка.',
  'билан.',
  'Вспомогательные слова, выражающие грамматическое значение, представлены как суффиксом, так и словом.'],
 ['В связи с этим W3C предоставляет список различных инструментов для оценки атрибутов качества [3].',
  'На данный момент их количество уже также превысило сотню, при этом ни один их них не является универсальным, что не упрощает задачу.',
  'Она состоит из следующих элементов: стратегия (Strategy), рамки (Scope), структура (Structure), компоновку (Composition) и поверхность (Surface).'],
 ['Для решения задачи атрибуции текстов хорошо зарекомендовали себя следующие математические методы [12; 13; 14]: нейронные сети, деревья решений, машина опорных векторов (SVG), метод k-средних, метод QSUM, байесовский классификатор, марковские цепи, метод главных компонент, дискриминантный анализ, генетические алгоритмы, статистические критерии (хи-квадрат Пирсона, критерий Стьюдента, Колмогорова-Смирнова) и др. Среди этих методов интеллектуального анализа данных деревья решений выделяются тем, что они просты в понимании и интерпретации, а также не требуют специальной предварительной обработки данных.',
  'Анализ этих фрагментов показывает, что среди неверно классифицированных фрагментов статей, которые принадлежат другим авторам (не Фёдору Михайловичу Достоевскому), есть и те, что расположены в начале или в конце текста, то есть в его сильных позициях.',
  'В тексте «Письмо к редактору», автором которого является Я. П. Полонский, («Время», 1863, № 3, код 13) последние три фрагмента имеют другое распределение.'],
 ['При этом чаще всего веб-документы анализируются как простые текстовые документы, а свойства самого гипертекста не используются, равно как и не используется статистика переходов в нем. Исходя из результатов проведенного анализа исследований в областях кластерного анализа, интеллектуального анализа данных, моделирования гипертекста, веб-аналитики и семантического веба, в данной статье предлагается использование статистики переходов в гипертекстовой структуре и разработка на данной основе моделей и методов семантической кластеризации данной структуры.',
  'В разработке и проектировании веб-сайтов, разработанные модели и методы могут применяться для решения задач реинжиниринга веб-сайта, реализации рекомендательных механизмов, оптимизации логической структуры веб-сайта с учетом поведения пользователей.',
  'Предложен метод семантической кластеризации, в котором статистика переходов используется для определения весов в алгоритмах графовой кластеризации, что позволяет эффективно применять данные методы для семантической кластеризации гипертекста.']]

In [16]:
annotations = []

In [17]:
for abstr in enumerate(abstracts, start=1):
  print(f'Аннотация статьи {abstr[0]}:')
  annotation = str(' '.join(abstr[1]))
  annotations.append(annotation)
  print(annotation, '\n\n')

Аннотация статьи 1:
Существует  множество  традиционных  и современных  способов  сбора  отзывов,  которые  используются  в  настоящее  время. Исследователи из Имперского колледжа Лондона собрали комментарии пациентов с сайта NHS Choices за 2008, 2009 и 2011 годы (13802 текста) и применили методы анализа тональности [5]. Эти данные будут  использованы  для  обучения  модели  анализа  тональности.


Аннотация статьи 2:
Анализ онтологии как системы организации знаний дан в работе [2]. Были обработаны формы федерального статистического наблюдения за 2008-2011 годы. Заключение По грантам РГНФ в рамках проекта УИС РОССИЯ разработана основа онтологии предметной области «государственное управление» для содержательной интеграции статистических показателей и аналитических документов.


Аннотация статьи 3:
В целях настоящей работы мы выделим два типа протестов, которые условно назовем стихийные и организованные Стихийные протесты (например, события в Бирюлово в 2012 году) отличаются тем, что протест возникает спонтанно как ответ на какой-либо информационный повод (обычно, происшествие), очаг возникновения локализуется вне социальных сетей, которые, хотя и могут выступать инструментом для координации и мобилизации, не играют существенной роли в моменте образования протеста. Результаты: больше всего свидетельств с пользу репрезентативности выделено для организованных протестов, для стихийных протестов нет релевантной информации, а для выборов заведомо известно, что репрезентативность отсутствует. Именно этот критерий, на наш взгляд, является определяющим для решения задачи предсказания протеста и ее сложности по сравнению с задачей предсказания выборов 6.


Аннотация статьи 4:
для 4.1 Мера MI Отличительной особенностью меры MI оказалось то, что по сравнению с другими мерами она выделила наибольшее количество сочетаний с числительными и местоимениями. Так же в отличие от взаимной информации зафиксировано большое число сочетаний с существительными (23,4% vs 15,7%).


Аннотация статьи 5:
Теоретические предпосылки Теоретическими предпосылками создания Антологии являются три источника: теория совокупности выдающегося русского статистика начала ХХ века А. А. Чупрова, статистические представления русского писателя и ученого А. А. Белого о массовом создании словарей русских писателей и системные представления выдающегося представителя русской формальной школы Ю. Н. Тынянова. После составления списка авторов каталогизируются их произведения. В основе проекта лежат идеи русской формальной школы и прежде всего системные идеи Ю. Н. Тынянова, обеспечивающие представительность авторов и их произведений на основе объективных формальных критериев.


Аннотация статьи 6:
исследования. Мы В графиках частотного поведения десяти самых частотных (по НЧСРЛ) существительных русского языка колебания кривых незначительны.


Аннотация статьи 7:
Особенности морфологического анализа узбекского языка Моделирование и аранжировка грамматическоих форм узбекского языка. билан. Вспомогательные слова, выражающие грамматическое значение, представлены как суффиксом, так и словом.


Аннотация статьи 8:
В связи с этим W3C предоставляет список различных инструментов для оценки атрибутов качества [3]. На данный момент их количество уже также превысило сотню, при этом ни один их них не является универсальным, что не упрощает задачу. Она состоит из следующих элементов: стратегия (Strategy), рамки (Scope), структура (Structure), компоновку (Composition) и поверхность (Surface).


Аннотация статьи 9:
Для решения задачи атрибуции текстов хорошо зарекомендовали себя следующие математические методы [12; 13; 14]: нейронные сети, деревья решений, машина опорных векторов (SVG), метод k-средних, метод QSUM, байесовский классификатор, марковские цепи, метод главных компонент, дискриминантный анализ, генетические алгоритмы, статистические критерии (хи-квадрат Пирсона, критерий Стьюдента, Колмогорова-Смирнова) и др. Среди этих методов интеллектуального анализа данных деревья решений выделяются тем, что они просты в понимании и интерпретации, а также не требуют специальной предварительной обработки данных. Анализ этих фрагментов показывает, что среди неверно классифицированных фрагментов статей, которые принадлежат другим авторам (не Фёдору Михайловичу Достоевскому), есть и те, что расположены в начале или в конце текста, то есть в его сильных позициях. В тексте «Письмо к редактору», автором которого является Я. П. Полонский, («Время», 1863, № 3, код 13) последние три фрагмента имеют другое распределение.


Аннотация статьи 10:
При этом чаще всего веб-документы анализируются как простые текстовые документы, а свойства самого гипертекста не используются, равно как и не используется статистика переходов в нем. Исходя из результатов проведенного анализа исследований в областях кластерного анализа, интеллектуального анализа данных, моделирования гипертекста, веб-аналитики и семантического веба, в данной статье предлагается использование статистики переходов в гипертекстовой структуре и разработка на данной основе моделей и методов семантической кластеризации данной структуры. В разработке и проектировании веб-сайтов, разработанные модели и методы могут применяться для решения задач реинжиниринга веб-сайта, реализации рекомендательных механизмов, оптимизации логической структуры веб-сайта с учетом поведения пользователей. Предложен метод семантической кластеризации, в котором статистика переходов используется для определения весов в алгоритмах графовой кластеризации, что позволяет эффективно применять данные методы для семантической кластеризации гипертекста.


Аннотация статьи 11:
Сравнение средних значений соответствия оценок запоминаемость и благозвучие, соответствие и понятность, благозвучие и выразительность, соответствие и запоминаемость среди всех сфер, аптек, магазинов продуктов и магазинов одежды 4. Рассмотрим среднее значение соответствия оценок запоминаемости и благозвучия после группировки в сферах «Аптеки», «Санатории» (в которые входят санатории и базы отдыха), и «Взрослые поликлиники». В сфере санаториев также используются синонимы к слову природа – 52 нейминга из 70.


Аннотация статьи 12:
Основная задача LI на основе N-грамм состоит в том, чтобы сгенерировать набор частотных профилей N-грамм для каждого языка, который необходимо идентифицировать. В процессе обучения модели на выборке с уникальными словоформами были извлечены 14262 различных 3-граммы. Извлеченные 3-граммы Количество	Покрытие всех 3-грамм Из якутских словоформ	6552	45% Из русских заимствований	11857	83% Рис. 1.

In [18]:
annots = pd.DataFrame(annotations, columns=['annotations_sumy'])

In [19]:
sumy = pd.concat([df, annots], join='outer', axis=1)
sumy

,names,texts,years,annotations_sumy
0,Belkin_IMS_2024_rus,1. Введение По мере стремительного развития...,_rus,Существует множество традиционных и совреме...
1,Bogomolova_IMS_2013_rus,УИС РОССИЯ: эксперимент по реализации онтологи...,_rus,Анализ онтологии как системы организации знани...
2,Filchenkov_IMS_2014_rus,Компаративный анализ методологических основ за...,_rus,В целях настоящей работы мы выделим два типа п...
3,Khokhlova_IMS_2017_rus,Сопоставительный анализ статистических мер\nна...,_rus,для 4.1 Мера MI Отличительной особенностью мер...
4,Martynenko_IMS_2018_rus,Методологические проблемы создания Компьютерно...,_rus,Теоретические предпосылки Теоретическими предп...
5,Masevich_IMS_2016_rus,Методы корпусной лингвистики в исторических\nи...,_rus,исследования. Мы В графиках частотного поведен...
6,Mengliev_IMS_2021_rus,Структура и единицы морфоанализатора узбекског...,_rus,Особенности морфологического анализа узбекског...
7,Perminov_IMS_2019_rus,Интеграция инструментов и сервисов для оценки ...,_rus,В связи с этим W3C предоставляет список различ...
8,Rogov_IMS_2020_rus,Применение деревьев решений для анализа сильны...,_rus,Для решения задачи атрибуции текстов хорошо за...
9,Salin_IMS_2015_rus,Семантическая сегментация веб-гипертекста на\n...,_rus,При этом чаще всего веб-документы анализируютс...
10,Tatur_IMS_2023,Выявление скрытых закономерностей в реакции об...,2023,Сравнение средних значений соответствия оценок...
11,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022,Основная задача LI на основе N-грамм состоит в...

T5

In [21]:
from transformers import AutoModelForSeq2SeqLM, T5TokenizerFast

In [22]:
import torch
from transformers import AutoTokenizer, AutoModelWithLMHead, T5ForConditionalGeneration

RuT5-base-sum

In [23]:
model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

C:\Users\sasha\anaconda3\envs\py39\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sasha\.cache\huggingface\hub\models--IlyaGusev--rut5_base_sum_gazeta. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/828k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/766 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/977M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/977M [00:00<?, ?B/s]

In [24]:
for i, text in enumerate (df.texts[:10]):
  article_text = text
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  output_ids = model.generate(input_ids=input_ids, no_repeat_ngram_size=4)[0]
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  print(f'Аннотация текста {i+1}:\n {summary}\n\n')

Аннотация текста 1:
 Пользователи интернет-платформы, социальные сети, форумы и т.д. дают возможность оценивать степень удовлетворенности в баллах от 1 до 5, а также выяснить, какие эмоции выражают пользователи.


Аннотация текста 2:
 Российские ученые и исследователи проводят эксперимент по реализации онтологии предметной области «государственное управление» для поиска в базах данных и по аналитическим публикациям.


Аннотация текста 3:
 Задача прогнозирования исходов выборов и протестов по цифровым следам пользователей в социальных сетях является фундаментальной научной задачей политологии. В данной работе будет проведен компаративный анализ методологических основ двух указанных задач, на основе чего будут указаны потенциальные трудности и ограничения, связанные с прогнозированием протестной активности.


Аннотация текста 4:
 Статистические метрики позволяют вычислять силу связанности словосочетаний в текстах. Это позволяет вычислить устойчивость лексических единиц, позволяющих расположить их на шкале.


Аннотация текста 5:
 Компьютерная антология русского рассказа как языковой ресурс для исследования языка и стиля русской художественной прозы в эпоху революционных перемен (первой трети XX века).


Аннотация текста 6:
 Методы корпусной лингвистики в исторических и культурологических исследованиях можно рассматривать как вариант контент-анализа большого массива текстов.


Аннотация текста 7:
 Структура и единицы морфоанализатора узбекского языка можно представить в виде следующей схемы. Основные компоненты МА могут сильно варьироваться в зависимости от языка и от конкретной реализации.


Аннотация текста 8:
 Интеграция инструментов и сервисов для оценки веб-интерфейсов пользователя и выявления юзабилити рисков в Новосибирском государственном техническом университете. В данной работе рассматриваются разновидности пользовательских интерфейсов, которые представляют собой совокупность средств и методов для взаимодействия пользователя с вычислительными устройствами.


Аннотация текста 9:
 В работе «Атрибуция произведений Ф. М. Достоевского» представлены деревьев решений для анализа сильных позиций текста на фоне массива текстов художественной литературы.


Аннотация текста 10:
 Саратовский государственный технический университет им. Ю.А. Гагарина опубликовал исследования в области кластеризации гипертекстовых документов на основе дискретных математических моделей. Для решения этих задач наиболее просто применить методы непосредственного определения ключевых слов и понятий текста.

In [25]:
annotations_t5 = []

for text in df.texts:
  article_text = text
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  output_ids = model.generate(input_ids=input_ids, min_length=50, max_length=250, no_repeat_ngram_size=4)[0]
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  print(f'Аннотация текста:\n {summary}\n\n')
  annotations_t5.append(str(''.join(summary)))

Аннотация текста:
 Пользователи интернет-платформы, социальные сети, форумы и т.д. дают возможность оценивать степень удовлетворенности в баллах от 1 до 5, а также выяснить, какие эмоции выражают пользователи.


Аннотация текста:
 Российские ученые и исследователи проводят эксперимент по реализации онтологии предметной области «государственное управление» для поиска в базах данных и по аналитическим публикациям. Эксперты считают, что такой подход стимулирует научные исследования и повышает эффективность государственного управления.


Аннотация текста:
 Задача прогнозирования исходов выборов и протестов по цифровым следам пользователей в социальных сетях является фундаментальной научной задачей политологии. В данной работе будет проведен компаративный анализ методологических основ двух указанных задач, на основе чего будут указаны потенциальные трудности и ограничения, связанные с прогнозированием протестной активности.


Аннотация текста:
 Статистические метрики позволяют вычислять силу связанности словосочетаний в текстах. Это позволяет вычислить устойчивость лексических единиц, позволяющих расположить их на шкале.


Аннотация текста:
 Компьютерная антология русского рассказа как языковой ресурс для исследования языка и стиля русской художественной прозы в эпоху революционных перемен (первой трети XX века) — одна из самых драматических эпох русской истории.


Аннотация текста:
 Методы корпусной лингвистики в исторических и культурологических исследованиях можно рассматривать как вариант контент-анализа большого массива текстов, используя математический аппарат для интерпретации выявленных числовых закономерностей.


Аннотация текста:
 Структура и единицы морфоанализатора узбекского языка можно представить в виде следующей схемы. Основные компоненты МА могут сильно варьироваться в зависимости от языка и от конкретной реализации.


Аннотация текста:
 Интеграция инструментов и сервисов для оценки веб-интерфейсов пользователя и выявления юзабилити рисков в Новосибирском государственном техническом университете. В данной работе рассматриваются разновидности пользовательских интерфейсов, которые представляют собой совокупность средств и методов для взаимодействия пользователя с вычислительными устройствами.


Аннотация текста:
 В работе «Атрибуция произведений Ф. М. Достоевского» представлены деревьев решений для анализа сильных позиций текста на фоне массива текстов художественной литературы. Это позволит определить, какие особенности воплощаются в произведениях конкретного автора.


Аннотация текста:
 Саратовский государственный технический университет им. Ю.А. Гагарина опубликовал исследования в области кластеризации гипертекстовых документов на основе дискретных математических моделей. Для решения этих задач наиболее просто применить методы непосредственного определения ключевых слов и понятий текста.


Аннотация текста:
 Название бренда является одним из возможных способов привлечения внимания клиента к компании, а также может вызывать ассоциации, чувства и атмосферу. Название является базовым атрибутом маркетинга, который оказывает прямое влияние на возможность выхода торговой марки на рынок и успешность ее продвижения.


Аннотация текста:
 Введение русских заимствований в якутских текстах — одна из основных источников новых терминов и имен собственных в якутском языке. Однако, по мнению авторов, русский язык до сих пор является важным источником новых имен собственных.

In [25]:
annots_t5 = pd.DataFrame(annotations_t5, columns=['annotations_t5'])

In [26]:
full = pd.concat([sumy, annots_t5], join='outer', axis=1)
full

,names,texts,years,annotations_sumy,annotations_t5
0,Adrova_IMS_2013,"Исследование алгоритмов хеширования, используе...",2013,Анализ времени работы стандартных алгоритмов х...,Для решения проблемы хранения пароля пользоват...
1,Balakshina_IMS_2014,Перспективы развития электронного взаимодейств...,2014,Основной целью разработки УФЭБС являлась станд...,Взаимодействие между кредитными организациями ...
2,Erkimbaev_IMS_2015,Онтология предметной области «Наноматериалы\nи...,2015,В качестве альтернативы для нано-объектов можн...,Онтология предметной области «Наноматериалы и ...
3,Godgildieva_IMS_2016,Создание словаря валентностей русского языка\n...,2016,"Более того, Теньер разделил глаголы на группы ...",Создание словаря валентностей русского языка н...
4,Khokhlova_IMS_2017,Сопоставительный анализ статистических мер\nна...,2017,для 4.1 Мера MI Отличительной особенностью мер...,Статистические метрики позволяют вычислять сил...
5,Martynenko_IMS_2018,Методологические проблемы создания Компьютерно...,2018,Теоретические предпосылки Теоретическими предп...,Компьютерная антология русского рассказа как я...
6,Perminov_IMS_2019,Интеграция инструментов и сервисов для оценки ...,2019,В связи с этим W3C предоставляет список различ...,Интеграция инструментов и сервисов для оценки ...
7,Sokolova_IMS_2020,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...,Корпусы с дискурсивной разметкой текста станов...
8,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022,Основная задача LI на основе N-грамм состоит в...,Введение русских заимствований в якутских текс...
9,Vybornaya_IMS_2024,1. ВведениеДанная статья основана на результат...,2024,"При этом как каузатив, так и квалификатив ...",Предлоги и предложные конструкции могут быть п...

In [27]:
full.to_csv('summarization.csv')