## Суммаризация
1. Вид семантичской свертки, другие виды
2. Виды суммаризации. 
3. Подходы.(TextRank TF-IDF + ранжирование предложений, Глуюокие модели)
4. Связность

In [ ]:
!pip install --upgrade pip
!pip install sumy
!pip install transformers sentencepiece

In [42]:
import os
import re

path = "IMS_extracted"
texts = []

for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith('_rus.txt') and 'Abstract' not in file and 'KW' not in file:
            file_path = os.path.join(root, file)
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    text = f.read()

                    name = file[:-4]  # Без ".txt"
                    
                    # Ищем год в имени файла
                    match = re.search(r'20\d{2}', file)
                    year = match.group(0) if match else 'Unknown'
                    if year not in {'2020', '2021', '2022', '2023', '2024'}:
                        continue

                    texts.append((name, text, year))
            except Exception as e:
                print(f"Ошибка при чтении файла {file_path}: {e}")

In [43]:
texts[:1]

[('Bakhvalov_IMS_2020_rus',
  'Разработка и реализация методов генерации правил \nдля автоматической проверки правописания\nП.Я. Бахвалов\nУниверситет ИТМО\nВведение\nАвтоматическая проверка правописания – это задача автоматического обнаружения и исправления грамматических, стилистических и орфографических ошибок в тексте. Актуальность этой задачи определяется тем, что людям свойственно делать ошибки правописания. Далеко не все хорошо знакомы с правилами грамматики языка или только приступают к их изучению. Помимо этого, существуют болезни, такие как дисграфия, при которых человеку особенно тяжело правильно писать. Задача осложняется за счет таких факторов как неформализованная грамматика, свободный порядок слов в предложении, зависимость слов от контекста, постоянные изменения в языке, диалекты, сленг, жаргон, омонимы и др.\nПодходы к задаче автоматической проверки правописания можно разделить на три типа: основанные на правилах, основанные на методах машинного обучения и гибридные. Подход, основанный на правилах, считается устаревшим, т.к. правила обычно пишут квалифицированные лингвисты, имеет низкую полноту, но более высокую точность. С другой стороны, подходы на основе машинного обучения показывают высокое покрытие ошибок и сейчас являются state-of-the-art. Гибридные же подходы обычно выигрывают, т.к. всегда можно взять за основу подход на машинном обучении и добавить в него правила, для которых взятый подход плохо работает, тем самым увеличивая точность и полноту.\nНесмотря на значительный прогресс в методах решения задачи проверки правописания, основанных на машинном обучении, у подхода, основанного на правилах, остается ряд существенных преимуществ:\n—\tинтерпретируемость правил;\n—\tвозможность редактирования набора правил;\n—\tнизкая потребность в вычислительных ресурсах.\nКвалифицированный специалист всегда может посмотреть на каждое конкретное правило и определить, соответствует ли оно правилу в естественном языке. Пользователь системы также сможет получить информацию о правиле, которое он нарушил. \nВ системе, основанной на правилах, новые правила можно просто добавить в общий список. То же самое относится к ошибкам в правилах: лингвист сможет исправить правило, добавить исключение или выключить его в такой системе, в то время как в системе, основанной на машинном обучении, ошибка будет возникать снова и необходимо полностью переобучать модель.\nСистемы, основанные на машинном обучении, гораздо более требовательны к ресурсам, поэтому их невозможно использовать локально на устройствах пользователя. К сожалению, не все пользователи имеют доступ к безлимитному и бесперебойному интернету для взаимодействия с такими системами на выделенных серверах; особые случаи связаны с работой с конфиденциальной информацией, где недопустима отправка данных по сети, в особенности на сторонний сервер. Модель, которая заняла первое место на последнем соревновании по автоматическому исправлению ошибок (BEA-2019) [1], занимает 3.7Гб в сжатом виде, в то время как системы, основанные на правилах, занимают всего десятки мегабайт.\nОсновной сложностью систем, основанной на правилах, является то, что правила пишутся вручную квалифицированными лингвистами. Когда количество правил достигает тысяч, становится проблематично отслеживать полноту правил и проверять, покрывает ли каждое правило все случаи, в том числе исключения. Решением этих проблем может быть автоматическая генерация правил. Существует ряд работ в этом направлении. Авторы [2] предлагают подход, основанный на имитации иммунной системы человека, когда ошибки рассматриваются как патогены, а правила как лимфоциты. Существуют подходы, основанные на расстоянии редактирования на уровне слов [3]. Однако ни один из подходов не работает хорошо на всех типах ошибок. Большинство описанных в литературе реализаций инструментов недоступно для публичного использования. К тому же сложно сравнивать результаты разных методов, т.к. в каждой работе используется свой набор данных. \nНа практике системы проверки правописания на основе правил активно используются и развиваются в настоящее время. Одной из таких систем является LanguageTool, для которого с 2003 года команда лингвистов пишет правила на основе присылаемых им ошибок [4]. Данная система является бесплатной и имеет открытый исходный код, а также подходит для автономного использования на локальном компьютере, поэтому набор правил данной системы был взят за основу настоящей работы и сгенерированные правила в итоге будут адаптированы под неё.\nВ настоящей работе был выбран английский язык, т.к. он является основным языком научных коммуникаций и технической документации.\nАвторы обзора систем автоматической проверки грамматики предлагают следующую классификацию типов ошибок [5]: грамматика, пунктуация, структура предложения, орфография, семантика.\nВ данной работе будут рассматриваться только ошибки грамматики, пунктуации и ошибки в структуре предложения. Исправление орфографических ошибок хорошо разработанная область, точность исправления таких ошибок уже достигает 91% [6]. Категория семантики, с другой стороны, слишком сложна, и предложения с такими ошибками имеют правильную грамматическую структуру. Для определения такой ошибки часто требуется учитывать контекст нескольких предложений, а иногда и целого текста. Как исключение, есть редкая подкатегория ошибок, когда люди используют похожее по смыслу слово, но которое недопустимо в контексте данного словосочетания. Например: «This is a durable (strong) drink». Но такие ошибки исправляются по словарю подобных словосочетаний и не входят в тематику настоящей работы. Поэтому задача генерации правил для ошибок из категории семантики не имеет смысла.\n1. Обзор существующих методов\nИсследования по автоматическому исправлению правописания ведутся с 60-х годов 20 века. Уже тогда были попытки решения задачи с использованием обычного словаря, n-граммной модели, и языковых моделей [7]. Новый импульс исследованиям придали открытые соревнования, которые проводятся с 2011 года. Первым в своем роде соревнованием является HOO-2011, который предоставил первый общий набор данных для работы с ошибками правописания в открытый доступ, а также общую систему оценивания работ [8]. Потом был CoNLL-2014 [9] и последний из таких контестов BEA-2019, набор данных и система проверки которого были использованы в настоящей работе для проверки качества полученных результатов [1].\nВ 2011 году подход на основе байесовских классификаторов для исправления ошибок в артиклях, предлогах и некорректном выборе слов продемонстрировал превосходство над подходами, основанными на правилах [10]. В 2014 году лучшие результаты показали подходы, основанные на статистическом машинном переводе [11]. Далее стали появляться подходы, основанные на использовании языковых моделей [12; 13]. Позже для решения задачи исправления ошибок в тексте стали использоваться более сложные модели машинного обучения, например, трансформеры [14; 15]. Лучшим подходом на текущий момент на данных BEA-2019 является система, представляющая собой ансамбль моделей других участников соревнования [16].\n2. Подготовка данных для экспериментов\n2.1. Исходные данные\nВ качестве набора данных были использованы данные, предоставленные соревнованием BEA-2019, оно состоит из двух частей. Первая часть – данные с онлайн-платформы Write & Improve [17], которая предлагает помощь при написании текстов людям, для которых английский язык не является родным. Вторая часть набора данных – The LOCNESS corpus [18] – сборник сочинений студентов-носителей английского языка, размеченный сотрудниками Write & Improve. \nОбщий объем данных – примерно 40000 предложений с ошибками и их исправлениями, сделанными одновременно и носителями, и не носителями языка [1]. Пример из набора данных представлен на рисунке 1.\n2.2. Разделение по категориям ошибок\nНа начальном этапе необходимо было разделить данные на группы по типам ошибок. Для данной задачи был использован инструмент для аннотации грамматических ошибок ERRANT [19]. В результате все ошибки были поделены по типам и по категориям (см. табл. 1 и 2).\nВсего получилось 54 категории ошибок – прямое произведение типов и категорий за исключением тех, что не встречаются в исходных данных. Примеры из каждой категории были сгруппированы, причем ошибки, не относящиеся к данной категории, были исправлены, чтобы избежать их влияния на генерацию правил. Тем самым мы предполагаем, что в категории ошибок нет ни одной другой ошибки кроме как из данной категории.\n2.3. Выделение признаков\nПосле разделения данных по ошибкам из слов и предложения были выделены признаки (см. табл. 3) в качестве основы для генерации правил. \nПример размеченного предложения представлен на рисунке 2. \nДля выделения признаков был использована библиотека StanfordNLP [20].\n3. Генерация правил\n3.1. Представление правила\nПроцесс проверки правописания выглядит следующим образом: предложение разбивается на токены, в нем выделяются признаки, описанные выше, после чего начинается итерирование по каждому токену. Токен подается в правило, как базовый элемент, от которого правило будет отталкиваться. В общем случае правило состоит из двух компонент: детектор и редактор. Детектор – это набор условий, которые должны быть выполнены в случае наличия ошибки. Условие – это тип признака вместе с ожидаемым его значением, либо логическая комбинация из других условий, а также смещение относительно проверяемого токена. Редактор – это набор изменений, которые должны произойти с предложением. Изменение состоит из:\n—\tсмещения относительно проверяемого токена;\n—\tсписка новых токенов, которые необходимо вставить перед изменяемым токеном;\n—\tсписка модификаций над изменяемым токеном (изменение регистра слова, изменение части речи слова, полная замена);\n—\tфлага о необходимости удаления токена.\nДанный формат удобен для генерации правил в отличие от формата, принятого в LanguageTool. В нем правило выглядит похожим образом, поэтому трансляция из одного формата в другой при необходимости не вызывает сложностей (см. рис. 3). \n<pattern> – это сгенерированное правило, внутри которого <token> является словом, на которое надо реагировать, в параметрах которого можно задавать признаки. <marker> отвечает за то, что будет являться ошибкой для пользователя и что нужно подчеркнуть. <example> – пример, берется из тестового набора данных. <suggestion> – это то, на что надо исправить <marker>, генерируется из редактора, внутри него можно использовать преобразования частей речи и обращаться к токенам в правиле по индексам. В итоге лингвисту остается только проверить осмысленность правила и придумать ему описание, хотя его тоже можно сгенерировать автоматически.\n3.2. Transformation-Based Learning\nВ качестве метода генерации правил было использовано обучение на основе трансформаций [21]. Этот метод использовался, например, для генерации правил морфологической разметки. Процесс генерации правил выглядит следующим образом. На вход подается набор данных с ошибками и их исправлениями. По каждой ошибке генерируется правило для её детектирования согласно шаблону из заданного списка. К детектору добавляется редактор, который будет исправлять ошибку, т.е. набор изменений, которые необходимо сделать для исправления. На данном этапе мы получили список правил-кандидатов. \nТеперь будем итерироваться по каждому кандидату и применять его ко всему набору данных, считая метрику качества. На каждой итерации выбираем лучшее правило по заданной метрике и применяем его ко всему набору данных. Повторяем, пока остаются ошибки, или результат не станет удовлетворительным (см. рис. 4).\nЭтот метод очень хорошо себя показал во многих областях обработки естественного языка [21]. Однако для применения метода к задаче исправления ошибок в тексте есть несколько препятствий:\n—\tнеясно, откуда брать список шаблонов для правил;\n—\tподсчет метрики каждый раз для каждого правила занимает много времени;\n—\tметрика плохо подходит для нашей задачи;\n—\tнеясно, какое правило считать лучшим на итерации.\nПотенциально правилом может являться любая комбинация из признаков, а количество шаблонов очень быстро растет с ростом количества признаков и токенов. Если пересчитывать метрику каждый раз, то уже на 1000 правилах время выполнения будет достигать нескольких дней на персональном компьютере.\nЕсли правило имеет большое количество одновременно ложных и корректных срабатываний, оно будет более приоритетным, в то время как более-менее продуктивное правило без ложных срабатываний будет выбрано гораздо позже или не выбрано вовсе. Помимо этого, возможна ситуация, когда два менее общих правила, которые будут покрывать то же множество ошибок, будут работать лучше и давать меньше ложных срабатываний. Применение более общего правила на более раннем этапе не позволит генерировать более специфичные правила позже.\nМетод был взят за основу и модифицирован с учетом выявленных недостатков.\n3.3. Предложенный метод\nЗа основу была взята часть корпуса Гутенберга [22] размером в ~2 млн слов, без грамматических и прочих ошибок. Данные были разбиты на токены, выделены признаки. После чего был построен граф возможных последовательностей признаков длиной в три токена (далее тройка). На основе такой структуры можно быстро находить количество троек по заданному набору условий для трех подряд идущих токенов. Такие же графы были сгенерированы для всего набора данных и для троек, включающих ошибку из набора данных.\nДля каждой ошибки в наборе генерируется каждая возможная тройка условий (порядка 250 тысяч на ошибку). Далее, тройки, которые часто (более 1% от всех троек) встречаются в «чистом» графе, а также тройки, которые реагируют на слишком малое количество (менее четырех) ошибок отфильтровываются, после чего выбирается первая тысяча лучших троек. После этого для каждой отфильтрованной тройки на основе графа из набора данных собираются индексы слов, на которые данная тройка будет реагировать, и рассчитывается количество правильных и ложных срабатываний. В итоге остаются только те тройки, которые могут исправить более 3 ошибок и имеют менее 1000 ложных срабатываний.\nДля каждой тройки с индексами генерируются условия для четвертого и пятого токена, получая тем самым наборы пятерок. Для каждой пятерки заново рассчитываются правильные и ложные срабатывания: при добавлении новых условий, количество срабатываний может только лишь уменьшится, следовательно, достаточно проверить только те срабатывания правила, которые уже нашлись для базовой тройки. Выбирается лучшая пятерка по заданной метрике для каждой ошибки. Если она имеет точность больше 80% и исправляет не меньше трех ошибок, то такая пятерка считается хорошей и из нее генерируется детектор.\nВместе с детектором единственно возможным образом из изначальной ошибки генерируется редактор. Из детектора и редактора получается правило-кандидат.\nПосле прохождения по всем ошибкам и получения набора кандидатов в правила, дублирующие правила отфильтровываются. Каждый раз выбирается лучшее правило из набора и считается качественным, после чего выбранное правило применяется к набору данных. Затем выполняется перерасчет метрики для всех остальных правил из набора кандидатов и процесс повторяется до тех пор, пока очередное правило не перестанет удовлетворять заданной метрике.\nПодробный процесс генерации правил показан на рисунке 5.\nВ качестве результата работы можно рассмотреть следующие правила (см. рис. 6). В первом примере правило можно сформулировать так: если фраза начинается с предлога in, далее идет любое притяжательное местоимение, за которым следует слово opinion, то после этой фразы следует поставить запятую. Во втором примере мы видим, что если встречается слово many являющееся часть связки с существительным, то существительное, к которому оно относится, должно находиться во множественном числе. Третье правило удаляет определенный артикль the во фразе at the school.\n4. Оценка качества\nДля оценки качества была использована F-мера, которая представляет собой гармоническое среднее между точностью и полнотой, она стремится к нулю, если точность или полнота стремятся к нулю. Стоит отметить, что при работе с правилами, большее значение придается точности, чем на полноте, потому что важнее правильно исправить ошибку, чем покрыть большее количество ошибок. В таких случаях F-мера может быть модифицирована с учетом необходимого приоритета. В настоящей работе приоритет точности считается в два раза выше приоритета полноты, такую меру принято называть F0.5 (см. рис. 7).\n4.1. Результаты генерации правил по категориям\nДля части категорий с помощью разработанного метода были сгенерированы правила. Другая часть была исключена. Например, категории опечаток, орфографии, морфологии были исключены т.к. не рассматриваются в данной работе. Категории сокращений, преобразования существительного и глагола, формы прилагательного, были исключены ввиду слишком малого количества ошибок для обучения. Также была исключена категория “остальное”, потому что содержит в себе слишком разнородный набор ошибок. Для остальных категорий результаты представлены в табл. 4.\nПосле генерации правила были проверены на третьей части набора данных, которая не использовалась при генерации и показала следующие результаты (см. табл. 5):\n4.2. Качество правил для LanguageTool\nLanguageTool был запущен на данных для обучения, после чего правила, у которых было слишком много ложных срабатываний, были выключены. После чего к исходным правилам были добавлены правила, полученные с использованием предложенного подхода (см. табл. 6).\nВыводы\nС помощью предложенного метода удалось сгенерировать 1238 правил для 36 категорий. Качественнее всего правила получились для категорий пунктуации, формы глагола, согласования глагола с существительным и фразовых глаголах. Для категорий, в основном связанных с заменой частей речи, не удалось сгенерировать качественных и общих правил, т.к. ошибки в них сильнее зависят от контекста предложения, чем от ближайших 5 токенов к ошибке. Результаты на дополнительных данных это подтверждают, категория наречий оказалась впереди лишь по причине слишком малого количества ошибок этого типа в выборке.\nПредложенный метод дает определенный прирост в качестве, полученные правила существенно расширили те 3203 правила, которые уже присутствуют в LanguageTool и увеличили количество найденных ошибок. \nВ дальнейшем планируется рассмотреть возможность генерации правил не для подряд идущих токенов в предложении, а для токенов, связанных через граф зависимостей, полученный после синтаксического анализа. \nЭто позволит сильнее учитывать контекст в рамках одного предложения и генерировать более общие правила для связок существительных с глаголом без учета лишних слов между ними.\n',
  '2020')]

In [44]:
df = pd.DataFrame(texts, columns=['names', 'texts', 'years'])

df

,names,texts,years
0,Bakhvalov_IMS_2020_rus,Разработка и реализация методов генерации прав...,2020
1,Grebennikov_IMS_2020_rus,Корпус русского рассказа начала XX века. \nПри...,2020
2,Khokhlova_IMS_2020_rus,Методы машинного обучения применительно к зада...,2020
3,Korablinov_IMS_2020_rus,Подготовка набора данных для вопросно-ответног...,2020
4,Kuznetsova_IMS_2020_rus,О возможности использования корпуса NOW в курс...,2020
5,Mikoni_IMS_2020_rus,Три подхода к определению понятий на основе со...,2020
6,Rogov_IMS_2020_rus,Применение деревьев решений для анализа сильны...,2020
7,Sokolova_IMS_2020_rus,К вопросу о формировании набора отношений для ...,2020
8,Antopolskii_IMS_2021_rus,Лингвистические ресурсы:\nевропейский опыт и у...,2021
9,Boyarsky_IMS_2021_rus,Устойчивые словосочетания в роли предлогов\nК....,2021
10,Chizhik_IMS_2021_rus,Использование методов тематического моделирова...,2021
11,Golitsina_IMS_2021_rus,Возможности использования семантического поиск...,2021
12,Maksimov_IMS_2021_rus,Модель механизма документального\nинформационн...,2021
13,Mengliev_IMS_2021_rus,Структура и единицы морфоанализатора узбекског...,2021
14,Mikoni_IMS_2021_rus,Оценивание понятности научных русскоязычных ра...,2021
15,Belkin_IMS_2024_rus,1. Введение По мере стремительного развития...,2024
16,MitrofanovaAdamova_IMS_2024_rus,"1. Введение Проект, представленный в данной ст...",2024
17,MitrofanovaGolubev_IMS_2024_rus,Под тематическим моделированием традиционно...,2024
18,Sukhan_IMS_2024_rus,1. Введение: типы метаинформации в корпусе и н...,2024
19,Vybornaya_IMS_2024_rus,1. ВведениеДанная статья основана на результат...,2024

## Sumy

In [23]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\alena\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
summarizer = LexRankSummarizer() #алгоритм LexRank из библиотеки sumy, основанный на графах

In [45]:
abstracts = []

In [ ]:
for text in df.texts:
  doc = text
  parser = PlaintextParser.from_string(doc, Tokenizer('russian'))
  summary = summarizer(parser.document, 3) #количество предложений в итоговом резюме
  abstracts.append([str(sentence) for sentence in summary]) #список предложений преобразуется в строку

In [47]:
abstracts[:10]

[['Тем самым мы предполагаем, что в категории ошибок нет ни одной другой ошибки кроме как из данной категории.',
  'Процесс генерации правил выглядит следующим образом.',
  'Такие же графы были сгенерированы для всего набора данных и для троек, включающих ошибку из набора данных.'],
 ['Корпус русского рассказа начала XX века.',
  'С этой целью в СПбГУ реализуется проект по созданию Корпуса рассказов русских писателей, охватывающего произведения возможно большего числа литераторов, написанные на русском языке с 1900 по 1930 гг. и опубликованные в периодических изданиях или отдельными брошюрами (подробнее о принципах построения корпуса см. [1, 2]).',
  'Обсуждение В данной статье описываются результаты лингвостатистического анализа частотного словаря, поостренного для выборки объемом 100 рассказов из Корпуса русских рассказов 1900 – 1930-х гг. Исследование затрагивает только первый из рассматриваемых в Корпусе периодов, а именно 1900 – 1913 гг. 100 наиболее частотных знаменательных слов словаря были сопоставлены с данными полученных авторами ранее частотных словарей рассказов отдельных выдающихся русских писателей, а также с материалами частотного словаря русского языка в целом.'],
 ['Обзор методов Традиционные методы извлечения лексических конструкций используют лексико-грамматические шаблоны для поиска возможных примеров, которые затем ранжируются в соответствии с одной из статистических мер, отражающих степень связи между двумя признаками.',
  'Нами были использованы простые векторные операции к векторными представлениям слова, чтобы найти семантические аналогии, как это описано в работе [15].',
  'Стоит подчеркнуть, что оценивались именно точность и полнота полученного списка коллокаций, а не их ранжирование (поскольку золотой стандарт не был отранжирован).'],
 ['Подготовка набора данных для вопросно-ответного поиска по базе знаний.',
  'Список полученных таким образом фрагментов мы будем называть ngrams.',
  'Оценка результатов работы алгоритма Для того, что оценить качество работы разработанного алгоритма, мы с его помощью сгенерировали списки сущностей-кандидатов для 14,435 пар “вопрос-ответ”.'],
 ['Для проверки частотности из off-list списка были отобраны десять терминов, состоящих из одного слова, 4 выражения, содержащих два слова, и один термин из трех слов.',
  'Студентам было предложено проверить, какие предлоги употребляются в выражениях типичных для резюме или сопроводительного письма при поиске работы по специальности (инженер-биотехнолог): apply for the position; working under the pressure; was in charge for; creating chemicals from renewable biomass, etc.',
  'В статье описаны упражнения, разработанные на основе подходов корпусной лингвистики для применения в курсе английского для специальных целей для студентов-биотехнологов, рассчитанные как на прямое обращение к корпусу, так и на работу с раздаточными материалами, подготовленными преподавателем.'],
 ['Переведя все поясняющие слова в именительный падеж, и заключив их в скобки, получим следующую аналитическую формулу определения понятия «менеджмент качества»: Менеджмент качества = (Деятельность (Скоординированная, Руководство (Организация, Качество), Управление (Организация, Качество)).',
  'Но слова руководство и управление являются синонимами определяемого слова, что порождает два порочных круга в определении понятия «менеджмент качества» по отношению к слову «менеджмент».',
  'Одним из видов толкования слов являются определение их смысла через слова с известным смыслом.'],
 ['Для решения задачи атрибуции текстов хорошо зарекомендовали себя следующие математические методы [12; 13; 14]: нейронные сети, деревья решений, машина опорных векторов (SVG), метод k-средних, метод QSUM, байесовский классификатор, марковские цепи, метод главных компонент, дискриминантный анализ, генетические алгоритмы, статистические критерии (хи-квадрат Пирсона, критерий Стьюдента, Колмогорова-Смирнова) и др. Среди этих методов интеллектуального анализа данных деревья решений выделяются тем, что они просты в понимании и интерпретации, а также не требуют специальной предварительной обработки данных.',
  'Анализ этих фрагментов показывает, что среди неверно классифицированных фрагментов статей, которые принадлежат другим авторам (не Фёдору Михайловичу Достоевскому), есть и те, что расположены в начале или в конце текста, то есть в его сильных позициях.',
  'В тексте «Письмо к редактору», автором которого является Я. П. Полонский, («Время», 1863, № 3, код 13) последние три фрагмента имеют другое распределение.'],
 ['Обобщение типов похожих риторических отношений Мы обсудим набор РО, определённый для корпуса Ru-RSTreebank, см. ([17, c.',
  'Если (4b) можно отнести к интерпретации, то (4c) – это оценка.',
  'Это РО Result или Effect и Condition или Othewise.'],
 ['Федеративный поиск.',
  'Инфраструктура знаний.',
  'При этом особое внимание нужно обратить на учет научных результатов в форме открытых научных данных, ориентированных на обмен и повторное использование.'],
 ['В общем случае слова, входящие в состав фразем, могут изменяться, однако в рамках данной работы нас интересуют неизменяемые фраземы, большая часть которых является оборотами, выполняющими функции: \uf02d наречий – в конце концов, время от времени, в свое время; \uf02d предлогов – в зависимости от, в соответствии с, несмотря на; \uf02d вводных оборотов – другими словами, к слову сказать; \uf02d союзов – а также, в том числе и, вместо того чтобы, если бы; \uf02d частиц – все же, как бы, как раз, к тому же, едва не, вроде бы; \uf02d предикативных оборотов – не дай бог, лыка не вяжет.',
  'Два оборота требуют после себя дательного падежа: в угоду, не в пример.',
  'В таблице 3 приведены наиболее часто встречающиеся предложные обороты второй группы.']]

In [50]:
annotations = []

In [51]:
for abstr in enumerate(abstracts, start=1):
  print(f'Аннотация статьи {abstr[0]}:')
  annotation = str(' '.join(abstr[1]))
  annotations.append(annotation)
  print(annotation, '\n\n')

Аннотация статьи 1:
Тем самым мы предполагаем, что в категории ошибок нет ни одной другой ошибки кроме как из данной категории. Процесс генерации правил выглядит следующим образом. Такие же графы были сгенерированы для всего набора данных и для троек, включающих ошибку из набора данных.


Аннотация статьи 2:
Корпус русского рассказа начала XX века. С этой целью в СПбГУ реализуется проект по созданию Корпуса рассказов русских писателей, охватывающего произведения возможно большего числа литераторов, написанные на русском языке с 1900 по 1930 гг. и опубликованные в периодических изданиях или отдельными брошюрами (подробнее о принципах построения корпуса см. [1, 2]). Обсуждение В данной статье описываются результаты лингвостатистического анализа частотного словаря, поостренного для выборки объемом 100 рассказов из Корпуса русских рассказов 1900 – 1930-х гг. Исследование затрагивает только первый из рассматриваемых в Корпусе периодов, а именно 1900 – 1913 гг. 100 наиболее частотных знаменательных слов словаря были сопоставлены с данными полученных авторами ранее частотных словарей рассказов отдельных выдающихся русских писателей, а также с материалами частотного словаря русского языка в целом.


Аннотация статьи 3:
Обзор методов Традиционные методы извлечения лексических конструкций используют лексико-грамматические шаблоны для поиска возможных примеров, которые затем ранжируются в соответствии с одной из статистических мер, отражающих степень связи между двумя признаками. Нами были использованы простые векторные операции к векторными представлениям слова, чтобы найти семантические аналогии, как это описано в работе [15]. Стоит подчеркнуть, что оценивались именно точность и полнота полученного списка коллокаций, а не их ранжирование (поскольку золотой стандарт не был отранжирован).


Аннотация статьи 4:
Подготовка набора данных для вопросно-ответного поиска по базе знаний. Список полученных таким образом фрагментов мы будем называть ngrams. Оценка результатов работы алгоритма Для того, что оценить качество работы разработанного алгоритма, мы с его помощью сгенерировали списки сущностей-кандидатов для 14,435 пар “вопрос-ответ”.


Аннотация статьи 5:
Для проверки частотности из off-list списка были отобраны десять терминов, состоящих из одного слова, 4 выражения, содержащих два слова, и один термин из трех слов. Студентам было предложено проверить, какие предлоги употребляются в выражениях типичных для резюме или сопроводительного письма при поиске работы по специальности (инженер-биотехнолог): apply for the position; working under the pressure; was in charge for; creating chemicals from renewable biomass, etc. В статье описаны упражнения, разработанные на основе подходов корпусной лингвистики для применения в курсе английского для специальных целей для студентов-биотехнологов, рассчитанные как на прямое обращение к корпусу, так и на работу с раздаточными материалами, подготовленными преподавателем.


Аннотация статьи 6:
Переведя все поясняющие слова в именительный падеж, и заключив их в скобки, получим следующую аналитическую формулу определения понятия «менеджмент качества»: Менеджмент качества = (Деятельность (Скоординированная, Руководство (Организация, Качество), Управление (Организация, Качество)). Но слова руководство и управление являются синонимами определяемого слова, что порождает два порочных круга в определении понятия «менеджмент качества» по отношению к слову «менеджмент». Одним из видов толкования слов являются определение их смысла через слова с известным смыслом.


Аннотация статьи 7:
Для решения задачи атрибуции текстов хорошо зарекомендовали себя следующие математические методы [12; 13; 14]: нейронные сети, деревья решений, машина опорных векторов (SVG), метод k-средних, метод QSUM, байесовский классификатор, марковские цепи, метод главных компонент, дискриминантный анализ, генетические алгоритмы, статистические критерии (хи-квадрат Пирсона, критерий Стьюдента, Колмогорова-Смирнова) и др. Среди этих методов интеллектуального анализа данных деревья решений выделяются тем, что они просты в понимании и интерпретации, а также не требуют специальной предварительной обработки данных. Анализ этих фрагментов показывает, что среди неверно классифицированных фрагментов статей, которые принадлежат другим авторам (не Фёдору Михайловичу Достоевскому), есть и те, что расположены в начале или в конце текста, то есть в его сильных позициях. В тексте «Письмо к редактору», автором которого является Я. П. Полонский, («Время», 1863, № 3, код 13) последние три фрагмента имеют другое распределение.


Аннотация статьи 8:
Обобщение типов похожих риторических отношений Мы обсудим набор РО, определённый для корпуса Ru-RSTreebank, см. ([17, c. Если (4b) можно отнести к интерпретации, то (4c) – это оценка. Это РО Result или Effect и Condition или Othewise.


Аннотация статьи 9:
Федеративный поиск. Инфраструктура знаний. При этом особое внимание нужно обратить на учет научных результатов в форме открытых научных данных, ориентированных на обмен и повторное использование.


Аннотация статьи 10:
В общем случае слова, входящие в состав фразем, могут изменяться, однако в рамках данной работы нас интересуют неизменяемые фраземы, большая часть которых является оборотами, выполняющими функции:  наречий – в конце концов, время от времени, в свое время;  предлогов – в зависимости от, в соответствии с, несмотря на;  вводных оборотов – другими словами, к слову сказать;  союзов – а также, в том числе и, вместо того чтобы, если бы;  частиц – все же, как бы, как раз, к тому же, едва не, вроде бы;  предикативных оборотов – не дай бог, лыка не вяжет. Два оборота требуют после себя дательного падежа: в угоду, не в пример. В таблице 3 приведены наиболее часто встречающиеся предложные обороты второй группы.


Аннотация статьи 11:
Таким образом, тематическое моделирование очень похоже на проблему кластеризации данных. Каждая из n строк этой матрицы представляет собой документ, а каждый из первых k столбцов соответствует теме. Поэтому документы рассматриваются как распределения вероятностей по скрытым темам, а эти темы - как распределения вероятностей по словам.


Аннотация статьи 12:
Методика формирования элементарного факта Отображение смысла документа на множество элементарных фактов, формирующих узлы и дуги графа функциональной системы онтологии, происходит в соответствии с классической схемой семантического анализа текстов, которая традиционно включает этапы графематического, морфологического, семантико-синтаксического и концептуального анализа [5]. Рассмотрим, например, задачу поиска определений понятий в отдельном тексте или в коллекции текстов. Авторы не ставили задачу сравнить полученные результаты с результатами работ, целенаправленно ориентированных на выявление определений понятий: задачей эксперимента было проверить на практике результаты типизации ситуативных отношений, с одной стороны, а с другой – продемонстрировать возможности семантического поиска в части формирования поискового результата как совокупности фрагментов документов, отвечающих поисковой потребности.


Аннотация статьи 13:
Интерактивная визуализация графа онтологии и механизмы поиска на графах, такие как «поиск пути» и «анализ семантической окрестности», обеспечивают навигацию по текстам документов и понятиям. В основе построения аспектного представления лежит операция проекции, которая в [1] сводится к операции пересечения исходной . Граф онтологии документа позволяет представить документ в форме, обеспечивающей навигацию по документу.


Аннотация статьи 14:
Особенности морфологического анализа узбекского языка Моделирование и аранжировка грамматическоих форм узбекского языка. билан. Вспомогательные слова, выражающие грамматическое значение, представлены как суффиксом, так и словом.


Аннотация статьи 15:
Применительно к онтологическим моделям она была рассмотрена в работе [9]. Примером частично нейтрального термина является «проактивное управление». Таким образом, в отсутствие в наименовании понятия отсылки к образу или к родственному слову прибегают к выяснению смысла из его определения.


Аннотация статьи 16:
Существует  множество  традиционных  и современных  способов  сбора  отзывов,  которые  используются  в  настоящее  время. Исследователи из Имперского колледжа Лондона собрали комментарии пациентов с сайта NHS Choices за 2008, 2009 и 2011 годы (13802 текста) и применили методы анализа тональности [5]. Эти данные будут  использованы  для  обучения  модели  анализа  тональности.


Аннотация статьи 17:
В  данной  статье  рассматриваются  следующие решенные нами задачи:₋формирование корпуса статей по корпусной лингвистике;₋типы информации, представленные в корпусе;₋разметка ключевых выражений в корпусе;₋генерация аннотаций статей;₋систематизация и разметка именованных сущностей. Состав и структура корпуса текстов ТКиКЛПроцедура формирования корпуса ТКиКЛ на основе материалов конференций Corpora и  IMS  CompLing  была  комплексной,  соответствовала  протоколу,  описанному  в  [4], и включала в себя несколько этапов. Структура  корпуса  включает  три  каталога:  Corpora,  IMS,  full_corpus.


Аннотация статьи 18:
В статье представлены результаты построения тематических моделей корпуса ТКиКЛ с помощью  алгоритмов  NMF,  LSA,  LDA  и  Biterm. Результаты тематического моделирования корпуса ТКиКЛ2.1. Результаты генерации меток тем в корпусе ТКиКЛ3.1.


Аннотация статьи 19:
В редакторе отсутствует возможность выбора размера вершин и ребер, недоступны автоматическая  кластеризация  и  укладка  графа. Наконец, ресурс не позволяет изменять цвет, размер или вид вершин и ребер графа. Кроме  того, в доступном формате демонстрируются базовые кластеры элементов метаданных корпуса, что  дает  дополнительную  статистическую  информацию  для  любого  исследования.


Аннотация статьи 20:
При  этом  как  каузатив,  так и квалификатив  для  предлога  «по»  обнаруживают  одинаковую  частотность:  на  каждую из синтаксем приходится примерно по 100 контекстов.2.1.5. Предлог «с» Предлог «с» представлен в базе данных 768 контекстами и, как и первый по частотности предлог  «в»,  охватывает  13  синтаксем  (рис.  5). Нельзя не заметить, что в случае с предлогом «между» все контексты размечаются однозначно, мы не  наблюдаем  двух  семантических  меток  (тематив  и  объект)  у  конструкций  с  данным предлогом.

In [52]:
annots = pd.DataFrame(annotations, columns=['annotations_sumy'])

In [53]:
sumy = pd.concat([df, annots], join='outer', axis=1)

In [54]:
sumy

,names,texts,years,annotations_sumy
0,Bakhvalov_IMS_2020_rus,Разработка и реализация методов генерации прав...,2020,"Тем самым мы предполагаем, что в категории оши..."
1,Grebennikov_IMS_2020_rus,Корпус русского рассказа начала XX века. \nПри...,2020,Корпус русского рассказа начала XX века. С это...
2,Khokhlova_IMS_2020_rus,Методы машинного обучения применительно к зада...,2020,Обзор методов Традиционные методы извлечения л...
3,Korablinov_IMS_2020_rus,Подготовка набора данных для вопросно-ответног...,2020,Подготовка набора данных для вопросно-ответног...
4,Kuznetsova_IMS_2020_rus,О возможности использования корпуса NOW в курс...,2020,Для проверки частотности из off-list списка бы...
5,Mikoni_IMS_2020_rus,Три подхода к определению понятий на основе со...,2020,Переведя все поясняющие слова в именительный п...
6,Rogov_IMS_2020_rus,Применение деревьев решений для анализа сильны...,2020,Для решения задачи атрибуции текстов хорошо за...
7,Sokolova_IMS_2020_rus,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...
8,Antopolskii_IMS_2021_rus,Лингвистические ресурсы:\nевропейский опыт и у...,2021,Федеративный поиск. Инфраструктура знаний. При...
9,Boyarsky_IMS_2021_rus,Устойчивые словосочетания в роли предлогов\nК....,2021,"В общем случае слова, входящие в состав фразем..."
10,Chizhik_IMS_2021_rus,Использование методов тематического моделирова...,2021,"Таким образом, тематическое моделирование очен..."
11,Golitsina_IMS_2021_rus,Возможности использования семантического поиск...,2021,Методика формирования элементарного факта Отоб...
12,Maksimov_IMS_2021_rus,Модель механизма документального\nинформационн...,2021,Интерактивная визуализация графа онтологии и м...
13,Mengliev_IMS_2021_rus,Структура и единицы морфоанализатора узбекског...,2021,Особенности морфологического анализа узбекског...
14,Mikoni_IMS_2021_rus,Оценивание понятности научных русскоязычных ра...,2021,Применительно к онтологическим моделям она был...
15,Belkin_IMS_2024_rus,1. Введение По мере стремительного развития...,2024,Существует множество традиционных и совреме...
16,MitrofanovaAdamova_IMS_2024_rus,"1. Введение Проект, представленный в данной ст...",2024,В данной статье рассматриваются следующие ...
17,MitrofanovaGolubev_IMS_2024_rus,Под тематическим моделированием традиционно...,2024,В статье представлены результаты построения те...
18,Sukhan_IMS_2024_rus,1. Введение: типы метаинформации в корпусе и н...,2024,В редакторе отсутствует возможность выбора раз...
19,Vybornaya_IMS_2024_rus,1. ВведениеДанная статья основана на результат...,2024,"При этом как каузатив, так и квалификатив ..."

## T5

In [35]:
!pip install transformers

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in c:\users\alena\appdata\roaming\python\python310\site-packages (4.49.0)
Requirement already satisfied: filelock in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\alena\appdata\roaming\python\python310\site-packages (from transformers) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\alena\appdata\roaming\python\python310\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\alena\appdata\roaming\python\python310\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\users\alena\appdata\roaming\python\python310\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\alena\appdata\roaming\python\python310\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\alena\appdata\roaming\python\python310\site-packages (from requests->transformers) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\alena\appdata\roaming\python\python310\site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\alena\appdata\roaming\python\python310\site-packages (from requests->transformers) (2024.8.30)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [36]:
from transformers import AutoModelForSeq2SeqLM, T5TokenizerFast

C:\Users\alena\AppData\Roaming\Python\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [37]:
import torch
from transformers import AutoTokenizer, AutoModelWithLMHead, T5ForConditionalGeneration

## RuT5-base-sum

In [ ]:
model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name) #класс модели T5, предназначенный для задач генерации последовательностей, в том числе суммаризации.

C:\Users\alena\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py:142: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\alena\.cache\huggingface\hub\models--IlyaGusev--rut5_base_sum_gazeta. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [56]:
output_dir = "Summarization"

# Фильтруем только нужные года
years = ['2020', '2021', '2022', '2023', '2024']

# Создаём папки под каждый год
output_dir = "Summarization"
for year in years:
    year_folder = os.path.join(output_dir, f"{year}_annotations")
    os.makedirs(year_folder, exist_ok=True)

In [ ]:
annotations_t5 = []

for text in df.texts:
  article_text = text
  #tokenizer преобразует текст в числовые идентификаторы токенов (input_ids), которые подаются на вход модели.
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"] # возвращает список сгенерированных последовательностей для батча. 
  output_ids = model.generate(input_ids=input_ids, min_length=50, max_length=250, no_repeat_ngram_size=4)[0] #запрещает повторение последовательностей из 4 токенов
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  print(f'Аннотация текста:\n {summary}\n\n')
  annotations_t5.append(str(''.join(summary)))

Аннотация текста:
 Автоматическая проверка правописания – это задача автоматического обнаружения и исправления грамматических ошибок в тексте. Эксперты считают, что эта задача является одной из самых сложных задач для людей, которым свойственно делать ошибки правописания.


Аннотация текста:
 В Санкт-Петербурге создан Корпус рассказов русских писателей, охватывающий произведения возможно большого числа литераторов, написанных на русском языке с 1900 по 1930 гг. и опубликованные в периодических изданиях или отдельных брошюрах.


Аннотация текста:
 Выделение атрибутивных и глагольных коллокаций при помощи моделей машинного обучения на русских коллекциях текстов большого объема стало одним из методов, применяемых при решении лингвистических задач в связи с появлением как больших текстовых данных, так и технических возможностей.


Аннотация текста:
 Введение набора данных для вопросно-ответного поиска по базе знаний. Основная задача – преобразование вопроса на естественном языке в конструкцию некоторого формального языка, например, SPARQL-запрос или терм лямбда-исчисления. Для достижения значительного прогресса в любых задачах, связанных с естественным языком, очень важны наборы данных с высококачественной разметкой.


Аннотация текста:
 О возможности использования корпуса NOW в курсе английского для специальных целей для студентов специальности «Биотехнология» рассказали в Университете ИТМО и Санкт-Петербургском политехническом университете Петра Великого.


Аннотация текста:
 Определение понятий на основе собственных свойств модели С.В. Микони рассматривается с точки зрения системного подхода. В настоящей работе автор рассматривает класс онтологических моделей, к которым применимы собственные свойства модели.


Аннотация текста:
 В работе «Атрибуция произведений Ф. М. Достоевского» представлены деревьев решений для анализа сильных позиций текста на фоне массива текстов художественной литературы. Это позволит определить, какие особенности воплощаются в произведениях конкретного автора.


Аннотация текста:
 Корпусы с дискурсивной разметкой текста становятся все более интересными для исследователей, в том числе и для компьютерной лингвистики. В настоящее время дискурсивная структура часто рассматривается в связи с другими составляющими организации текста, в частности, отношениями кореферентности.


Аннотация текста:
 Европейский опыт и уроки для России: лингвистические ресурсы: европейский опыт, европейские уроки и опыт для России. В Европе создана общеевропейская исследовательская инфраструктура для языковых ресурсов и технологий (CLARIN), которая предлагает доступ к лингвистическим информационным ресурсам и технологиям через единый онлайн-вход.


Аннотация текста:
 На русском языке возникает проблема снятия омонимии различных типов – морфологической, лексической, частеречной и т.д. При этом большинство фразем не обладают омонимией и всегда являются предложными оборотами, выполняющими функции или предлоги.


Аннотация текста:
 Использование методов тематического моделирования для оценки степени влияния СМИ на общественное настроение можно разделить на две основные группы – алгебраические и вероятностные. При этом алгоритм может быть достаточно схож на классическую задачу в области обработки естественного языка.


Аннотация текста:
 Выявление определений понятий в научнотехнических текстах не является новой задачей, а может быть решена посредством использования семантического поискового образа в задаче выявления определений определений.


Аннотация текста:
 Введение механизма документального информационного поиска на графах знаний может быть представлено как задача формирования образа решения из фрагментов релевантных документов, найденных традиционными методами поиска.


Аннотация текста:
 Структура и единицы морфоанализатора узбекского языка можно представить в виде следующей схемы. Основные компоненты МА могут сильно варьироваться в зависимости от языка и от конкретной реализации.


Аннотация текста:
 Оценивание понятности научных русскоязычных работ С.В. Микони является одним из примеров неоднозначного понимания смысла в научных публикациях, опубликованных в Санкт-Петербургском институте информатики и автоматизации РАН.


Аннотация текста:
 Пользователи интернет-платформы, социальные сети, форумы и т.д. дают возможность оценивать степень удовлетворенности в баллах от 1 до 5, а также выяснить, какие эмоции выражают пользователи.


Аннотация текста:
 В Петербургской школе корпусной и компьютерной лингвистики создан комплексный корпусный и терминологический ресурс с возможностью многопараметрического поиска источников. Проект, представленный в данной статье, посвящен памяти основателя и руководителя школы Виктора Захарова, который с 2002 года был главным организатором конференций и семинаров, где обсуждались проблемы создания и применения корпусов текстов.


Аннотация текста:
 Тематический моделирование корпуса текстов ТКиКЛ позволяет определять взаимосвязи тем, документов и слов-тематизаторов, которые могут пересекаться в одном или нескольких темах с некоторой вероятностью. Для оценки качества и интерпретируемости полученных моделей мы использовали алгоритмы Biterm, LSA, LDA и Biterm.


Аннотация текста:
 Корпус статей по корпусной лингвистике, собранный студентами и сотрудниками кафедры математической лингвистики СПбГУ, представляет собой многоуровневую базу данных с несколькими типами сущностей, связанных друг с другом через гиперссылки.


Аннотация текста:
 Предлоги и предложные конструкции могут быть представлены сразу несколькими парами «предлог — падежная форма» и «стоп-слова». В настоящее время исследователи считают, что предлоги представляют собой весьма неоднородную группу с неясными и неструктурированными значениями, а значит, передают четкие семантико-синтаксические отношения между знаменательными словами.

In [58]:
annots_t5 = pd.DataFrame(annotations_t5, columns=['annotations_t5'])

In [59]:
full = pd.concat([sumy, annots_t5], join='outer', axis=1)

In [60]:
full

,names,texts,years,annotations_sumy,annotations_t5
0,Bakhvalov_IMS_2020_rus,Разработка и реализация методов генерации прав...,2020,"Тем самым мы предполагаем, что в категории оши...",Автоматическая проверка правописания – это зад...
1,Grebennikov_IMS_2020_rus,Корпус русского рассказа начала XX века. \nПри...,2020,Корпус русского рассказа начала XX века. С это...,В Санкт-Петербурге создан Корпус рассказов рус...
2,Khokhlova_IMS_2020_rus,Методы машинного обучения применительно к зада...,2020,Обзор методов Традиционные методы извлечения л...,Выделение атрибутивных и глагольных коллокаций...
3,Korablinov_IMS_2020_rus,Подготовка набора данных для вопросно-ответног...,2020,Подготовка набора данных для вопросно-ответног...,Введение набора данных для вопросно-ответного ...
4,Kuznetsova_IMS_2020_rus,О возможности использования корпуса NOW в курс...,2020,Для проверки частотности из off-list списка бы...,О возможности использования корпуса NOW в курс...
5,Mikoni_IMS_2020_rus,Три подхода к определению понятий на основе со...,2020,Переведя все поясняющие слова в именительный п...,Определение понятий на основе собственных свой...
6,Rogov_IMS_2020_rus,Применение деревьев решений для анализа сильны...,2020,Для решения задачи атрибуции текстов хорошо за...,В работе «Атрибуция произведений Ф. М. Достоев...
7,Sokolova_IMS_2020_rus,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...,Корпусы с дискурсивной разметкой текста станов...
8,Antopolskii_IMS_2021_rus,Лингвистические ресурсы:\nевропейский опыт и у...,2021,Федеративный поиск. Инфраструктура знаний. При...,Европейский опыт и уроки для России: лингвисти...
9,Boyarsky_IMS_2021_rus,Устойчивые словосочетания в роли предлогов\nК....,2021,"В общем случае слова, входящие в состав фразем...",На русском языке возникает проблема снятия омо...
10,Chizhik_IMS_2021_rus,Использование методов тематического моделирова...,2021,"Таким образом, тематическое моделирование очен...",Использование методов тематического моделирова...
11,Golitsina_IMS_2021_rus,Возможности использования семантического поиск...,2021,Методика формирования элементарного факта Отоб...,Выявление определений понятий в научнотехничес...
12,Maksimov_IMS_2021_rus,Модель механизма документального\nинформационн...,2021,Интерактивная визуализация графа онтологии и м...,Введение механизма документального информацион...
13,Mengliev_IMS_2021_rus,Структура и единицы морфоанализатора узбекског...,2021,Особенности морфологического анализа узбекског...,Структура и единицы морфоанализатора узбекског...
14,Mikoni_IMS_2021_rus,Оценивание понятности научных русскоязычных ра...,2021,Применительно к онтологическим моделям она был...,Оценивание понятности научных русскоязычных ра...
15,Belkin_IMS_2024_rus,1. Введение По мере стремительного развития...,2024,Существует множество традиционных и совреме...,"Пользователи интернет-платформы, социальные се..."
16,MitrofanovaAdamova_IMS_2024_rus,"1. Введение Проект, представленный в данной ст...",2024,В данной статье рассматриваются следующие ...,В Петербургской школе корпусной и компьютерной...
17,MitrofanovaGolubev_IMS_2024_rus,Под тематическим моделированием традиционно...,2024,В статье представлены результаты построения те...,Тематический моделирование корпуса текстов ТКи...
18,Sukhan_IMS_2024_rus,1. Введение: типы метаинформации в корпусе и н...,2024,В редакторе отсутствует возможность выбора раз...,"Корпус статей по корпусной лингвистике, собран..."
19,Vybornaya_IMS_2024_rus,1. ВведениеДанная статья основана на результат...,2024,"При этом как каузатив, так и квалификатив ...",Предлоги и предложные конструкции могут быть п...

In [61]:
full.to_csv('summarization.csv')

In [62]:
for index, row in full.iterrows():
  year = row['years']
  name = row['names']
  text = row['annotations_t5']
  try:
    with open(f'Summarization/{year}_annotations/{name}_annotation.txt', 'w') as writefile:
      writefile.write(text)
  except:
    pass