В корпусе отсутствовали аннотации для статей 2002, 2004-2006, 2008 и 2011 годов

In [32]:
# Импортируем необходимые библиотеки
from pathlib import Path  # для работы с путями файлов
from PyPDF2 import PdfReader  # для чтения PDF файлов
import os  # для работы с операционной системой

def extract_text_from_pdfs(pdf_folder="arxiv_papers"):
    """
    Функция для извлечения текста из PDF файлов
   
    """
    corpus = []  # создаем пустой список для хранения текстов
    
    # Проходим по всем PDF файлам в указанной папке
    for pdf_file in Path(pdf_folder).glob("*.pdf"):
        try:
            # Создаем объект для чтения PDF
            reader = PdfReader(str(pdf_file))
            # Извлекаем текст из каждой страницы и объединяем их
            text = "\n".join(page.extract_text() for page in reader.pages if page.extract_text())
            corpus.append(text)  # добавляем текст в корпус
        except Exception as e:
            # В случае ошибки выводим сообщение
            print(f"Ошибка в {pdf_file.name}: {e}")
    return corpus

# Вызываем функцию для извлечения текстов
corpus_texts = extract_text_from_pdfs()

In [33]:
texts = []

In [34]:
# Проходим по каждому тексту в корпусе
for text in corpus_texts:
    # Создаем уникальное имя для каждого документа в формате "paper_X"
    name = "paper_" + str(len(texts))
    # Устанавливаем год публикации (в данном случае фиксированный 2025)
    year = "2025"  
    # Добавляем кортеж (имя, текст, год) в список texts
    texts.append((name, text, year))

In [35]:
texts[:1]

[('paper_0',

In [36]:
import pandas as pd

In [37]:
df = pd.DataFrame(texts, columns=['names', 'texts', 'years'])

df

     names                                              texts years
0  paper_0  133\n133\nISSN 2500-4255Всероссийский криминол...  2025
1  paper_1  "Теория и практика современной науки" № 5(71) ...  2025
2  paper_2  НАУЧНАЯ  МЫСЛЬ  КАВКАЗА 2010 127 № 3\nСТРАНИЧК...  2025
3  paper_3  стр. 2 из 6  \nУДК  629 \nК ВОПРОСУ  ПРИМЕНЕНИ...  2025
4  paper_4  90 ЧЕЛОВЕК И ОБРАЗОВАНИЕ.  2019.  № 4 (61)\nОб...  2025
5  paper_5  УДК 339.187  \nЗаборских А.С. , студент  \nПер...  2025
6  paper_6  Vestnik of Tuvan State University  \nIssue 4. ...  2025
7  paper_7  .\nАКИМОВА Алёна Олеговна – аспирант Московско...  2025
8  paper_8  252   \nŋũŭűŵŢŮŹŪũųŷū\nřżźźųűŲŵűŽŷ\nCommed...  2025
9  paper_9  Петербургский исторический журнал № 4 (2015)УД...  2025

## Sumy

In [38]:
pip install sumy

Requirement already satisfied: sumy in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (0.11.0)
Requirement already satisfied: docopt<0.7,>=0.6.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sumy) (0.6.2)
Requirement already satisfied: breadability>=0.1.20 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sumy) (0.1.20)
Requirement already satisfied: requests>=2.7.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sumy) (2.32.3)
Requirement already satisfied: pycountry>=18.2.23 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sumy) (24.6.1)
Requirement already satisfied: nltk>=3.0.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from sumy) (3.9.1)
Requirement already satisfied: chardet in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from breadability>=0.1.20->sumy) (5.2.0)
Requirement already satisfied: lxml>=2.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from breadability>=0.1.20->sumy) (5.3.2)
Requirement already satisfied: click in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.0.2->sumy) (8.1.8)
Requirement already satisfied: joblib in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.0.2->sumy) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.0.2->sumy) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from nltk>=3.0.2->sumy) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.7.0->sumy) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.7.0->sumy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.7.0->sumy) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.7.0->sumy) (2025.4.26)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from click->nltk>=3.0.2->sumy) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [39]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [40]:
summarizer = LexRankSummarizer()

In [41]:
abstracts = []

In [42]:
# Проходим по каждому тексту в датафрейме
for text in df.texts:
  # Сохраняем текст в переменную doc
  doc = text
  # Создаем парсер для русского текста
  parser = PlaintextParser.from_string(doc, Tokenizer('russian'))
  # Генерируем краткое содержание из 3 предложений
  summary = summarizer(parser.document, 3)
  # Добавляем полученные предложения в список abstracts
  abstracts.append([str(sentence) for sentence in summary])

In [43]:
abstracts[:10]

[['— С. 110–114.',
  '— С. 170–174.',
  'Shell B.H., Martin M.V., Hung P.C.K., Rueda L. Cyber Child Pornography: a Review Paper of Social and Legal Issues and Remedies — and a Proposed Technological Solution.'],
 ['Ключевые слова: Единоборства, спорт, спортсмены.',
  'По возрасту борцы делятся на юниоров, взрослых, ветеранов и т. д. Разделение на группы по возрасту важно, так как правила и продолжительность матча различаются.',
  'Именно в этом виде спорта можно овладеть приемами борьбы и самообороны, чтобы в крайнем случае защитить себя.'],
 ['[3, ñ.', 'Ñ.', 'Ñ.'],
 ['Системы  управления  двигателями  в настоящее  время  выпускаются  в различных модификациях .',
  'Системы  управления  двигателем  подразделяются  на системы  управления карбюраторным  (бензиновым ) и дизельным  двигателем  и трансмиссией .',
  'Развитие  экологического  туризма  – один  из возможных  путей  экологического просвещения  населения .'],
 ['Радевская Н.С., Антонова Т .А., Радевский А.В. Организации летнего детского оздоровительного отдыха ...патриотических качеств у молодежи через систему летнего оздоровительного отдыха для детей и подростков на базе ОУ , органи - зацию профильных смен военно-патриоти - ческой направленности.',
  'Поставленные перед школой задачи ста - ли основанием для разработки и принятия программы профильной кадетской смены детского оздоровительного лагеря на базе школы, позволяющей соприкоснуться с историей, культурой и достижениями сво - его Отечества, таким образом, ориенти - рованной на практическое воплощение в жизнь гуманистических ценностей, на фор - мирование у детей и подростков активной гражданской позиции и их социализацию, направленную на пробуждение интереса к истории кадетства в России, уважительное отношение к его историческим ценностям, на патриотическое, нравственное воспита - ние, содержательное общение и межлич - ностные отношения в разновозрастном коллективе.',
  'Радевская Н.С., Антонова Т .А., Радевский А.В. Организации летнего детского оздоровительного отдыха ...довской песни», «Вечер разгаданных и не - разгаданных тайн).'],
 ['Перечислим основные плюсы: \uf0b7 обеспеченность финансирования опера ции в полном объеме; \uf0b7 нет необходимости осуществлять платежи сразу  и иметь всю сумму денег в наличии ; \uf0b7 лизинг является более гибким источником (например, по сравнению с ссудой), так как позволяет субъектам выбрать альтернативный график выплат , который описывается сторонами при заключении договора ; \uf0b7 полученные активы, как правило, не числятся у лизингополучателя на балансе, что освобождает его от уплаты налога на это имущество; \uf0b7 лизинг обеспечивает возможность получения квалифицированного сервисного и техн ического обслуживания и др. К недостаткам же данной операции можно отнести следующее: \uf0b7 конечная стоимость лизинга обычно получается больше, чем покупка оборудования в кредит , то есть лизинг обходится  дороже, чем кредит, что, конечно же, отпугивает клиентов лизинга ; \uf0b7 необходимость внесения аванса; \uf0b7 платежи носят обязательный характер и производятся в установленные сроки независимо от состояния оборудования и результатов хозяйственной деятельности; \uf0b7 сущест вует риск расторжения договора; \uf0b7 юридическая сложность сделки , более тяжелые условия (в отличие от другой финансовой помощи)  и др. [7].',
  'Лизинг в России.',
  '2015, С.  1014 -1021 6.'],
 ['Потому у Н. В. Нечаевой уже на 12 странице «Азбуки» (приблизи тельно на шестом уроке) дети приступают к изучению однозвучных гласных  звуков: Аа, Уу, Оо, Ээ, Ии, ы.  В это же время вводятся такие важные лингвистические понятия, как речь устная и письменная (в темах «История речи», «Речь устная и письменная»), предложен ие, слово, звук, звуки гласные и согласные, буквы (в темах «Знаки звук ов», «Звуки – гласные и согласные», «Знаки звуков – буквы»), твердые и мягкие согласные звуки (в теме «Как буква меняет слово»).',
  '[3, с. 6-7].',
  'Нечаева, Н. В. Обучение грамоте.'],
 ['С. 89.', 'С. 88–105.', 'С. 29–41.'],
 ['252 ŋũŭűŵ\x03ŢŮŹŪũųŷū řżźźųűŲ\x03ŵűŽ\x03ŷ\x03 Commedia dell’Arte ŘŹŷŴŷŬ ŋ\x03mŘŷƆŵŮ\x03ŪŮŰ\x03ŬŮŹŷƈ}\x03ŉŶŶũ\x03ŉžŵũŻŷūũ\x03 ūŷźųŴűſũŮŻ \x03mśƄ\x03ū\x03řŷźźűƇ\x03ŸŹűƁŴũ\x03ŶűŷŻųżŭũ\x0f\x03\x12\x12\x03ŗ\x03ŵŷŮ\x03ŪŮŴŷųżŹŷŮ\x03ƀżŭŷ\x0f\x03\x12\x12\x03œŷŴŷŵŪűŶũ\x03ŭŮźƈŻƄž\x03Ŭŷŭŷū\x04}\x11\x03ŚŻŹŷųű\x03ŸŷźūƈƂŮŶƄ\x03ũųŻŹűźŮ\x03ŗŴƅŬŮ\x03ŌŴŮŪŷūŷŲ\x10ŚżŭŮŲųűŶŷŲ\x0f\x03Ŷŷ\x03ŵŷŬżŻ\x03ŪƄŻƅ\x03ŸŹŷƀűŻũŶƄ\x03ű\x03ŪŮŰ\x03ŪűŷŬŹũŽűƀŮźųŷŬŷ\x03ŸŷŭŻŮųźŻũ\x11\x03ōżŵũƇ\x0f\x03ŉžŵũŻŷūũ\x03ūŹƈŭ\x03Ŵű\x03ŹũźźƀűŻƄūũŴũ\x0f\x03ƀŻŷ\x03ūźƈųűŲ\x03ƀűŻũŻŮŴƅ\x03ŮŮ\x03ŸŷƆŵƄ\x03ŷųũůŮŻźƈ\x03ŰŶũŻŷųŷŵ\x03ŪŷŬŮŵŶŷŲ\x03ųżŴƅŻżŹƄ\x03ŘŮŻŮŹŪżŹŬũ\x03ųũŶżūƁŮŲ\x03ū\x03ŔŮŻż\x03ƆŸŷžű\x11\x03ŘŷƆŻ\x03źŵŷŻŹűŻ\x03Ŷũ\x03\x14 \x14\x16\x03Ŭ\x11\x03űŰ\x03\x14 \x17\x13\x10ž\x03ű\x03ŸŷŹũůũŮŻźƈ\x03ŸŹűźżŻźŻūűƇ\x03Ŷũ\x03ŪŮŹŮŬũž\x03ŖŮūƄ\x03ŵũźŷų\x03űŰ\x03mŋŮŶŮſűű\x03ŭŷůŮŲ}\x11 253Pro memoria:   ŻŮũŻŹũŴƅŶƄŮ\x03űźŻŷŹűű ŗŭŶũųŷ\x0f\x03ŶűƀŻŷ\x03ŶŮ\x03ƈūŴƈŮŻźƈ\x03ŶűŷŻųżŭũ\x0f\x03ŭũůŮ\x03ŸŹűŰŹũųű\x11 ŠżŻƅ\x03ūƄƁŮ\x03Ÿŷ\x03ŻŮųźŻż\x03ŸŷƆŵƄ\x03ŉžŵũŻŷūũ\x03ūźŸŷŵűŶũŮŻ\x03ŮƂŮ\x03ŷŭŶż\x03ŹŮũŴűƇ\x03 žżŭŷůŮźŻūŮŶŶŷŲ\x03ůűŰŶű\x03ŚŮŹŮŪŹƈŶŷŬŷ\x03ūŮųũ \x03mŋűŭűƁƅ\x03Żũŵ\x0f\x03Űũ\x03ūƅƇŬŷŲ\x03 ųŹżŸƀũŻŷŲ\x0f\x03\x12\x12\x03ŕŮŲŮŹžŷŴƅŭŷūƄ\x03ũŹũŸƀũŻũ\x03\x12\x12\x03ŐũŻŮūũƇŻ\x03ŷŸƈŻƅ\x03ūŷŰŶƇ"}\x11 \x03 řűŽŵżƈ\x03źŮūŮŹŶżƇ\x03ŵŮŻŮŴƅ\x03ű\x03ƀŮŹŶŷųŷůűž\x03ŭŮŻŮŲ\x03ŧŬũ\x0f\x03ųŷŻŷŹƄž\x03ũŹűźŻŷ - ųŹũŻűƀŮźųũƈ\x03ŸŹűžŷŻƅ\x03ŸŹŮūŹũŻűŴũ\x03ū\x03ůűūƄŮ\x03űŬŹżƁųű\x0f\x03ũ\x03ŕŮŲŮŹžŷŴƅŭ\x03ū\x03 źūŷűž\x03źſŮŶűƀŮźųűž\x03ųŷŵŸŷŰűſűƈž\x03źŭŮŴũŴ\x03ŰŶũųŷŵ\x03ƆŸŷžű\x03ũŪźŷŴƇŻűŰŵũ\x0f\x03 ŉžŵũŻŷūũ\x03ŷƀŮŶƅ\x03ŻŷƀŶŷ\x03żųũŰƄūũŮŻ\x03źŸŷźŷŪ\x03ŸŹűžŷŭũ\x03ŵũźŷų\x03űŻũŴƅƈŶźųŷŲ \x03 ųŷŵŮŭűű\x03ū\x03ŘŮŻŮŹŪżŹŬ\x11 ŋ\x03ŵŮŲŮŹžŷŴƅŭŷūźųŷŵ\x03mōŷŶ\x03ŏżũŶŮ}\x03 ŉŴŮųźũŶŭŹűŶźųűŲ\x03ŻŮũŻŹ\x0f\x03\x14 \x14\x13 \x03 ũŹũŸƀũŻũ\x03ūŮŴű\x03ŸũŹũŴŴŮŴƅŶƄŲ\x03ŵŷŴƅŮŹŷūźųŷŵż\x03ŹŮůűźźŮŹźųűŲ\x03źƇůŮŻ\x11\x03ŗŶ ű\x03 ŷŻūŮƀũŴű\x03Űũ\x03ŹűŻżũŴ\x03źŸŮųŻũųŴƈ\x0f\x03źŷŰŭũūũŴű\x03ŻŷŹůŮźŻūŮŶŶżƇ\x0f\x03ũ\x03ūŹŮŵŮŶ ũ- ŵű\x03ŸŷŻŮƁŶżƇ\x03 ūŷŰűŴűźƅ\x03ųũų\x03ųŷŻƈŻũbȡ\x03ūźŸŷŵűŶũŴ\x03žżŭŷůŶűų\x03ŉŴŮųźũŶŭŹ \x03 ŌŷŴŷūűŶ\x14 \x03ŭŮŲźŻūŮŶŶżƇ\x03Źũŵż\x03ŸŹŮŭźŻũūŴŮŶűƈ\x03ŸƅŮźƄ\x03ŸŹű\x03ūŮŹźũŴƅźųŷŵ\x03 ŭūŷŹŮ\x11\x03ŉŹũŸƀũŻũ\x03ŰũůűŬũŴű\x03źūŮƀű\x0f\x03ŸŷŭũūũŴű\x03ŬŮŹŷƈŵ\x03ŕŷŴƅŮŹũ\x03ŶŮŷŪžŷ - ŭűŵƄŲ\x03ŹŮųūűŰűŻ\x0f\x03ūƄŻűŹũŴű\x03ŭżƆŴƈŶŻũŵ\x03ŸŷŻ\x03źŷ\x03ŴŪŷū\x03ūŷ\x03ūŹŮŵƈ\x03ŸŷŮŭűŶų ũ\x11\x03 ŋbŷŪƂŮŵbȡ\x03ŷŪŹũŰſŷūŷ\x03űźŸŷŴŶƈŴű\x03ŽżŶųſűű\x03mźŴżŬ\x03ŸŹŷźſŮŶűżŵũ}\x03 ŭŷ - ŪũūŴŮŶŶƄž\x03ŹŮůűźźżŹŷŲ\x03ŸŮŹźŷŶũůŮŲ\x0f\x03ŬŴũūŶŷŲ\x03ƆźŻŮŻűƀŮźųŷŲ\x03ŰũŭũƀŮŲ\x03 ųŷŻŷŹƄž\x03ƈūŴƈŴũźƅ\x03ŶũŬŴƈŭŶũƈ\x03ŭŮŵŷŶźŻŹũſűƈ\x03ŷŻųŹŷūŮŶŶŷ\x03żźŴŷūŶŷŬŷ\x03žũ - ŹũųŻŮŹũ\x03źŸŮųŻũųŴƈ \x11 ŉ\x11\x03śƄƁŴŮŹ\x11\x03ŘŷŹŻŹŮŻ\x03ŉŶŶƄ\x03ŉžŵũŻŷūŷŲ\x11\x03\x14 \x17\x16\x11\x03ŝŹũŬŵŮŶŻ \x15\x18\x17ŋũŭűŵ\x03ŢŮŹŪũųŷū\x03\x03 \x03řżźźųűŲ\x03ŵűŽ\x03ŷ\x03 Commedia dell’Arte ŠŮŹŶŷųŷůűŮ\x03źŴżŬű\x03ŸŷƈūŴƈŴűźƅ\x03ū\x03źſŮŶűƀŮźųűž\x03ųŷŵŸŷŰűſűƈž\x03 ŕŮŲŮŹ\x03žŷŴƅŭũ\x03ű\x03ŶŮŵŶŷŬűŵ\x03ŹũŶŮŮ \x03ū\x03mšũŹŽŮ\x03œŷŴŷŵŪűŶƄ}\x0f\x03ū\x03mŘŷųŴŷŶŮ - Ŷűű\x03ųŹŮźŻż}\x03 ŷŪũbȡ\x03\x14 \x14\x13 \x11\x03ŗŭŶũųŷ\x03ūŸŮŹūƄŮ\x03ƆŻŷ\x03ŭŷŴůŶŷ\x03ŪƄŴŷ\x03źŴżƀűŻ ƅźƈ\x03 ŷźŮŶƅƇ\x03\x14 \x13\x18\x03Ŭ\x11\x0f\x03ū\x03ŸŷźŻũŶŷūųŮ\x03ŸƅŮźƄ\x03ŌŮŹžũŹŭŻũ\x03ŌũżŸŻŵũŶũ\x03mšŴƇų\x03ű\x03 Ũż}\x11\x03 ŎƇbŸŴũŶűŹŷūũŴű\x03ŷŻųŹƄŻƅ\x03ŶŷūƄŲ\x03źűŵūŷŴűźŻźųűŲ\x03ŻŮũŻŹ\x03ū\x03ŕŷźųūŮbȡ\x03ŚŻż - ŭűƇ\x03Ŷũ\x03ŘŷūũŹźųŷŲ\x11\x03ŋŹŮŵƈ\x03ŭŮŲźŻūűƈ\x03mźŹŮŭŶŮūŮųŷūŷŲ}\x03ųŷŵŮŭűű\x03ŌũżŸŻ - ŵũŶũ\x03ŹŮůűźźŮŹƄ\x03 Ŷũŭ\x03źŸŮųŻũųŴŮŵ\x03źŷūŵŮźŻŶŷ\x03ŹũŪŷŻũŴű\x03ŕŮŲŮŹžŷŴƅŭ\x03ű\x03 ŚŻũŶűźŴũūźųűŲ \x03ŹŮƁűŴű\x03ŸŮŹŮŶŮźŻű\x03ū\x03;9,,,\x03źŻŷŴŮŻűŮ\x11\x03ŗŪźżůŭũƈ\x03ūűŰż - ũŴƅŶƄŮ\x03ű\x03źſŮŶűƀŮźųű\x03ūƄŬŷŭŶƄŮ\x03ŰŶũųű\x03ƆŸŷžű\x0f\x03ŸŷźŻũŶŷūƂűųű\x03ūźŸŷŵŶű - Ŵű\x03ŷŪ\x03ũŹũŸƀũŻũž\x03ű\x03ŸŷŸŹŷźűŴű\x03žżŭŷůŶűųũ\x03ŖűųŷŴũƈ\x03ŜŴƅƈŶŷūũ\x03źŹűźŷūũŻ ƅ\x03 ŷŭŶŷŬŷ\x03űŰ\x03Ŷűž\x03ź\x03ųŷŶŶŷŬŷ\x03ŸŷŹŻŹŮŻũ\x03űŵŸŮŹũŻŹűſƄ\x03ŎŴűŰũūŮŻƄ\x03ŘŮŻŹŷūŶƄ \x11\x03 œũŹŻűŶũ\x03ƆųźŸŷŶűŹŷūũŴũźƅ\x03Ŷũ\x03ŰŶũŵŮŶűŻŷŲ\x03ūƄźŻũūųŮ\x03řżźźųűž\x03ŸŷŹŻŹŮ - Żŷū\x0f\x03ŷŹŬũŶűŰŷūũŶŶŷŲ\x03Ś\x11Ř\x11\x03ōƈŬűŴŮūƄŵ\x03ū\x03śũūŹűƀŮźųŷŵ\x03ŭūŷŹſŮ\x11\x03Ŗũ\x03ƆŻŷ ŵ\x03 ŸŷŴŷŻŶŮ\x03ŶŮűŰūŮźŻŶŷŬŷ\x03žżŭŷůŶűųũ\x03 źŮŲƀũź\x03žŹũŶűŻźƈ\x03ū\x03mŦŹŵűŻũůŮ} \x0f\x03 ŶũŸűźũŶŶŷŵ\x03mŸŷ\x03ŵŷŻűūũŵ}\x03ŰŶũŵŮŶűŻŷŲ\x03ųũŹŻűŶƄ\x03Ō\x11Ş\x11\x03ŌŹŷŷŻũ\x0f\x03ūŸŷŴŶŮ\x03 ūŰŹŷźŴƄŲ\x03ũŹũŸ\x03ŪŮůűŻ\x03Ɔŭũųűŵ\x03ƆųŰŷŻűƀŮźųűŵ\x03źųŷŹŷžŷŭŷŵ\x03ŸŮŹŮŭ\x03Ŵŷ\x10 ƁũŭƅƇ\x03ŵŷŶũŹžűŶű\x11 ŚƇůŮŻ\x03ŸŷŴŷŻŶũ\x03ŸŹŷŴűūũŮŻ\x03źūŮŻ\x03Ŷũ\x03űŶŻŮŹŮźżƇƂűŲ\x03Ŷũź\x03ūŷŸŹŷź\x11\x03 Commedia dell’ Arte ŸŷƈūűŴũźƅ\x03Ŷũ\x03ŪŮŹŮŬũž\x03ŖŮūƄ\x03Żũų\x03ůŮ\x0f\x03ųũų\x03ƀŮŹŶŷųŷůűŮ\x03 ŭŮŻű\x0fbȡ\x03Ÿŷ\x03űŵŸŮŹũŻŷŹźųŷŲ\x03ŸŹűžŷŻű\x11 ŉŹũŸƀũŻũ\x11\x03mōŷŶ\x03ŏżũŶ}\x11\x03ŉŴŮųźũŶŭŹűŶźųűŲ\x03ŻŮũŻŹ\x11\x03\x14 \x14\x13 255Pro memoria:   ŻŮũŻŹũŴƅŶƄŮ\x03űźŻŷŹűű',
  'ŘŷųŷŴŮŶűŮ\x0f\x03ŹŷůŭŮŶŶŷŮ\x03ū\x03\x14\x1b\x1a\x13bȡ\x03\x1b\x13\x10Ů\x03ŬŬ\x11\x03ū\x03řŷźźűűbȡ\x03ű\x03ůűŻŮŴű\x03źŻŷŴ űſ\x0f\x03 ű\x03ŸŹŷūűŶſűũŴƄbȡ\x03źŹŮŭű\x03źũŵƄž\x03ŭŷŹŷŬűž\x03ŭŮŻźųűž\x03ūŷźŸŷŵűŶũŶűŲ\x03źŷžŹũ - ŶűŴű\x03ŶũűūŶƄŮ\x03ūŷźŻŷŹŬű\x03ŷŻ\x03mƀżŭŮź}\x03ŪũŴũŬũŶŶƄž\x03ŸũŶŻŷŵűŵ\x11\x03ŉ\x11Ŗ\x11\x03ŊŮŶż ũ\x03 ŸűźũŴ \x03mŘŷŻŹŮŪŶŷźŻű\x03ū\x03ƀŮŵ\x10Żŷ\x03ƀżŭŮźŶŷŵ\x03 ű\x03ŪŴŮźŻƈƂŮŵ\x03ūŸŷŴŶŮ\x03ŷŻūŮŻű - Ŵŷ\x03ŰŹŮŴűƂŮ\x0f\x03ųŷŻŷŹŷŮ\x03ƈ\x03źŸŷŭŷŪűŴźƈ\x03ŻŷŬŭũ\x03żūűŭŮŻƅ\x03ū\x03ŷŭŶŷŵ\x03űŰ\x03ŪŷŴƅƁ űž\x03 ŭŮŹŮūƈŶŶƄž\x03ŻŮũŻŹŷū\x0f\x03ũ\x03űŵŮŶŶŷ\x03ū\x03ŻŮũŻŹŮ\x03ŎŬũŹƉūũ\x0f\x03ū\x03ųŷŻŷŹŷŵ\x03ūźŮ\x03ŮƂ Ů\x0f\x03Ÿŷ\x03 źŻũŹŷŲ\x03ŻŹũŭűſűű\x0f\x03ŭũūũŴűźƅ\x03ũŹŴŮųűŶũŭƄ\x11\x03\x1fȬ!\x03ŋƄŲŭƈ\x03űŰ\x03ƆŻŷŬŷ\x0f\x03ȦŸŮŹū ŷŬŷ\x03 ŵŷŮŬŷ\x03ŻŮũŻŹũȧ\x0f\x03ƈ\x03ŪƄŴ\x03źŴŷūŶŷ\x03żŬŷŹŮŴƄŲ\x0f\x03ũ\x03ŸũŵƈŻƅ\x03ŷŪ\x03ƆŻŷŵ\x03ŸŷźŮƂŮŶű ű\x03ŶŮ\x03 żŻŹũŻűŴũ\x03źūŮůŮźŻű\x03ű\x03źűŴƄ\x03ŭũůŮ\x03ű\x03Ÿŷ\x03źŮŲ\x03ŭŮŶƅ\x11\x03ŦŻŷ\x03ŵŷŮ\x03ŸŮŹūŷŮ\x03ŰŶũ ųŷŵ - źŻūŷ\x03ź\x03ŻŮũŻŹŷŵ\x03ųũų\x10Żŷ\x03ŷŰũŹűŴŷ\x03ŵŮŶƈ\x0f\x03ũ\x03ū\x03ŬŴũūŶŷŮ\x03ŭŮŲźŻūżƇƂŮŮ\x03Ŵűſ ŷ\x0f\x03ū\x03 ŉŹŴŮųűŶũ\x0f\x03ƈ\x03ŸŹŷźŻŷ\x03ūŴƇŪűŴźƈ\x11\x03Ũ\x03żůŮ\x03ŪƄŴ\x03ŰŶũųŷŵ\x03ź\x03ŴűƀŶŷźŻƅƇ\x03ŉŹŴŮų űŶũ\x03 ű\x03ƀżūźŻūŷūũŴ\x03ų\x03ƆŻŷŵż\x03ŵũźųűŹŷūũŶŶŷŵż\x03ŸŷūŮźŮ\x03ųũųżƇ\x10Żŷ\x03ūŷźžűƂŮŶŶżƇ \x03 ŶŮůŶŷźŻƅ\x0f\x03Ŷŷ\x03ŻżŻ\x03ƈ\x03żūűŭũŴ\x03ŮŬŷ\x03ůűūƄŵ\x0f\x03ŭŮŲźŻūżƇƂűŵ\x0f\x03ŸŷŪŮŭŷŶŷźŶƄŵ\x0f \x03 űŰŭŮūũƇƂűŵźƈ\x03Ŷũŭ\x03ūźŮŵű\x0f\x03ųŻŷ\x03źŻũŶŷūűŴźƈ\x03Ůŵż\x03ŸŷŸŮŹŮų\x03ŭŷŹŷŬű\x11\x03ŕŶŮ\x03 ŕũźŴŮŶűſũ\x11\x03Ś\x03ŹűźżŶųũ\x03ŉ\x11\x03ŊũŴƅŭŮŹũ 263Pro memoria:   ŻŮũŻŹũŴƅŶƄŮ\x03űźŻŷŹűű źũŵŷŵż\x03ŰũžŷŻŮŴŷźƅ\x03źŭŮŴũŻƅźƈ\x03ŉŹŴŮųűŶŷŵ\x0f\x03ű\x03ƈ\x03źŮŹƅŮŰŶŷ\x03ŵŮƀŻũŴ\x03ŷ\x03Żŷ ŵ\x0f\x03 ƀŻŷŪƄ\x03ŸŷŴżƀűŻƅ\x03ŻũųżƇ\x03ůŮ\x03ūŷŴƁŮŪŶżƇ\x03ŸũŴŷƀųż\x0f\x03ųũų\x03Żũ\x0f\x03ƀŻŷ\x03ŸŷŭũŹűŴũ \x03 Ůŵż\x03 Űũ\x03ƀŻŷ" \x03ŭŷŪŹũƈ\x03ű\x03ŸŹŮųŹũźŶũƈ\x03ŽŮƈ\x11\x03ŕũŴŷ\x03ŻŷŬŷ\x0f\x03ƈ\x03ŭũůŮ\x03ūŻũŲŶŮ \x03ŷŻ\x03 ŵũŵƄ\x03ŵŷŴűŴźƈ\x03ŸŹŷ\x03źŮŪƈ\x0f\x03ƀŻŷŪƄ\x03ƆŻũ\x03ŽŮƈ\x03ƈūűŴũźƅ\x03ű\x03źŭŮŴũŴũ\x03ŪƄ\x03ŵŶŮ\x03Ż ũųŷŲ\x03 ŸŷŭũŹŷų}\x17\x11 ŐŶũŵŮŶűŻƄŲ\x03ŪũŴŮŻ\x03ő\x11ŝ\x11\x03ŚŻŹũūűŶźųŷŬŷ\x03mŘŮŻŹżƁųũ}\x03 řżźźųűŮ\x03źŮŰŷŶƄ\x0f\x03 \x14 \x14\x14 \x0f\x03ŴűŪŹŮŻŻŷ\x03ųŷŻŷŹŷŬŷ\x03źŷƀűŶűŴ\x03ŊŮŶżũ\x03 ū\x03źŷũūŻŷŹźŻūŮ\x03ź\x03ųŷŵŸŷŰű ŻŷŹŷŵ\x03 ű\x03ŪũŴŮŻŵŮŲźŻŮŹŷŵ5 \x0f\x03ŪŮŰżźŴŷūŶŷ\x03űŻŷůűŴ\x03ƆŻű\x03ūŷźŸŷŵűŶũŶűƈ\x03ű\x03ŸŮŹŮūŷŭűŴ\x03 ŬŮŶŮŹũŴƅŶƄŮ\x03ŵŷŻűūƄ\x03ŪżŭżƂŮŬŷ\x03ŵűŽũ\x03ŷ\x03 Commedia dell’ Arte \x03ū\x03ŶŷūŷŮ\x03ųũƀŮ - źŻūŷ\x11\x03ŗŶű\x03źŻũŶŷūűŴűźƅ\x03ŵũŻŮŹűũŴŷŵ\x03ūƄźŷųŷŬŷ\x03űźųżźźŻūũ\x03ű\x03ūųŴƇƀũŴűź ƅ\x03ū\x03 ŸŹŷſŮźź\x03Ÿŷűźųũ\x03ŷźŻŹŷ\x03źŷūŹŮŵŮŶŶŷŬŷ\x03žżŭŷůŮźŻūŮŶŶŷŬŷ\x03ƈŰƄųũ\x11 ŋ\x03ŭŹũŵũŻűƀŮźųŷŵ\x03ŻŮũŻŹŮ\x03ūźŻŹŮƀũ\x03ŹŮůűźźŮŹũ\x10ƆųźŸŮŹűŵŮŶŻũŻŷŹũ\x03ź\x03 ŵũźųũŵű\x03ƈŹŵũŹŷƀŶŷŲ\x03ŸũŶŻŷŵűŵƄ\x03ŸŹŷűŰŷƁŴũ\x03ƀżŻƅ\x03ŹũŶŮŮbȡ\x03ū\x03ŸŷźŴŮŭŶűŮ \x03 ŭŶű\x03\x14 \x13\x19\x03Ŭ\x11\x03ŋ\x03ũŶŻŹŮŸŹűŰŮ\x03ŋ\x11ŝ\x11\x03œŷŵűźźũŹůŮūźųŷŲ\x03ŕŮŲŮŹžŷŴƅŭ\x03źŻũūűŻ \x03Ŵű- ŹűƀŮźųżƇ\x03ŭŹũŵż\x03ŊŴŷųũ\x03mŊũŴũŬũŶƀűų}\x11 ŋ\x03ŷųŷƉŵŮ\x03źűŶŮŲ\x03ŸżźŻŷŻƄ\x03źŻŷűŻ\x03ŸŷźŹŮŭű\x03ŸŴũŶƁŮŻũ\x03ŵũŴŮŶƅųűŲ\x03ŪŮ - ŴƄŲ\x03ŻŮũŻŹűų\x03ź\x03ųŹũźŶƄŵ\x03ŸŴƇƁŮūƄŵ\x03ŰũŶũūŮźŷŵ\x0f\x03ŹũźƁűŻƄŵ\x03ŰŷŴŷŻƄŵű\x03 ŰūŮŰŭũŵű\x11\x03Ŗũŭ\x03Ŷűŵbȡ\x03ŸũżŻűŶũ\x03ūŮŹŮūŷų\x03ű\x03ŸŹŷūŷŴŷų\x0f\x03żžŷŭƈƂũƈ\x03ūūƄźƅ\x11 \x03 ŖŮŸŹűųŹƄŻƄŮ\x03ųŷŴŷźŶűųű"\x03őŴű\x03ūũŬű\x0f\x03ųŷŻŷŹƄŵű\x03źūƄƁŮ\x03żŸŹũūŴƈƇŻźƈ\x03 ŉ\x11\x03ŊŮŶżũ\x11\x03ŨŹŵũŹųũ\x11\x03ŦźųűŰ\x03ŭŮųŷŹũſűű\x03\x14\x10Ų\x03ųũŹŻűŶƄ\x03ŪũŴŮŻũ\x03mŘŮŻŹżƁųũ }\x11\x03\x14 \x15\x14\x11\x03 ŝŹũŬŵŮŶŻ \x15\x19\x17ŋũŭűŵ\x03ŢŮŹŪũųŷū\x03\x03 \x03řżźźųűŲ\x03ŵűŽ\x03ŷ\x03 Commedia dell’Arte ŵũŹűŷŶŮŻųű"\x03ŌŹŷžŷŻ\x03ŪũŹũŪũŶũ\x11\x03őŰ\x10Űũ\x03ŰũŶũūŮźũ\x03ūƄźųũŴƅŰƄūũŮŻ\x03źżŽŴŮ Ź\x0f\x03 ŭŮŴŷūűŻŷ\x03ŰũŪűŹũŮŻźƈ\x03ū\x03źūŷƇ\x03Ūżŭųż\x0f\x03ŰũůűŬũŮŻ\x03źūŮƀű\x11\x03ŕżŰƄųũ\x03 mŵżŰƄ ƀųũ\x03 ź\x03ƈŭŷŵ}bȡ\x03ųũų\x03źųũůŮŻ\x03ŷ\x03ŶŮŲ\x03ŮŮ\x03ũūŻŷŹ\x0f\x03ŸŷƆŻ\x03ŕ\x11ŉ\x11\x03œżŰŵűŶ \x11\x03ŐũŶũūŮź \x03ŹũŰ- ŭūűŬũŮŻźƈ\x11 Ŗũ\x03źſŮŶŮ\x03ŻŮũŻŹűųũ\x03ŸŷźŻũūŴŮŶ\x03ŻŹŮžźŻŮŶŶƄŲ\x03ŸũūűŴƅŷŶ\x03ź\x03ŭūżŵƈ\x03 ŭūŮŹƈŵű\x03ű\x03ŷųŶŷŵ\x0f\x03ū\x03ųŷŻŷŹŷŵ\x03ūűŭŶũ\x03ŶũŹűźŷūũŶŶũƈ\x03Ŷũ\x03ŪżŵũŬŮ\x03ŭũŴƅ\x11\x03Ŝ \x03 ŷųŶũ\x0f\x03Ŷũ\x03ŰŷŴŷƀŮŶŷŵ\x03žŹżŸųŷŵ\x03źŻżŴƅƀűųŮ\x03źűŭűŻ\x03ŘƅŮŹŷ\x03ū\x03ŪŮŴŷŵ\x03ŪũŴũžŷ ŶŮ\x03 ź\x03ųŹũźŶƄŵű\x03ŸŷŵŸŷŶũŵű\x03ŸżŬŷūűſ\x11\x03ŚųŴŷŶűū\x03ŬŷŴŷūż\x03Ŷũ\x03ŪŴƇŭŷ\x03ŸŴŷƉŶŷŬŷ\x03 ūŷŹŷŻŶűųũ\x03ű\x03ŷŪūŮŹŶżū\x03ŷŭŶŷŲ\x03ŶŷŬŷŲ\x03ŭŹżŬżƇ\x0f\x03ŷŶ\x03źŵŷŻŹűŻ\x03ū\x03ƆŻż\x03ŭũŴƅ\x11 \x03ŏŭŮŻ\x03 źūŷƇ\x03ŶŮūŮźŻż\x11 ŋ\x03ŬŴżŪűŶŮ\x03źſŮŶƄ\x0f\x03ŽŹŷŶŻũŴƅŶŷ\x0f\x03źŻŷűŻ\x03ŭŴűŶŶƄŲ\x03źŻŷŴ\x11\x03Őũ\x03Ŷűŵ\x0f\x03Ŵűſŷŵ\x03 ų\x03ŸżŪŴűųŮ\x0f\x03mŵűźŻűƀŮźųŷŮ\x03źŷŪŹũŶűŮ}\x11\x03ŝűŰűŷŶŷŵűű\x03ūŰūŷŴŶŷūũŶƄ\x11\x03ōŷŴŬ ŷ\x03 źŵŷŻŹƈŻ\x03ū\x03ŰŹűŻŮŴƅŶƄŲ\x03ŰũŴ\x0f\x03ŰũŻŮŵbȡ\x03ŶũŸŹũūŷ\x0f\x03ŶũŴŮūŷ\x0f\x03źŶŷūũ\x03Ŷũ\x03ŰŹű ŻŮŴƈ\x11\x03 řżųű\x03Ŷũ\x03źŻŷŴŮ\x0f\x03ŸũŴƅſƄ\x03ŭŹŷůũŻ\x03ű\x03ŪŮŬũƇŻ\x11\x03ŏŭżŻ\x03ŚŵŮŹŻƅ\x11 ŋźŻŹŮƀũ\x03ŘƅŮŹŷ\x03ű\x03mŵűźŻűųŷū}\x03ź\x03ŖŮūŮźŻŷŲbȡ\x03ŚŵŮŹŻƅƇbȡ\x03œŷŴŷŵŪűŶŷŲ\x03 ŸŹűŶŮźŮŻ\x03űŵ\x03ŵŶŷŬŷ\x03ŷůűŭũŮŵƄž\x03ŶŮŷůűŭũŶŶŷźŻŮŲ\x11\x03ŋźŻŹŮƀũ\x03ŕŮŲŮŹžŷŴƅ - ŭũ\x03ź\x03ŸƅŮźŷŲ\x03ŊŴŷųũ\x03źŻũŶŮŻ\x03źŷŪƄŻűŮŵ\x03ū\x03űźŻŷŹűű\x03ŵűŹŷūŷŬŷ\x03ŻŮũŻŹũ\x03ŞŞ\x03 ū\x11\x03 śũų\x03ůŮ\x0f\x03ųũų\x03ű\x03źŻŷŴųŶŷūŮŶűŮ\x03ŚŻũŶűźŴũūźųŷŬŷ\x03ź\x03ƀŮžŷūźųŷŲ\x03mŠũŲųŷŲ}\x0f \x03ŷŶũ\x03 ƈūűŻ\x03źŷŪŷƇ\x03ŸŹűŵŮŹ\x03ŹŷůŭŮŶűƈ\x03źſŮŶűƀŮźųŷŬŷ\x03ƈŰƄųũ\x03űŰ\x03źŷŭŮŹůũŶűƈ\x03ű\x03 Ŗ\x11\x03ŚũŸżŶŷū\x11\x03ŕűźŻűƀŮźųŷŮ\x03źŷŪŹũŶűŮ\x11\x03\x14 \x13 \x11\x03 ŝŹũŬŵŮŶŻ 265Pro memoria:   ŻŮũŻŹũŴƅŶƄŮ\x03űźŻŷŹűű ŽŷŹŵƄ\x03ūŮŴűųŷŲ\x03ŭŹũŵũŻżŹŬűű\x11\x03Śūŷűŵű\x03źŻűžũŵű\x03ű\x03ŹŮŵũŹųũŵű\x03ŊŴŷų\x0f\x03ū\x03 űŰūŮźŻŶŷŵ\x03źŵƄźŴŮ\x0f\x03ŷŪżƀűŻ\x03ŕŮŲŮŹžŷŴƅŭũ\x03Żŷŵż\x03żźŴŷūŶŷŵż\x03ŻŮũŻŹż\x0f\x03ŻŷŲ \x03 źűŵūŷŴűƀŮźųŷŲ\x03 ūŷ\x03ūŻŷŹŷŲ\x03ŸŷŴŷūűŶŮ\x03ūŮųũ\x03ŮŮ\x03ŶũŰŷūżŻ\x03ŵŮŻũŽŷŹűƀŮźųŷ Ų \x03 ŵűŰũŶźſŮŶŮ\x0f\x03ųŷŻŷŹżƇ\x03ŹŮůűźźŮŹ\x03ŪżŭŮŻ\x03ŹũŰūűūũŻƅ\x0f\x03ŷŻŻũƀűūũŻƅ\x03ű\x03źŷūŮ Ź- ƁŮŶźŻūŷūũŻƅ\x03ū\x03ŭũŴƅŶŮŲƁŮŵ\x0f\x03ŷŪŷŬũƂũƈ\x03ŮƇbȡ\x03ūŸŹƈŵżƇ\x03űŴű\x03ŰũŷƀŶŷbȡ\x03ūź Ůž\x03 ŴƇŭŮŲ\x03ŻŮũŻŹũ\x03ŵűŶżūƁŮŬŷ\x03źŻŷŴŮŻűƈ\x11 œŷŶŮƀŶŷ\x0f\x03ŸŹŷŭŷŴůũƈ\x03ŭūűŬũŻƅźƈ\x03ŹũŶŮŮ\x03űŰŪŹũŶŶŷŲ\x03ŭŷŹŷŬŷŲ\x0f\x03ŕŮŲŮŹ - žŷŴƅŭ\x03źũŵ\x03ŸŹűƁŮŴ\x03ŪƄ\x03ų\x03ŷŻųŹƄŻűƈŵ\x03mŊũŴũŬũŶƀűųũ}\x11\x03ŐũŴŷŬŷŵ\x03Żŷŵż\x03źŴż ůũŻ\x03 ű\x03ŮŬŷ\x03ŷŸƄŻƄ\x03ůŮźŻųŷŬŷ\x03ŭŮŲźŻūŮŶŶŷŬŷ\x03ŸŷźŻŹŷŮŶűƈ\x03źŸŮųŻũųŴŮŲ\x03ū\x03ŸŹŷūű Ŷ- ſűű\x03 ŷźŶŷūũŶŶƄŮ\x03Ŷũ\x03ŻŷƀŶŷŵ\x03żƀŮŻŮ\x03ūŷŰŭŮŲźŻūűƈ\x03Ŷũ\x03ũųŻŮŹŷū\x03ű\x03ŸżŪŴűų ż\x03 ŵŷŶŻũůũ\x03ŵũŻŮŹűũŴƅŶƄž\x03ŷŪƃŮųŻŷū\x03ŰŹŮŴűƂũ \x0f\x03ű\x03ŮŬŷ\x03ŷŻųũŰ\x03ŷŻ\x03ŸŹűŶſűŸũ \x03 můűŰŶŮŸŷŭŷŪűƈ}\x03ū\x03ŸŷŴƅŰż\x03mźūŮŹžůűŰŶŮŶŶŷźŻű}\x03źűŵūŷŴűźŻźųŷŬŷ\x03ŻŮũŻŹ ũ\x0f\x03 ŸŷƆŻűųũ\x03ųŷŻŷŹŷŬŷ\x03ŪƄŴũ\x03űŵ\x03ŹũŰŹũŪŷŻũŶũ\x03ŮƂŮ\x03ū\x03ŵŷźųŷūźųŷŲ\x03ŚŻżŭűű\x03Ŷũ \x03 ŘŷūũŹźųŷŲ\x03 \x14 \x13\x18 \x11\x03ŐŮŹŶŷ\x03ūźŮŬŭũ\x03ūźžŷŭűŻ\x03ŴűƁƅ\x03ū\x03ŸŷŭŬŷŻŷūŴŮŶŶŷŲ\x03Ÿŷ ƀūŮ\x11\x03 ŋŴűƈŶűŮ\x03ŮźŻƅ\x03ŸŹŷſŮźź\x03ŷŪŶũŹżůŮŶűƈ\x03ū\x03ƀżůŷŵ\x03žżŭŷůŮźŻūŮŶŶŷŵ\x03ŻŮųźŻŮ\x03 ŽŷŹŵżŴűŹŷūŷų\x0f\x03ūŷŻ\x10ūŷŻ\x03ŬŷŻŷūƄž\x03źŷŹūũŻƅźƈ\x03ź\x03źŷŪźŻūŮŶŶƄž\x03żźŻ\x11\x03ŗŭŶũ ųŷ\x0f\x03 żźųŷŹŮŶűŮ\x0f\x03ŸŹűŭũŶŶŷŮ\x03ūŶżŻŹŮŶŶŮŵż\x03ŹũŰūűŻűƇ\x03ŕŮŲŮŹžŷŴƅŭũ\x03ūźŻŹŮƀŮŲ\x03 ź\x03 mŊũŴũŬũŶƀűųŷŵ}\x0f\x03ŷųũŰũŴŷźƅ\x03źŻŷŴƅ\x03ŵŷƂŶƄŵ\x0f\x03ƀŻŷ\x03ŰŹŮŴűƂŮ\x0f\x03ųŷŻŷŹŷŮ\x03żū ű- ŭŮŴũ\x03ŸżŪŴűųũ\x03ŻŮũŻŹũ\x03œŷŵűźźũŹůŮūźųŷŲ\x03ū\x03ųũŶżŶ\x03ŖŷūŷŬŷ\x0f\x03\x14 \x13\x1a\x10Ŭŷ\x0f\x03Ŭŷ ŭũ\x0f\x03 ŶũŸŹŷƀƅ\x03ūƄŴũŵƄūũŴŷźƅ\x03űŰ\x03Źƈŭũ\x03ŸŹŮŭƄŭżƂűž\x03źŸŮųŻũųŴŮŲ\x03ŹŮůűźźŮŹũ\x11 ŞżŭŷůŮźŻūŮŶŶƄŲ\x03źŵƄźŴ\x03źŸŮųŻũųŴƈ\x03ƈūźŻūŮŶŶŮŮ\x03ūźŮŬŷ\x03ƀűŻũŴźƈ\x03ū\x03ŵŮŲ - ŮŹžŷŴƅŭŷūźųŷŵ\x03űźŸŷŴŶŮŶűű\x03ŹŷŴű\x03ŘƅŮŹŷ\x11\x03œũų\x03ŶŮųŷŬŭũ\x03śŹŮŸŴŮū\x0f\x03ŘƅŮŹŷ \x03ŭũŴ\x03 ŕŮŲŮŹžŷŴƅŭż\x03ūŷŰŵŷůŶŷźŻƅ\x03ŴűŹűƀŮźųŷŬŷ\x03źũŵŷŹũźųŹƄŻűƈ\x11\x03ŚŷūŸũŭŮŶűŮ\x03 źżŭƅŪƄ\x03ű\x03ŹŷŴű\x03ŷųũŰũŴŷźƅ\x03Żũųŷūŷ\x0f\x03ƀŻŷ\x03ŭũůŮ\x03ŶŮ\x03ūűŭŮūƁűŲ\x03mŊũŴũŬũŶƀű ųũ}\x03 ŚŮŹŬŮŲ\x03ŦŲŰŮŶƁŻŮŲŶ\x03ūźƇ\x03źūŷƇ\x03ůűŰŶƅ\x03ŹűźŷūũŴ\x03ű\x03ŷŸűźƄūũŴ\x03ŕũźŻŮŹũ\x03ū\x03 ŷŪŹũŰŮ\x03ŪŮŴŷŬŷ\x03Ÿũƈſũ\x11\x03ŔŷŵųűŲ\x0f\x03źŸűŹũŴƅƇ\x03ŰũųŹżƀŮŶŶƄŲ\x03ű\x03ŷŭŶŷūŹŮŵŮŶ - Ŷŷ\x03ūŮźƅ\x03źŷźŻŷƈƂűŲ\x03űŰ\x03żŬŴŷū\x03ŘƅŮŹŷ\x03ŕŮŲŮŹžŷŴƅŭũ\x03ŸŮƀũŴƅŶŷ\x03ŶũűŬŹƄūũŴ \x03 Ŷũ\x03ŭżŭŷƀųŮ\x03ŻŮŵż\x03ŷŭűŶŷƀŮźŻūũ\x0f\x03ŵŹũƀŶŷŲ\x03ŵűŹŷūŷŲ\x03ŸżźŻŷŻƄ\x0f\x03ū\x03ųŷŻŷŹŷŲ \x03 ųŹżŻƈŻźƈbȡ\x03ųũų\x03źŶŮůűŶųűbȡ\x03ŷŪŹũŰƄ\x10źżƂŶŷźŻű\x0f\x03źŻũŴųűūũƈźƅ\x03ű\x03ŹũŰŴŮŻ ũƈźƅ\x03 ūŶŷūƅ\x11\x03őž\x03ŭūűůŮŶűŮ\x03žũŷŻűƀŶŷ\x11\x03ŗŶű\x03ŸŷŭƀűŶŮŶƄ\x03ūŮŻŹżbȡ\x03ūŶŮƁŶŮŲ\x03ŻũűŶ - źŻūŮŶŶŷŲ\x03źűŴŮ\x0f\x03źŷūźŮŵ\x03ŶŮ\x03źŷŸŹűŹŷŭŶŷŲ\x03űŵ\x11\x03ŖŮźŴűƈŶŶƄŮ\x03ū\x03ŭūűůŮŶűű\x0f \x03 ŷŶű\x03żŵŮƇŻ\x03ŴűƁƅ\x03źŴűŸũŻƅźƈ\x03ū\x03ŵŮŹŻūƄŲ\x03ųũŹŻŷŶŶƄŲ\x03źŶŮŬ\x0f\x03żŻŹũƀűūũƈ\x03űź ųŹż\x03 źūŮŻũ\x03ū\x03ŸŷƁŴŷŲ\x03źŸŹŮźźŷūũŶŶŷźŻű\x03ŪżŭŶŮŲ\x11\x03Ŗũ\x03ūŰŬŴƈŭ\x03źŷ\x03źŻŷŹŷŶƄbȡ\x03Ɔ Żŷ\x03 ŶŮŵŶŷŬŷ\x03źŵŮƁŶŷ\x03ű\x03ŷƀŮŶƅ\x03ŬŹżźŻŶŷ\x11\x03mő\x03żŴƄŪũŮŵźƈ\x03ŷŻ\x03żůũźũ\x0f\x03ű\x03źŵŮŮŵź ƈ\x03 Ŷũŭ\x03źūŷűŵű\x03żŴƄŪųũŵű\x0fbȡ\x03ŶũŸűƁŮŻ\x03œ\x11ő\x11\x03ŠżųŷūźųűŲ\x11bȡ\x03ŦŻŷ\x03ŷƀŮŶƅ\x03źŴŷů Ŷũƈ\x0f\x03 ŷƀŮŶƅ\x03żŻŷŶƀŮŶŶũƈ\x03Ɔŵŷſűƈ}6\x11 ŗƀŮūűŭŶŷ\x0f\x03ƀŻŷ\x03źŸŷźŷŪŶŷźŻƅ\x03ų\x03źŻŷŴƅ\x03űŰƄźųũŶŶƄŵ\x03ŸŮŹŮůűūũŶű - ƈŵbȡ\x03żŭŮŴ\x03ŶŮŵŶŷŬűž\x11\x03ŊŮƁŮŶƄŲ\x03ūźŸŴŮźų\x03źŷūźŮŵ\x03űŶƄž\x03ƆŵŷſűŲ\x03ŰŹűŻŮŴŮŲ \x03 266ŋũŭűŵ\x03ŢŮŹŪũųŷū\x03\x03 \x03řżźźųűŲ\x03ŵűŽ\x03ŷ\x03 Commedia dell’Arte ŊũŴũŬũŶƀűųũ}\x03ŕŮŲŮŹžŷŴƅŭ\x0f\x03ūŸŷźŴŮŭźŻūűű\x0f\x03ƀũźŻŷ\x03ŻŹũųŻŷūũŴ\x03ųũų\x03ŵŮŻŷ - ŭŷŴŷŬűƀŮźųűŲ\x03żŹŷų\x11\x03ŎŭűŶŷūŹŮŵŮŶŶŷźŻƅ\x03ŷūũſűŲ\x03ű\x03ŷŪźŻŹżųſűŲ\x03ųũŰũŴũź ƅ\x03 ŹŮůűźźŮŹż\x03ŻŷŲ\x03źũŵŷŲ\x03űŭŮũŴƅŶŷŲ\x03ŹŮũųſűŮŲ\x0f\x03ųŷŻŷŹżƇ\x03ŭŷŴůŶŷ\x03ūƄŰƄūũŻƅ \x03 ŸŷŭŴűŶŶŷŮ\x03ŸŹŷűŰūŮŭŮŶűŮ\x03ŴƇŪŷŬŷ\x03űźųżźźŻūũ\x0f\x03ũ\x03źſŮŶűƀŮźųŷŬŷbȡ\x03ū\x03ŷźŷ - ŪŮŶŶŷźŻű\x11\x03mŘżźŻƅ\x03ƀũźŻƅ\x03ŰŹűŻŮŴƅŶŷŬŷ\x03ŰũŴũ\x03ƁűųũŴũ\x03ŊŴŷųż\x03ű\x03ŮŬŷ\x03ũųŻŮ - Źũŵ\x0fbȡ\x03ŸűźũŴ\x03ŕŮŲŮŹžŷŴƅŭbȡ\x03ŻŮũŻŹ\x03ŪƄŴ\x03ŻŮũŻŹŷŵ\x11\x03ő\x0f\x03ŪƄŻƅ\x03ŵŷůŮŻ\x0f\x03ƆŻŷ \x10Żŷ\x03 ŷŪźŻŷƈŻŮŴƅźŻūŷ\x0f\x03Żŷ\x03ŮźŻƅ\x03Żŷ\x0f\x03ƀŻŷ\x03ŸżŪŴűųũ\x03ŷźŵŮŴűŴũźƅ\x03Żũų\x03ŶŮűźŻŷūŷ \x03źūű - źŻũŻƅ\x0f\x03ŴżƀƁŮ\x03ūźŮŬŷ\x03ŭŷųũŰƄūũŮŻ\x0f\x03ƀŻŷ\x03ŰŭŮźƅ\x03żźŻũŶŷūűŴŷźƅ\x03ŷŻŶŷƁŮŶűŮ \x03ų\x03 ŸŹŮŭźŻũūŴŮŶűƇ\x0f\x03ųũų\x03ų\x03ŸŹŮŭźŻũūŴŮŶűƇ\x03ŻŮũŻŹũŴƅŶŷŬŷ\x03ŸŷŹƈŭųũ}\x1a\x11\x03řżźźųŷŮ\x03 źſŮŶűƀŮźųŷŮ\x03űźųżźźŻūŷ\x03ūŷŰūŹũƂũŴŷ\x03źŮŪŮ\x03ū\x03mŊũŴũŬũŶƀűųŮ}\x03űŰŹƈŭŶŷ\x03Ÿ ŷŭ- ŰũŪƄŻƄŮ\x03 ŻŮũŻŹũŴƅŶƄŮ \x03ųũƀŮźŻūũ\x11',

In [44]:
annotations = []

In [45]:
for abstr in enumerate(abstracts, start=1):
  print(f'Аннотация статьи {abstr[0]}:')
  annotation = str(' '.join(abstr[1]))
  annotations.append(annotation)
  print(annotation, '\n\n')

Аннотация статьи 1:
— С. 110–114. — С. 170–174. Shell B.H., Martin M.V., Hung P.C.K., Rueda L. Cyber Child Pornography: a Review Paper of Social and Legal Issues and Remedies — and a Proposed Technological Solution.


Аннотация статьи 2:
Ключевые слова: Единоборства, спорт, спортсмены. По возрасту борцы делятся на юниоров, взрослых, ветеранов и т. д. Разделение на группы по возрасту важно, так как правила и продолжительность матча различаются. Именно в этом виде спорта можно овладеть приемами борьбы и самообороны, чтобы в крайнем случае защитить себя.


Аннотация статьи 3:
[3, ñ. Ñ. Ñ.


Аннотация статьи 4:
Системы  управления  двигателями  в настоящее  время  выпускаются  в различных модификациях . Системы  управления  двигателем  подразделяются  на системы  управления карбюраторным  (бензиновым ) и дизельным  двигателем  и трансмиссией . Развитие  экологического  туризма  – один  из возможных  путей  экологического просвещения  населения .


Аннотация статьи 5:
Радевская Н.С., Антонова Т .А., Радевский А.В. Организации летнего детского оздоровительного отдыха ...патриотических качеств у молодежи через систему летнего оздоровительного отдыха для детей и подростков на базе ОУ , органи - зацию профильных смен военно-патриоти - ческой направленности. Поставленные перед школой задачи ста - ли основанием для разработки и принятия программы профильной кадетской смены детского оздоровительного лагеря на базе школы, позволяющей соприкоснуться с историей, культурой и достижениями сво - его Отечества, таким образом, ориенти - рованной на практическое воплощение в жизнь гуманистических ценностей, на фор - мирование у детей и подростков активной гражданской позиции и их социализацию, направленную на пробуждение интереса к истории кадетства в России, уважительное отношение к его историческим ценностям, на патриотическое, нравственное воспита - ние, содержательное общение и межлич - ностные отношения в разновозрастном коллективе. Радевская Н.С., Антонова Т .А., Радевский А.В. Организации летнего детского оздоровительного отдыха ...довской песни», «Вечер разгаданных и не - разгаданных тайн).


Аннотация статьи 6:
Перечислим основные плюсы:  обеспеченность финансирования опера ции в полном объеме;  нет необходимости осуществлять платежи сразу  и иметь всю сумму денег в наличии ;  лизинг является более гибким источником (например, по сравнению с ссудой), так как позволяет субъектам выбрать альтернативный график выплат , который описывается сторонами при заключении договора ;  полученные активы, как правило, не числятся у лизингополучателя на балансе, что освобождает его от уплаты налога на это имущество;  лизинг обеспечивает возможность получения квалифицированного сервисного и техн ического обслуживания и др. К недостаткам же данной операции можно отнести следующее:  конечная стоимость лизинга обычно получается больше, чем покупка оборудования в кредит , то есть лизинг обходится  дороже, чем кредит, что, конечно же, отпугивает клиентов лизинга ;  необходимость внесения аванса;  платежи носят обязательный характер и производятся в установленные сроки независимо от состояния оборудования и результатов хозяйственной деятельности;  сущест вует риск расторжения договора;  юридическая сложность сделки , более тяжелые условия (в отличие от другой финансовой помощи)  и др. [7]. Лизинг в России. 2015, С.  1014 -1021 6.


Аннотация статьи 7:
Потому у Н. В. Нечаевой уже на 12 странице «Азбуки» (приблизи тельно на шестом уроке) дети приступают к изучению однозвучных гласных  звуков: Аа, Уу, Оо, Ээ, Ии, ы.  В это же время вводятся такие важные лингвистические понятия, как речь устная и письменная (в темах «История речи», «Речь устная и письменная»), предложен ие, слово, звук, звуки гласные и согласные, буквы (в темах «Знаки звук ов», «Звуки – гласные и согласные», «Знаки звуков – буквы»), твердые и мягкие согласные звуки (в теме «Как буква меняет слово»). [3, с. 6-7]. Нечаева, Н. В. Обучение грамоте.


Аннотация статьи 8:
С. 89. С. 88–105. С. 29–41.


Аннотация статьи 9:

In [46]:
annots = pd.DataFrame(annotations, columns=['annotations_sumy'])

In [47]:
sumy = pd.concat([df, annots], join='outer', axis=1)

In [48]:
sumy

,names,texts,years,annotations_sumy
0,paper_0,133\n133\nISSN 2500-4255Всероссийский криминол...,2025,"— С. 110–114. — С. 170–174. Shell B.H., Martin..."
1,paper_1,"""Теория и практика современной науки"" № 5(71) ...",2025,"Ключевые слова: Единоборства, спорт, спортсмен..."
2,paper_2,НАУЧНАЯ МЫСЛЬ КАВКАЗА 2010 127 № 3\nСТРАНИЧК...,2025,"[3, ñ. Ñ. Ñ."
3,paper_3,стр. 2 из 6 \nУДК 629 \nК ВОПРОСУ ПРИМЕНЕНИ...,2025,Системы управления двигателями в настоящее ...
4,paper_4,90 ЧЕЛОВЕК И ОБРАЗОВАНИЕ. 2019. № 4 (61)\nОб...,2025,"Радевская Н.С., Антонова Т .А., Радевский А.В...."
5,paper_5,"УДК 339.187 \nЗаборских А.С. , студент \nПер...",2025,Перечислим основные плюсы:  обеспеченность фи...
6,paper_6,Vestnik of Tuvan State University \nIssue 4. ...,2025,Потому у Н. В. Нечаевой уже на 12 странице «Аз...
7,paper_7,.\nАКИМОВА Алёна Олеговна – аспирант Московско...,2025,С. 89. С. 88–105. С. 29–41.
8,paper_8,252 \nŋũŭűŵŢŮŹŪũųŷū\nřżźźųűŲŵűŽŷ\nCommed...,2025,252 ŋũŭűŵŢŮŹŪũųŷū řżźźųűŲŵűŽŷ Commedia del...
9,paper_9,Петербургский исторический журнал № 4 (2015)УД...,2025,"18 Финляндское уголовное уложение, в связи с о..."

##T5

In [49]:
!pip install transformers

Requirement already satisfied: transformers in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (4.51.3)
Requirement already satisfied: filelock in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.31.4)
Requirement already satisfied: numpy>=1.17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\user\appdata\roaming\python\python311\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.13.1)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from requests->transformers) (2025.4.26)

In [50]:
from transformers import AutoModelForSeq2SeqLM, T5TokenizerFast

In [51]:
import torch
from transformers import AutoTokenizer, AutoModelWithLMHead, T5ForConditionalGeneration

##RuT5-base-sum

In [52]:
model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

In [53]:
# Цикл по первым 5 текстам из датафрейма
for text in df.texts[:5]:
  # Сохраняем текст статьи
  article_text = text
  
  # Токенизируем текст с ограничением длины 600 токенов
  # add_special_tokens=True - добавляет специальные токены [CLS] (начало последовательности) и [SEP] (разделитель последовательностей)
  # padding="max_length" - дополняет последовательности до максимальной длины
  # truncation=True - обрезает текст если он длиннее max_length
  # return_tensors="pt" - возвращает тензоры PyTorch
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  
  # Генерируем аннотацию с помощью модели
  # no_repeat_ngram_size=4 - запрещает повторение n-грамм длиной 4
  output_ids = model.generate(input_ids=input_ids, no_repeat_ngram_size=4)[0]
  
  # Декодируем полученные токены обратно в текст
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  
  # Выводим аннотацию
  print(f'Аннотация текста:\n {summary}\n\n')

Аннотация текста:
 В российском криминологическом журнале опубликовано исследование, посвященное распространению детской порнографии в сети Интернет. На сегодняшний день перед национальными законодательствами стоят различные задачи по противодействию распространению этого явления, от криминализации до совершенство - вания технических средств противодействия ему.


Аннотация текста:
 Единоборства - это вид спорта, направленный на поддержание здоровья человека, а также для того, чтобы человек овладевал основными элементами борьбы. В этой статье мы расскажем, какие виды спорта существуют, в чём состоит особенность единоборств.


Аннотация текста:
 Н.В. Забабурова Нина Владимировна – доктор филологи - ческих наук профессор кафедры теории и истории мировой литературы Южного федерального университета, г. Ростов -на Дону, ул. Пушкинская, 150, e-mail: Zababourova.


Аннотация текста:
 Автомобильная электроника применяется при ремонте и обслуживании автомобилей отечественного и импортного производства на предприятиях автосервиса. Для этого необходимо знание автомобильной электроники, используемой при эксплуатации автомобилей различной модификации.


Аннотация текста:
 Программа профильной кадетской смены детского оздоровительного лагеря на базе школы, позволяющей соприкоснуться с историей, культурой и достижениями своего Отечества, пробуждающей интерес к истории кадетства в России.

In [54]:
# Создаем пустой список для хранения аннотаций
annotations_t5 = []

# Проходим по всем текстам в датафрейме
for text in df.texts:
  # Сохраняем текст статьи
  article_text = text
  
  # Токенизируем текст с ограничением длины 600 токенов
  # add_special_tokens=True - добавляет специальные токены [CLS] и [SEP]
  # padding="max_length" - дополняет последовательности до максимальной длины
  # truncation=True - обрезает текст если он длиннее max_length
  # return_tensors="pt" - возвращает тензоры PyTorch
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  
  # Генерируем аннотацию с помощью модели
  # min_length=50 - минимальная длина аннотации
  # max_length=250 - максимальная длина аннотации
  # no_repeat_ngram_size=4 - запрещает повторение n-грамм длиной 4
  output_ids = model.generate(input_ids=input_ids, min_length=50, max_length=250, no_repeat_ngram_size=4)[0]
  
  # Декодируем полученные токены обратно в текст
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  
  # Выводим аннотацию
  print(f'Аннотация текста:\n {summary}\n\n')
  
  # Добавляем аннотацию в список
  annotations_t5.append(str(''.join(summary)))

Аннотация текста:
 В российском криминологическом журнале опубликовано исследование, посвященное распространению детской порнографии в сети Интернет. На сегодняшний день перед национальными законодательствами стоят различные задачи по противодействию распространению этого явления, от криминализации до совершенство - вания технических средств противодействия ему.


Аннотация текста:
 Единоборства - это вид спорта, направленный на поддержание здоровья человека, а также для того, чтобы человек овладевал основными элементами борьбы. В этой статье мы расскажем, какие виды спорта существуют, в чём состоит особенность единоборств.


Аннотация текста:
 Н.В. Забабурова Нина Владимировна – доктор филологи - ческих наук профессор кафедры теории и истории мировой литературы Южного федерального университета, г. Ростов -на Дону, ул. Пушкинская, 150, e-mail: Zababourova.


Аннотация текста:
 Автомобильная электроника применяется при ремонте и обслуживании автомобилей отечественного и импортного производства на предприятиях автосервиса. Для этого необходимо знание автомобильной электроники, используемой при эксплуатации автомобилей различной модификации.


Аннотация текста:
 Программа профильной кадетской смены детского оздоровительного лагеря на базе школы, позволяющей соприкоснуться с историей, культурой и достижениями своего Отечества, пробуждающей интерес к истории кадетства в России.


Аннотация текста:
 Российский лизинг является одной из самых актуальных тем в мире. В статье рассмотрены основные преимущества и недостатки проведения лизинговых сделок. Обозначены роль и особенности лизинга в России.


Аннотация текста:
 Проблема обучения грамоте младших школьников в современной начальной школе стала одной из самых актуальных в мире образовательных технологий. Основное содержание исследования составляет анализ инновационной методики Н. В. Нечаевой, базирующейся на концепции развивающего обучения.


Аннотация текста:
 Российская диаспора: перспективы сотрудничества с соотечественниками за рубежом – одна из важнейших проблем современного российского общества. Проблема взаимодействия России со своей диаспорой, её факторы и критерии, а также критерии взаимодействия с государственными и общественными структурами страны можно найти в ра- ботах таких учёных, как В. Евтух, В. Трощинский, В. Рымаренко, А. Попок и другие.


Аннотация текста:
 Commedia dell’Arte - одна из самых успешных и лучших и самых знаменитых европейских и международных кинотеатров. Местные кинотеатры и кинотеатры, где можно было бы сыграть роль режиссера, считают, что его можно будет использовать только для того, чтобы развлечь своих соотечественников.


Аннотация текста:
 Уголовное право Финляндии 1889 г. является одним из самых эффективных и эффективных в Европе, а тюрьмы — одни из лучших в мире. В Петербургском историческом журнале я попытаюсь рассказать, каким образом Финляндия достигла этого.

In [55]:
annots_t5 = pd.DataFrame(annotations_t5, columns=['annotations_t5'])

In [56]:
full = pd.concat([sumy, annots_t5], join='outer', axis=1)

In [57]:
full

,names,texts,years,annotations_sumy,annotations_t5
0,paper_0,133\n133\nISSN 2500-4255Всероссийский криминол...,2025,"— С. 110–114. — С. 170–174. Shell B.H., Martin...",В российском криминологическом журнале опублик...
1,paper_1,"""Теория и практика современной науки"" № 5(71) ...",2025,"Ключевые слова: Единоборства, спорт, спортсмен...","Единоборства - это вид спорта, направленный на..."
2,paper_2,НАУЧНАЯ МЫСЛЬ КАВКАЗА 2010 127 № 3\nСТРАНИЧК...,2025,"[3, ñ. Ñ. Ñ.",Н.В. Забабурова Нина Владимировна – доктор фил...
3,paper_3,стр. 2 из 6 \nУДК 629 \nК ВОПРОСУ ПРИМЕНЕНИ...,2025,Системы управления двигателями в настоящее ...,Автомобильная электроника применяется при ремо...
4,paper_4,90 ЧЕЛОВЕК И ОБРАЗОВАНИЕ. 2019. № 4 (61)\nОб...,2025,"Радевская Н.С., Антонова Т .А., Радевский А.В....",Программа профильной кадетской смены детского ...
5,paper_5,"УДК 339.187 \nЗаборских А.С. , студент \nПер...",2025,Перечислим основные плюсы:  обеспеченность фи...,Российский лизинг является одной из самых акту...
6,paper_6,Vestnik of Tuvan State University \nIssue 4. ...,2025,Потому у Н. В. Нечаевой уже на 12 странице «Аз...,Проблема обучения грамоте младших школьников в...
7,paper_7,.\nАКИМОВА Алёна Олеговна – аспирант Московско...,2025,С. 89. С. 88–105. С. 29–41.,Российская диаспора: перспективы сотрудничеств...
8,paper_8,252 \nŋũŭűŵŢŮŹŪũųŷū\nřżźźųűŲŵűŽŷ\nCommed...,2025,252 ŋũŭűŵŢŮŹŪũųŷū řżźźųűŲŵűŽŷ Commedia del...,Commedia dell’Arte - одна из самых успешных и ...
9,paper_9,Петербургский исторический журнал № 4 (2015)УД...,2025,"18 Финляндское уголовное уложение, в связи с о...",Уголовное право Финляндии 1889 г. является одн...

In [58]:
full.to_csv('summarization.csv')

In [59]:
for index, row in full.iterrows():
    year = row['years']
    name = row['names']
    text = row['annotations_t5']
    
    os.makedirs(f'{year}_annotations', exist_ok=True)
    
    filepath = os.path.join(f'{year}_annotations', f'{name}_annotation.txt')
    with open(filepath, 'w', encoding='utf-8') as writefile:
        writefile.write(text)