In [ ]:
pip install textstat

In [6]:
import textstat

In [7]:
>>> import textstat

>>> test_data = (
    "Playing games has always been thought to be important to "
    "the development of well-balanced and creative children; "
    "however, what part, if any, they should play in the lives "
    "of adults has never been researched that deeply. I believe "
    "that playing games is every bit as important for adults "
    "as for children. Not only is taking time out to play games "
    "with our children and other adults valuable to building "
    "interpersonal relationships but is also a wonderful way "
    "to release built up tension."
)

>>> textstat.flesch_reading_ease(test_data)
>>> textstat.flesch_kincaid_grade(test_data)
>>> textstat.smog_index(test_data)
>>> textstat.coleman_liau_index(test_data)
>>> textstat.automated_readability_index(test_data)
>>> textstat.dale_chall_readability_score(test_data)
>>> textstat.difficult_words(test_data)
>>> textstat.linsear_write_formula(test_data)
>>> textstat.gunning_fog(test_data)
>>> textstat.text_standard(test_data)
>>> textstat.fernandez_huerta(test_data)
>>> textstat.szigriszt_pazos(test_data)
>>> textstat.gutierrez_polini(test_data)
>>> textstat.crawford(test_data)
>>> textstat.gulpease_index(test_data)
>>> textstat.osman(test_data)

48.0142032520325

In [4]:
import os
import pandas as pd

In [3]:
years = [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [ ]:
path = "C:\\Users\\79040\\OneDrive\\Рабочий стол\\MSP\\2 семестр HW\\HW_Sumy_T5\\10_articles"

In [5]:
texts = []

In [6]:
for root, dirs, files in os.walk(path):
  for file in files:
      if 'annotation' not in file:
        with open(os.path.join(root,file), 'r', encoding='utf-8')as f:
          text = f.read()
          name = str(file[:-4])
          year = str(file[-8:-4])
          texts += [(name, text, year)]

In [7]:
texts[:1]

[('Adrova_IMS_2013',
  "Исследование алгоритмов хеширования, используемых\nдля аутентификации в Web-приложениях\uf0a7\nЛ.С. Адрова, П.Н. Полежаев\nОренбургский государственный университет\n1. Проблема хранения пароля\nпользователя в Web-приложении\nВ настоящее время широкое распространение\nполучили различные интернет-сервисы, поэтому\nпользователи стали чаще задумываться о безопасности при работе в глобальной сети. Основной способ аутентификации в Web-приложении — использование логина и пароля, которые обычно хранятся\nв некоторой базе данных приложения. Зачастую они\nхранятся в открытом виде (даже на очень популярных сайтах), что облегчает работу злоумышленников по их получению с помощью SQL-инъекций и\nпоследующей аутентификации на сайте. Примером\nсистем управления содержимым (Content Management System, CMS), хранящих пароль в открытом\nвиде, служат Aqua CMS, jasP и Liferay.\nОдин из вариантов хранения пароля в базе данных приложения — использование хешированного\nпароля. Например, в 1C Битрикс, Drupal 6.15 и PHPNuke используются результаты применения алгоритма md5 к паролю. Radiant использует хеширование по схеме sha1(sha1(password)). В данном случае\nтруднее получить исходный пароль, однако для его\nвосстановления могут быть использованы радужные\nтаблицы, содержащие миллиарды пар «пароль –\nрезультат хеширования». Радужные таблицы доступны в интернете и составлены для всех словарных\nпаролей. Радужные таблицы могут достигать гигантских размеров, но вычисление исходного пароля будет зависеть только от времени поиска по ним.\nЯрким примером служит утечка 6,5 миллионов\nпаролей из баз данных социальной сети LinkedIn.\nАлгоритм хеширования паролей SHA-1, используемый без соли позволил злоумышленникам за шесть\nдней получить доступ к 90% паролей социальной\nсети [5].\nКроме того, в последние годы возросла вычислительная мощность GPU, они способны вычислять\nмиллиарды хешей в секунду. Поэтому в настоящее\nвремя даже длинные пароли не могут считаться\nбезопасными.\nДля решения данной проблемы необходимо использовать соль, причем уникальную для каждого\nпользователя. Использование общей соли для всех\nпользователей сайта позволяет сгенерировать единую радужную таблицу, а затем ее применить к записям всех пользователей для получения паролей.\nНеэффективность данного приема можно увидеть на примере хеширования паролей в CMS eFront\n3.6.4, которая добавляет к алгоритму хеширования\nmd5 соль, единую для всех пользователей:\nmd5(password.'cDWQR#$Rcxsc').\nВ случае уникальной соли — генерация паролей\nбессмысленна, в этом случае единственный способ\n— брутфорс (перебор паролей по словарю или полный перебор символов из набора) с последующим\nих хешированием с уникальной солью и сравнением\nс украденным хеш-значением. Примером такого\nиспользование соли может служить алгоритм хеширования Joomla — md5(password.salt).\nЧтобы предотвратить взлом паролей нужно использовать медленные хеш-функции или увеличить\nчисло раундов для быстрых хеш-функций. Одним из\nпримеров использования увеличения числа раундов\nхеш-функции может служить алгоритм хеширования CMS IPB 1.3-2.17 и MyBB 1.2.x: md5(md5(salt).\nmd5(password)).\nЦелью настоящей работы является исследование\nприменительно к аутентификации в Web-приложениях различных алгоритмов хеширования,\nразработка рекомендаций по их использованию.\n2. Исследование различных алгоритмов\nхеширования\n2.1. Анализ времени работы стандартных\nалгоритмов хеширования\nДля исследования были взяты наиболее популярные алгоритмы хеширования: MD5, SHA512,\nRIPEMD320, WHIRPOOL, TIGER и GOST. Часть из\nних входит в стандартную библиотеку .NET, другие\nв открытую библиотеку CryptSharp [3]. В результате\nисследования была определена зависимость времени их выполнения (в мс) от размера пароля (см. рисунок 1). Длина пароля варьируется от 2 до 20 символов. Время выполнения алгоритмов практически\nидентично, единственно из общего ряда выбивается\nалгоритм GOST. Время хеширования этого алгоритма достигает 0,046-0,047 мс. Но в целом время\nхеширования слишком мало, чтобы противостоять\nатаке брутфорса.\n2.2. Анализ времени работы алгоритмов\nхеширования BCRYPT и SCRYPT\nБольшее время хеширования обеспечивают алгоритмы BCRYPT [1] и SCRYPT [2]. В результате\nисследования также была определена зависимость\nвремени выполнения данных алгоритмов (в мс) от\nразмера пароля по сравнению с выше перечисленными алгоритмами хеширования (MD5, SHA512,\nRIPEMD320, WHIRPOOL, TIGER, GOST) (см. рисунок 2). Это две достаточно медленные хешфункции. Алгоритм хеширования BCRYPT использует соль для защиты от радужных таблиц. Однако\nBCRYPT был разработан в 1999 году, поэтому он\nзащищен от перебора на компьютерах того времени.\nСейчас появились ПЛИС, которые ускоряют выполнение BCRYPT для брутфорса.\nВ 2009 году был создан алгоритм SCRYPT, который работает медленнее и требует значительный\nобъем памяти, что является дополнительным достоинством. Алгоритм SCRYPT использует память со\nслучайным доступом, ее объём может настраиваться.\nУ обоих алгоритмов настраивается стоимость\nхеширования (количество внутренних раундов), у\nSCRYPT можно дополнительно изменять размер\nблока, что позволяет увеличивать время хеширования паролей.\nДанные алгоритмы были реализованы на языке\nC#, исследовалась зависимость времени выполнения SCRYPT от стоимости и размера блока,\nBCRYPT – от размера блока. Усредненные значения\nвремени в результате повторения замера 100 раз\nприведены в таблице 1.\nЕсли принять в качестве предельного времени\nаутентификации 250 мс, то наиболее близкие к нему\nзначения в 247,46 и 243,50 мс обеспечиваются алгоритмом SCRYPT при соответствующих значения\n(27, 28) и (28, 27) (первое число — стоимость, второе\n— размер блока). У BCRYPT это значение намного\nниже, порядка 167,95 мс, что значительно быстрее\nи, следовательно, уровень безопасности хеширования понижается.\n2.3. Исследование алгоритмов хеширования в\nзависимости от числа используемых раундов\nВторой подход к борьбе с полным перебором\nпаролей – увеличение числа раундов. В данном случае алгоритмы BCRYPT и SCRYPT не подходят, так\nкак не рекомендуется добавление дополнительных\nвнешних раундов. В ходе сравнительного анализа\nалгоритмов хеширования по критерию устойчивости к известным атакам обращения, нахождения\nколлизии, определения второго прообраза, выяснилось, что среди рассматриваемых алгоритмов хеширования наибольшей стойкостью обладают GOST и\nSHA512. Поэтому они и были выбрано для дальнейшего рассмотрения.\nРисунок 3 иллюстрирует зависимость времени\nработы алгоритма GOST от числа раундов, которая\nимеет линейный характер, рисунок 4 — аналогичную зависимость для алгоритма SHA512.\nМаксимальное допустимое время аутентификации достигается при ~4695 раундах. Аналогично\nдля более быстрого алгоритма SHA512 было получено значение в ~15650 раундов.\nРасчеты показывают, что при максимальном\nчисле раундов для данных алгоритмов и максимальном времени аутентификации в 250 мс перебор\n100000 наиболее распространённых словарных паролей займет приблизительно 7 часов. Это лишний\nраз подтверждает необходимость использования\nсложных, близких к случайным паролей.\nПолный перебор алфавитно-цифровых паролей\nсредней длины от 6 до 8 символов займет около\n880000 дней, что достаточно велико. Однако мощный суперкомпьютер с 1000 ядрами справится с\nэтой задачей за 2.5 года.\nВозникает вопрос – как влияет увеличение количества раундов на криптостойкость функции хеширования? Проведя математические расчеты [4],\nможно показать, что сужение выходного множества\nпосле выполнения i раундов может быть определено\nиз следующей рекуррентной формулы:\n\nЗначение сужения может быть переведено в биты с помощью функции:\nгде — число, показывающее во сколько раз\nсократилось выходное множество (в битах). На рисунке 5 приведен график зависимости r до 50000\nитераций.\nДанный график показывает медленный рост\nснижения криптостойкости с ростом числа раундов.\n3. Результаты исследования\nВ результате проведенного исследования получены следующие выводы:\n\uf02d важно использовать при хешировании паролей\nуникальную соль для защиты от радужных таблиц;\n\uf02d необходимо увеличивать время хеширования,\nдля защиты от перебора, в данном случае мы\nотдаем преимущество функции хеширования —\nSCRYPT. Данный алгоритм достаточно новый,\nимеет настраиваемый объем памяти для хеширования, а также это очень медленный алгоритм, что является важным параметром в хешировании. Оптимальное значение пар (раунды,\nразмер блока) для SCRYPT: (27, 28) и (28, 27);\n\uf02d оптимальное количество раундов для GOST-\n4695, для SHA512 — 15650, что приводит к сужению выходного множества соответственно на\n12 и 13 бит, что незначительно при его размере\nв 256 и 512 бит соответственно;\n\uf02d современные методы аутентификации по паролю защищены от полного перебора, но не от\nатаки по словарю. Очень важно, чтобы пользователи создавали случайные пароли длиной от 8\nсимволов и более, так как время перебора по\nсловарю паролей такой длины достаточно велико;\n\uf02d на основе проведенного исследования, мы рекомендуем использовать SCRYPT с заданными\nпараметрами или GOST/SHA512 с вычисленным числом раундов для большей защищенности Web-приложений от взлома паролей.",
  '2013')]

In [8]:
df = pd.DataFrame(texts, columns=['names', 'texts', 'years'])

df

,names,texts,years
0,Adrova_IMS_2013,"Исследование алгоритмов хеширования, используе...",2013
1,Balakshina_IMS_2014,Перспективы развития электронного взаимодейств...,2014
2,Erkimbaev_IMS_2015,Онтология предметной области «Наноматериалы\nи...,2015
3,Godgildieva_IMS_2016,Создание словаря валентностей русского языка\n...,2016
4,Khokhlova_IMS_2017,Сопоставительный анализ статистических мер\nна...,2017
5,Martynenko_IMS_2018,Методологические проблемы создания Компьютерно...,2018
6,Perminov_IMS_2019,Интеграция инструментов и сервисов для оценки ...,2019
7,Sokolova_IMS_2020,К вопросу о формировании набора отношений для ...,2020
8,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022
9,Vybornaya_IMS_2024,1. ВведениеДанная статья основана на результат...,2024

Sumy

In [9]:
pip install sumy

Requirement already satisfied: sumy in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (0.11.0)
Requirement already satisfied: docopt<0.7,>=0.6.1 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from sumy) (0.6.2)
Requirement already satisfied: breadability>=0.1.20 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from sumy) (0.1.20)
Requirement already satisfied: requests>=2.7.0 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from sumy) (2.32.3)
Requirement already satisfied: pycountry>=18.2.23 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from sumy) (24.6.1)
Requirement already satisfied: nltk>=3.0.2 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from sumy) (3.9.1)
Requirement already satisfied: chardet in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from breadability>=0.1.20->sumy) (5.2.0)
Requirement already satisfied: lxml>=2.0 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from breadability>=0.1.20->sumy) (5.4.0)
Requirement already satisfied: click in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.0.2->sumy) (8.1.8)
Requirement already satisfied: joblib in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.0.2->sumy) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.0.2->sumy) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from nltk>=3.0.2->sumy) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.7.0->sumy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.7.0->sumy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.7.0->sumy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.7.0->sumy) (2025.1.31)
Requirement already satisfied: colorama in c:\users\79040\appdata\roaming\python\python310\site-packages (from click->nltk>=3.0.2->sumy) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\79040\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [11]:
summarizer = LexRankSummarizer()

In [12]:
abstracts = []

In [13]:
for text in df.texts:
  doc = text
  parser = PlaintextParser.from_string(doc, Tokenizer('russian'))
  summary = summarizer(parser.document, 3)
  abstracts.append([str(sentence) for sentence in summary])

In [14]:
abstracts[:10]

[['Анализ времени работы стандартных алгоритмов хеширования Для исследования были взяты наиболее популярные алгоритмы хеширования: MD5, SHA512, RIPEMD320, WHIRPOOL, TIGER и GOST.',
  'Анализ времени работы алгоритмов хеширования BCRYPT и SCRYPT Большее время хеширования обеспечивают алгоритмы BCRYPT [1] и SCRYPT [2].',
  'Исследование алгоритмов хеширования в зависимости от числа используемых раундов Второй подход к борьбе с полным перебором паролей – увеличение числа раундов.'],
 ['Основной целью разработки УФЭБС являлась стандартизация способов и средств взаимодействия между автоматизированными системами различных разработчиков, используемых в расчетной системе ЦБ РФ для осуществления безналичных расчетов на территории Российской Федерации и взаимодействия с ней, а так же упрощение существующих форматов электронных сообщений и переход к современным стандартам обмена коммерческой информацией в электронном виде.',
  'Но подразделения ЦБ РФ Федерации не могут обеспечить свое присутствие во всех муниципальных образованиях Российской Федерации, что вынуждает государственные органы федерального казначейства заключать контракты на обслуживание расчетных счетов по обеспечению наличными деньгами с иными кредитными организациями, независимо от качества предоставляемых ими услуг и наличия электронного обмена, поскольку согласно законодательству Российской Федерации, кредитные организации могут так же выполнять функции ЦБ РФ в случае отсутствия учреждения ЦБ РФ на соответствующей территории или невозможности выполнения ЦБ РФ этих функций.',
  'Разработка «DBF Converter» может быть использована, как пример качественной реализации программных требований, которые имеет смысл воспроизвести и в проектируемой модели конвертера, но обеспечить адаптацию под требования информационного обмена между кредитными организациями и органами казначейства.'],
 ['В качестве альтернативы для нано-объектов можно использовать упомянутую в разделе 1 онтологию ChEBI, которая каждый из объектов (как молекулы, так и наноструктуры) определяет 5значным индексом.',
  'Три главных класса в проектируемой онтологии – «nanomaterials», «characterization_of_nano-objects», «characterization_of_nano-products» покрывают, по сути, основную часть предметной области.',
  'В качестве названия может быть использовано лишь одно из неформальных имен (common name).'],
 ['Более того, Теньер разделил глаголы на группы в зависимости от того, сколько актантов они могут присоединять (авалентные, одноактантые, двухактантные, трехактантные).',
  'и командировать (6 актантов) — кто?',
  'У семантических ролей с большей частотой обычно слишком общее значение, чтобы их можно было использовать таким образом.'],
 ['для',
  '4.1 Мера MI Отличительной особенностью меры MI оказалось то, что по сравнению с другими мерами она выделила наибольшее количество сочетаний с числительными и местоимениями.',
  'Так же в отличие от взаимной информации зафиксировано большое число сочетаний с существительными (23,4% vs 15,7%).'],
 ['Теоретические предпосылки Теоретическими предпосылками создания Антологии являются три источника: теория совокупности выдающегося русского статистика начала ХХ века А. А. Чупрова, статистические представления русского писателя и ученого А. А. Белого о массовом создании словарей русских писателей и системные представления выдающегося представителя русской формальной школы Ю. Н. Тынянова.',
  'После составления списка авторов каталогизируются их произведения.',
  'В основе проекта лежат идеи русской формальной школы и прежде всего системные идеи Ю. Н. Тынянова, обеспечивающие представительность авторов и их произведений на основе объективных формальных критериев.'],
 ['В связи с этим W3C предоставляет список различных инструментов для оценки атрибутов качества [3].',
  'На данный момент их количество уже также превысило сотню, при этом ни один их них не является универсальным, что не упрощает задачу.',
  'Она состоит из следующих элементов: стратегия (Strategy), рамки (Scope), структура (Structure), компоновку (Composition) и поверхность (Surface).'],
 ['Обобщение типов похожих риторических отношений Мы обсудим набор РО, определённый для корпуса Ru-RSTreebank, см. ([17, c.',
  'Если (4b) можно отнести к интерпретации, то (4c) – это оценка.',
  'Это РО Result или Effect и Condition или Othewise.'],
 ['Основная задача LI на основе N-грамм состоит в том, чтобы сгенерировать набор частотных профилей N-грамм для каждого языка, который необходимо идентифицировать.',
  'В процессе обучения модели на выборке с уникальными словоформами были извлечены 14262 различных 3-граммы.',
  'Извлеченные 3-граммы Количество\tПокрытие всех 3-грамм Из якутских словоформ\t6552\t45% Из русских заимствований\t11857\t83% Рис. 1.'],
 ['При  этом  как  каузатив,  так и квалификатив  для  предлога  «по»  обнаруживают  одинаковую  частотность:  на  каждую из синтаксем приходится примерно по 100 контекстов.2.1.5.',
  'Предлог «с» Предлог «с» представлен в базе данных 768 контекстами и, как и первый по частотности предлог  «в»,  охватывает  13  синтаксем  (рис.  5).',
  'Нельзя не заметить, что в случае с предлогом «между» все контексты размечаются однозначно, мы не  наблюдаем  двух  семантических  меток  (тематив  и  объект)  у  конструкций  с  данным предлогом.']]

In [15]:
annotations = []

In [16]:
for abstr in enumerate(abstracts, start=1):
  print(f'Аннотация статьи {abstr[0]}:')
  annotation = str(' '.join(abstr[1]))
  annotations.append(annotation)
  print(annotation, '\n\n')

Аннотация статьи 1:
Анализ времени работы стандартных алгоритмов хеширования Для исследования были взяты наиболее популярные алгоритмы хеширования: MD5, SHA512, RIPEMD320, WHIRPOOL, TIGER и GOST. Анализ времени работы алгоритмов хеширования BCRYPT и SCRYPT Большее время хеширования обеспечивают алгоритмы BCRYPT [1] и SCRYPT [2]. Исследование алгоритмов хеширования в зависимости от числа используемых раундов Второй подход к борьбе с полным перебором паролей – увеличение числа раундов.


Аннотация статьи 2:
Основной целью разработки УФЭБС являлась стандартизация способов и средств взаимодействия между автоматизированными системами различных разработчиков, используемых в расчетной системе ЦБ РФ для осуществления безналичных расчетов на территории Российской Федерации и взаимодействия с ней, а так же упрощение существующих форматов электронных сообщений и переход к современным стандартам обмена коммерческой информацией в электронном виде. Но подразделения ЦБ РФ Федерации не могут обеспечить свое присутствие во всех муниципальных образованиях Российской Федерации, что вынуждает государственные органы федерального казначейства заключать контракты на обслуживание расчетных счетов по обеспечению наличными деньгами с иными кредитными организациями, независимо от качества предоставляемых ими услуг и наличия электронного обмена, поскольку согласно законодательству Российской Федерации, кредитные организации могут так же выполнять функции ЦБ РФ в случае отсутствия учреждения ЦБ РФ на соответствующей территории или невозможности выполнения ЦБ РФ этих функций. Разработка «DBF Converter» может быть использована, как пример качественной реализации программных требований, которые имеет смысл воспроизвести и в проектируемой модели конвертера, но обеспечить адаптацию под требования информационного обмена между кредитными организациями и органами казначейства.


Аннотация статьи 3:
В качестве альтернативы для нано-объектов можно использовать упомянутую в разделе 1 онтологию ChEBI, которая каждый из объектов (как молекулы, так и наноструктуры) определяет 5значным индексом. Три главных класса в проектируемой онтологии – «nanomaterials», «characterization_of_nano-objects», «characterization_of_nano-products» покрывают, по сути, основную часть предметной области. В качестве названия может быть использовано лишь одно из неформальных имен (common name).


Аннотация статьи 4:
Более того, Теньер разделил глаголы на группы в зависимости от того, сколько актантов они могут присоединять (авалентные, одноактантые, двухактантные, трехактантные). и командировать (6 актантов) — кто? У семантических ролей с большей частотой обычно слишком общее значение, чтобы их можно было использовать таким образом.


Аннотация статьи 5:
для 4.1 Мера MI Отличительной особенностью меры MI оказалось то, что по сравнению с другими мерами она выделила наибольшее количество сочетаний с числительными и местоимениями. Так же в отличие от взаимной информации зафиксировано большое число сочетаний с существительными (23,4% vs 15,7%).


Аннотация статьи 6:
Теоретические предпосылки Теоретическими предпосылками создания Антологии являются три источника: теория совокупности выдающегося русского статистика начала ХХ века А. А. Чупрова, статистические представления русского писателя и ученого А. А. Белого о массовом создании словарей русских писателей и системные представления выдающегося представителя русской формальной школы Ю. Н. Тынянова. После составления списка авторов каталогизируются их произведения. В основе проекта лежат идеи русской формальной школы и прежде всего системные идеи Ю. Н. Тынянова, обеспечивающие представительность авторов и их произведений на основе объективных формальных критериев.


Аннотация статьи 7:
В связи с этим W3C предоставляет список различных инструментов для оценки атрибутов качества [3]. На данный момент их количество уже также превысило сотню, при этом ни один их них не является универсальным, что не упрощает задачу. Она состоит из следующих элементов: стратегия (Strategy), рамки (Scope), структура (Structure), компоновку (Composition) и поверхность (Surface).


Аннотация статьи 8:
Обобщение типов похожих риторических отношений Мы обсудим набор РО, определённый для корпуса Ru-RSTreebank, см. ([17, c. Если (4b) можно отнести к интерпретации, то (4c) – это оценка. Это РО Result или Effect и Condition или Othewise.


Аннотация статьи 9:
Основная задача LI на основе N-грамм состоит в том, чтобы сгенерировать набор частотных профилей N-грамм для каждого языка, который необходимо идентифицировать. В процессе обучения модели на выборке с уникальными словоформами были извлечены 14262 различных 3-граммы. Извлеченные 3-граммы Количество	Покрытие всех 3-грамм Из якутских словоформ	6552	45% Из русских заимствований	11857	83% Рис. 1.


Аннотация статьи 10:
При  этом  как  каузатив,  так и квалификатив  для  предлога  «по»  обнаруживают  одинаковую  частотность:  на  каждую из синтаксем приходится примерно по 100 контекстов.2.1.5. Предлог «с» Предлог «с» представлен в базе данных 768 контекстами и, как и первый по частотности предлог  «в»,  охватывает  13  синтаксем  (рис.  5). Нельзя не заметить, что в случае с предлогом «между» все контексты размечаются однозначно, мы не  наблюдаем  двух  семантических  меток  (тематив  и  объект)  у  конструкций  с  данным предлогом.

In [17]:
annots = pd.DataFrame(annotations, columns=['annotations_sumy'])

In [18]:
sumy = pd.concat([df, annots], join='outer', axis=1)
sumy

,names,texts,years,annotations_sumy
0,Adrova_IMS_2013,"Исследование алгоритмов хеширования, используе...",2013,Анализ времени работы стандартных алгоритмов х...
1,Balakshina_IMS_2014,Перспективы развития электронного взаимодейств...,2014,Основной целью разработки УФЭБС являлась станд...
2,Erkimbaev_IMS_2015,Онтология предметной области «Наноматериалы\nи...,2015,В качестве альтернативы для нано-объектов можн...
3,Godgildieva_IMS_2016,Создание словаря валентностей русского языка\n...,2016,"Более того, Теньер разделил глаголы на группы ..."
4,Khokhlova_IMS_2017,Сопоставительный анализ статистических мер\nна...,2017,для 4.1 Мера MI Отличительной особенностью мер...
5,Martynenko_IMS_2018,Методологические проблемы создания Компьютерно...,2018,Теоретические предпосылки Теоретическими предп...
6,Perminov_IMS_2019,Интеграция инструментов и сервисов для оценки ...,2019,В связи с этим W3C предоставляет список различ...
7,Sokolova_IMS_2020,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...
8,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022,Основная задача LI на основе N-грамм состоит в...
9,Vybornaya_IMS_2024,1. ВведениеДанная статья основана на результат...,2024,"При этом как каузатив, так и квалификатив ..."

T5

In [19]:
!pip install transformers

Requirement already satisfied: transformers in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (4.49.0)
Requirement already satisfied: filelock in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.29.3)
Requirement already satisfied: numpy>=1.17 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\79040\appdata\roaming\python\python310\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\79040\appdata\roaming\python\python310\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\users\79040\appdata\roaming\python\python310\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\79040\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (2025.1.31)

In [20]:
from transformers import AutoModelForSeq2SeqLM, T5TokenizerFast

c:\Users\79040\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [21]:
import torch
from transformers import AutoTokenizer, AutoModelWithLMHead, T5ForConditionalGeneration

RuT5-base-sum

In [22]:
model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

In [23]:
for i, text in enumerate (df.texts[:10]):
  article_text = text
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  output_ids = model.generate(input_ids=input_ids, no_repeat_ngram_size=4)[0]
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  print(f'Аннотация текста {i+1}:\n {summary}\n\n')

Аннотация текста 1:
 Для решения проблемы хранения пароля пользователя в Web-приложениях необходимо использовать соль, причем уникальную для каждого пользователя, а также использовать радужные таблицы, содержащие миллиарды пар «пароль – результат хеширования». В настоящее время даже длинные пароли не могут считаться безопасными.


Аннотация текста 2:
 Взаимодействие между кредитными организациями и государственными финансовыми учетными системами исполнения бюджетов в процессе осуществления безналичных и налично-денежных расчетов обусловлено анализом возникающих проблем исполнения бюджета и ужесточением требований к качеству, достоверности и своевременности проводимых платежей со стороны законодательной власти Российской Федерации.


Аннотация текста 3:
 Онтология предметной области «Наноматериалы и их применение» может стать идеальным средством для концептуализации предметной области.


Аннотация текста 4:
 Создание словаря валентностей русского языка на основе компьютерного словаря чешского языка Verbalex было проведено в рамках XIX Объединенной конференции «Интернет современное общество» IMS-2015 в Санкт-Петербурге. Для этого необходимо создать систему описания синтаксических и семантических связей глагола таким образом, чтобы ею могли пользоваться и автоматизированные системы, и человек.


Аннотация текста 5:
 Статистические метрики позволяют вычислять силу связанности словосочетаний в текстах. Это позволяет вычислить устойчивость лексических единиц, позволяющих расположить их на шкале.


Аннотация текста 6:
 Компьютерная антология русского рассказа как языковой ресурс для исследования языка и стиля русской художественной прозы в эпоху революционных перемен (первой трети XX века).


Аннотация текста 7:
 Интеграция инструментов и сервисов для оценки веб-интерфейсов пользователя и выявления юзабилити рисков в Новосибирском государственном техническом университете. В данной работе рассматриваются разновидности пользовательских интерфейсов, которые представляют собой совокупность средств и методов для взаимодействия пользователя с вычислительными устройствами.


Аннотация текста 8:
 Корпусы с дискурсивной разметкой текста становятся все более интересными для исследователей, в том числе и для компьютерной лингвистики. В настоящее время дискурсивная структура часто рассматривается в связи с другими составляющими организации текста, в частности, отношениями кореферентности.


Аннотация текста 9:
 Введение русских заимствований в якутских текстах — одна из основных источников новых терминов и имен собственных в якутском языке. Однако, по мнению авторов, русский язык до сих пор является важным источником новых имен собственных.


Аннотация текста 10:
 Предлоги и предложные конструкции могут быть представлены сразу несколькими парами «предлог — падежная форма» и «стоп-слова». В настоящее время исследователи считают, что предлоги представляют собой весьма неоднородную группу с неясными и неструктурированными значениями, а значит, передают четкие семантико-синтаксические отношения между знаменательными словами.

In [24]:
annotations_t5 = []

for text in df.texts:
  article_text = text
  input_ids = tokenizer([article_text], max_length=600, add_special_tokens=True, padding="max_length", truncation=True, return_tensors="pt")["input_ids"]
  output_ids = model.generate(input_ids=input_ids, min_length=50, max_length=250, no_repeat_ngram_size=4)[0]
  summary = tokenizer.decode(output_ids, skip_special_tokens=True)
  print(f'Аннотация текста:\n {summary}\n\n')
  annotations_t5.append(str(''.join(summary)))

Аннотация текста:
 Для решения проблемы хранения пароля пользователя в Web-приложениях необходимо использовать соль, причем уникальную для каждого пользователя, а также использовать радужные таблицы, содержащие миллиарды пар «пароль – результат хеширования». В настоящее время даже длинные пароли не могут считаться безопасными.


Аннотация текста:
 Взаимодействие между кредитными организациями и государственными финансовыми учетными системами исполнения бюджетов в процессе осуществления безналичных и налично-денежных расчетов обусловлено анализом возникающих проблем исполнения бюджета и ужесточением требований к качеству, достоверности и своевременности проводимых платежей со стороны законодательной власти Российской Федерации.


Аннотация текста:
 Онтология предметной области «Наноматериалы и их применение» может стать идеальным средством для концептуализации предметной области. В настоящее время онтологи являются инструментом для разработки и распространения научного знания для различных естественных наук, в том числе биологии, химии, наук о Земле и других наук.


Аннотация текста:
 Создание словаря валентностей русского языка на основе компьютерного словаря чешского языка Verbalex было проведено в рамках XIX Объединенной конференции «Интернет современное общество» IMS-2015 в Санкт-Петербурге. Для этого необходимо создать систему описания синтаксических и семантических связей глагола таким образом, чтобы ею могли пользоваться и автоматизированные системы, и человек.


Аннотация текста:
 Статистические метрики позволяют вычислять силу связанности словосочетаний в текстах. Это позволяет вычислить устойчивость лексических единиц, позволяющих расположить их на шкале.


Аннотация текста:
 Компьютерная антология русского рассказа как языковой ресурс для исследования языка и стиля русской художественной прозы в эпоху революционных перемен (первой трети XX века) — одна из самых драматических эпох русской истории.


Аннотация текста:
 Интеграция инструментов и сервисов для оценки веб-интерфейсов пользователя и выявления юзабилити рисков в Новосибирском государственном техническом университете. В данной работе рассматриваются разновидности пользовательских интерфейсов, которые представляют собой совокупность средств и методов для взаимодействия пользователя с вычислительными устройствами.


Аннотация текста:
 Корпусы с дискурсивной разметкой текста становятся все более интересными для исследователей, в том числе и для компьютерной лингвистики. В настоящее время дискурсивная структура часто рассматривается в связи с другими составляющими организации текста, в частности, отношениями кореферентности.


Аннотация текста:
 Введение русских заимствований в якутских текстах — одна из основных источников новых терминов и имен собственных в якутском языке. Однако, по мнению авторов, русский язык до сих пор является важным источником новых имен собственных.


Аннотация текста:
 Предлоги и предложные конструкции могут быть представлены сразу несколькими парами «предлог — падежная форма» и «стоп-слова». В настоящее время исследователи считают, что предлоги представляют собой весьма неоднородную группу с неясными и неструктурированными значениями, а значит, передают четкие семантико-синтаксические отношения между знаменательными словами.

In [25]:
annots_t5 = pd.DataFrame(annotations_t5, columns=['annotations_t5'])

In [26]:
full = pd.concat([sumy, annots_t5], join='outer', axis=1)
full

,names,texts,years,annotations_sumy,annotations_t5
0,Adrova_IMS_2013,"Исследование алгоритмов хеширования, используе...",2013,Анализ времени работы стандартных алгоритмов х...,Для решения проблемы хранения пароля пользоват...
1,Balakshina_IMS_2014,Перспективы развития электронного взаимодейств...,2014,Основной целью разработки УФЭБС являлась станд...,Взаимодействие между кредитными организациями ...
2,Erkimbaev_IMS_2015,Онтология предметной области «Наноматериалы\nи...,2015,В качестве альтернативы для нано-объектов можн...,Онтология предметной области «Наноматериалы и ...
3,Godgildieva_IMS_2016,Создание словаря валентностей русского языка\n...,2016,"Более того, Теньер разделил глаголы на группы ...",Создание словаря валентностей русского языка н...
4,Khokhlova_IMS_2017,Сопоставительный анализ статистических мер\nна...,2017,для 4.1 Мера MI Отличительной особенностью мер...,Статистические метрики позволяют вычислять сил...
5,Martynenko_IMS_2018,Методологические проблемы создания Компьютерно...,2018,Теоретические предпосылки Теоретическими предп...,Компьютерная антология русского рассказа как я...
6,Perminov_IMS_2019,Интеграция инструментов и сервисов для оценки ...,2019,В связи с этим W3C предоставляет список различ...,Интеграция инструментов и сервисов для оценки ...
7,Sokolova_IMS_2020,К вопросу о формировании набора отношений для ...,2020,Обобщение типов похожих риторических отношений...,Корпусы с дискурсивной разметкой текста станов...
8,Vissio_IMS_2022,Выделение русских заимствований в якутских тек...,2022,Основная задача LI на основе N-грамм состоит в...,Введение русских заимствований в якутских текс...
9,Vybornaya_IMS_2024,1. ВведениеДанная статья основана на результат...,2024,"При этом как каузатив, так и квалификатив ...",Предлоги и предложные конструкции могут быть п...

In [27]:
full.to_csv('summarization.csv')